# Step 0: Importing Api and Packages

In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
sns.set('notebook', font_scale=1.25, style='whitegrid')

from pathlib import Path
import re

import nba_api
import nba_api.stats.endpoints as ep
from nba_api.stats.static import teams

import xgboost as xgb

import re
import unicodedata

from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
from nba_api.stats.endpoints import (
    leaguedashplayerstats,
    PlayerEstimatedMetrics,
    ScheduleLeagueV2,
    LeagueDashPlayerBioStats,
    GravityLeaders,
    LeagueDashPlayerShotLocations,
    LeagueDashPlayerStats,
    LeagueDashPtDefend,
    LeagueDashPlayerPtShot,
    ScheduleLeagueV2,
)

# Seasons to pull
SEASONS = [
    "2021-22",
    "2022-23",
    "2023-24",
    "2024-25",
    "2025-26",
    "2026-27",
]

endpoints = {
    "ScheduleLeagueV2": ScheduleLeagueV2,
    "LeagueDashPlayerBioStats": LeagueDashPlayerBioStats,
    "GravityLeaders": GravityLeaders,
    "LeagueDashPlayerShotLocations": LeagueDashPlayerShotLocations,
    "LeagueDashPlayerStats": LeagueDashPlayerStats,
    "LeagueDashPtDefend": LeagueDashPtDefend,
    "LeagueDashPlayerPtShot": LeagueDashPlayerPtShot,
    "ScheduleLeagueV2": ScheduleLeagueV2,
}

## Retrieving Data

# Step 1: Retrieve Dataframes From NBA API

To improve performance, I’ll pull the remote API dataframes locally so they can be accessed more efficiently during manipulation and analysis.

In [3]:
# OUTPUT_DIR = "/Users/ronanhwang/Downloads/Github/nba_2020s/csv_files"

# os.makedirs(OUTPUT_DIR, exist_ok = True)

# # Helper function to convert SEASONS to seasons in api
# def season_filename(season, endpoint_name):
#     start, end = season.split("-")
#     season_short = f"{start[-2:]}_{end[-2:]}"
#     return f"{season_short}{endpoint_name}.csv"


# for season in SEASONS:

#     print(f"SEASON: {season}")

#     for name, endpoint in endpoints.items():

#         filename = season_filename(season, name)

#         filepath = os.path.join(OUTPUT_DIR, filename)

#         print(f"\nPulling {name}...")

#         try:
#             # Different endpoints have different args
#             if name == "ScheduleLeagueV2":

#                 response = endpoint(
#                     league_id="00",
#                     season=season,
#                 )

#             else:

#                 response = endpoint(
#                     season=season,
#                     season_type_all_star="Regular Season",
#                 )

#             # Get DataFrame
#             df = response.get_data_frames()[0]

#             # Export
#             df.to_csv(filepath, index = False)

#             print(f"Exported: {filename}")
#             print(f"Shape: {df.shape}")

#             # Read CSV back in
#             df_check = pd.read_csv(filepath)

#             print(f"\nHead of {filename}:")
#             print(df_check.head())

#             # Look for season columns
#             season_cols = [
#                 col
#                 for col in df_check.columns
#                 if "SEASON" in col.upper()
#                 or "YEAR" in col.upper()
#             ]

#             if season_cols:
#                 print("\nSeason information:")

#                 for col in season_cols:
#                     print(
#                         f"  {col}: "
#                         f"{df_check[col].dropna().unique()[:10]}"
#                     )

#         except Exception as e:

#             print(f"ERROR pulling {name} for {season}:")
#             print(e)

# Step 2: Read in Data

In [4]:
CSV_DIR = Path("/Users/ronanhwang/Downloads/Github/nba_2020s/csv_files")


# Helper function that laods all NBA CSV files from csv_files directory
# Expects 23_24LeagueDashPlayerStats.csv format
# Returns 
    # data = {
        # "23_24": {
        #     "LeagueDashPlayerStats": DataFrame,
        #     "GravityLeaders": DataFrame,
        #     ...
        # },
def load_nba_csvs(csv_dir):
    data = {}

    # Loop through every CSV in the directory
    for filepath in csv_dir.glob("*.csv"):

        filename = filepath.name

        # Extract season from beginning of filename
        match = re.match(r"^(\d{2}_\d{2})(.+)\.csv$", filename)

        if not match:
            print(f"Skipping unrecognized filename: {filename}")
            continue

        season = match.group(1)
        endpoint = match.group(2)

        # Create season dictionary if necessary
        if season not in data:
            data[season] = {}

        # Read CSV
        df = pd.read_csv(filepath)

        # Store DataFrame
        data[season][endpoint] = df

        print(f"{filename} -> {season} / {endpoint} | Shape: {df.shape}")

    return data

In [5]:
data = load_nba_csvs(CSV_DIR)

26_27LeagueDashPlayerBioStats.csv -> 26_27 / LeagueDashPlayerBioStats | Shape: (582, 23)
24_25ScheduleLeagueV2.csv -> 24_25 / ScheduleLeagueV2 | Shape: (1400, 159)
22_23LeagueDashPtDefend.csv -> 22_23 / LeagueDashPtDefend | Shape: (535, 14)
21_22LeagueDashPlayerStats.csv -> 21_22 / LeagueDashPlayerStats | Shape: (605, 67)
26_27LeagueDashPlayerShotLocations.csv -> 26_27 / LeagueDashPlayerShotLocations | Shape: (583, 30)
23_24LeagueDashPlayerShotLocations.csv -> 23_24 / LeagueDashPlayerShotLocations | Shape: (573, 30)
23_24LeagueDashPlayerPtShot.csv -> 23_24 / LeagueDashPlayerPtShot | Shape: (568, 20)
26_27NBA2k.csv -> 26_27 / NBA2k | Shape: (650, 46)
23_24ScheduleLeagueV2.csv -> 23_24 / ScheduleLeagueV2 | Shape: (1396, 184)
21_22LeagueDashPlayerPtShot.csv -> 21_22 / LeagueDashPlayerPtShot | Shape: (596, 20)
25_26Misc.csv -> 25_26 / Misc | Shape: (582, 20)
23_24LeagueDashPlayerBioStats.csv -> 23_24 / LeagueDashPlayerBioStats | Shape: (572, 23)
25_26LeagueDashPlayerPtShot.csv -> 25_26 / LeagueDashPlayerPtShot | Shape: (582, 20)
21_22LeagueDashPtDefend.csv -> 21_22 / LeagueDashPtDefend | Shape: (595, 14)
24_25LeagueDashPlayerBioStats.csv -> 24_25 / LeagueDashPlayerBioStats | Shape: (569, 23)
25_26LeagueDashPlayerStats.csv -> 25_26 / LeagueDashPlayerStats | Shape: (582, 69)
26_27LeagueDashPtDefend.csv -> 26_27 / LeagueDashPtDefend | Shape: (580, 14)
21_22LeagueDashPlayerBioStats.csv -> 21_22 / LeagueDashPlayerBioStats | Shape: (605, 23)
26_27ScheduleLeagueV2.csv -> 26_27 / ScheduleLeagueV2 | Shape: (1274, 160)
22_23ScheduleLeagueV2.csv -> 22_23 / ScheduleLeagueV2 | Shape: (1394, 151)
21_22ScheduleLeagueV2.csv -> 21_22 / ScheduleLeagueV2 | Shape: (1393, 152)
21_22LeagueDashPlayerShotLocations.csv -> 21_22 / LeagueDashPlayerShotLocations | Shape: (606, 30)
25_26ScheduleLeagueV2.csv -> 25_26 / ScheduleLeagueV2 | Shape: (1400, 206)
25_26GravityLeaders.csv -> 25_26 / GravityLeaders | Shape: (234, 27)
25_26LeagueDashPtDefend.csv -> 25_26 / LeagueDashPtDefend | Shape: (580, 14)
24_25LeagueDashPlayerShotLocations.csv -> 24_25 / LeagueDashPlayerShotLocations | Shape: (570, 30)
26_27Rosters.csv -> 26_27 / Rosters | Shape: (596, 8)
24_25LeagueDashPlayerPtShot.csv -> 24_25 / LeagueDashPlayerPtShot | Shape: (566, 20)
21_22Misc.csv -> 21_22 / Misc | Shape: (605, 20)
23_24LeagueDashPlayerStats.csv -> 23_24 / LeagueDashPlayerStats | Shape: (572, 67)
25_26LeagueDashPlayerBioStats.csv -> 25_26 / LeagueDashPlayerBioStats | Shape: (582, 23)
23_24LeagueDashPtDefend.csv -> 23_24 / LeagueDashPtDefend | Shape: (569, 14)
22_23LeagueDashPlayerStats.csv -> 22_23 / LeagueDashPlayerStats | Shape: (539, 67)
25_26LeagueDashPlayerShotLocations.csv -> 25_26 / LeagueDashPlayerShotLocations | Shape: (583, 30)
23_24Misc.csv -> 23_24 / Misc | Shape: (572, 20)
24_25LeagueDashPlayerStats.csv -> 24_25 / LeagueDashPlayerStats | Shape: (569, 67)
22_23Misc.csv -> 22_23 / Misc | Shape: (539, 20)
24_25LeagueDashPtDefend.csv -> 24_25 / LeagueDashPtDefend | Shape: (568, 14)
26_27GravityLeaders.csv -> 26_27 / GravityLeaders | Shape: (234, 27)
24_25Misc.csv -> 24_25 / Misc | Shape: (569, 20)
22_23LeagueDashPlayerPtShot.csv -> 22_23 / LeagueDashPlayerPtShot | Shape: (537, 20)
22_23LeagueDashPlayerBioStats.csv -> 22_23 / LeagueDashPlayerBioStats | Shape: (539, 23)
26_27LeagueDashPlayerStats.csv -> 26_27 / LeagueDashPlayerStats | Shape: (582, 69)
26_27LeagueDashPlayerPtShot.csv -> 26_27 / LeagueDashPlayerPtShot | Shape: (582, 20)
22_23LeagueDashPlayerShotLocations.csv -> 22_23 / LeagueDashPlayerShotLocations | Shape: (540, 30)
26_27Misc.csv -> 26_27 / Misc | Shape: (582, 20)

## See all .csv files

In [6]:
for season, endpoints in data.items():
    print(f"\n{season}")

    for endpoint, df in endpoints.items():
        print(f"  {endpoint}: {df.shape}")

26_27
  LeagueDashPlayerBioStats: (582, 23)
  LeagueDashPlayerShotLocations: (583, 30)
  NBA2k: (650, 46)
  LeagueDashPtDefend: (580, 14)
  ScheduleLeagueV2: (1274, 160)
  Rosters: (596, 8)
  GravityLeaders: (234, 27)
  LeagueDashPlayerStats: (582, 69)
  LeagueDashPlayerPtShot: (582, 20)
  Misc: (582, 20)

24_25
  ScheduleLeagueV2: (1400, 159)
  LeagueDashPlayerBioStats: (569, 23)
  LeagueDashPlayerShotLocations: (570, 30)
  LeagueDashPlayerPtShot: (566, 20)
  LeagueDashPlayerStats: (569, 67)
  LeagueDashPtDefend: (568, 14)
  Misc: (569, 20)

22_23
  LeagueDashPtDefend: (535, 14)
  ScheduleLeagueV2: (1394, 151)
  LeagueDashPlayerStats: (539, 67)
  Misc: (539, 20)
  LeagueDashPlayerPtShot: (537, 20)
  LeagueDashPlayerBioStats: (539, 23)
  LeagueDashPlayerShotLocations: (540, 30)

21_22
  LeagueDashPlayerStats: (605, 67)
  LeagueDashPlayerPtShot: (596, 20)
  LeagueDashPtDefend: (595, 14)
  LeagueDashPlayerBioStats: (605, 23)
  ScheduleLeagueV2: (1393, 152)
  LeagueDashPlayerShotLocations: (606, 30)
  Misc: (605, 20)

23_24
  LeagueDashPlayerShotLocations: (573, 30)
  LeagueDashPlayerPtShot: (568, 20)
  ScheduleLeagueV2: (1396, 184)
  LeagueDashPlayerBioStats: (572, 23)
  LeagueDashPlayerStats: (572, 67)
  LeagueDashPtDefend: (569, 14)
  Misc: (572, 20)

25_26
  Misc: (582, 20)
  LeagueDashPlayerPtShot: (582, 20)
  LeagueDashPlayerStats: (582, 69)
  ScheduleLeagueV2: (1400, 206)
  GravityLeaders: (234, 27)
  LeagueDashPtDefend: (580, 14)
  LeagueDashPlayerBioStats: (582, 23)
  LeagueDashPlayerShotLocations: (583, 30)

# Step 2.5: Update 2026_27 Data

In [7]:
# Helper function that updates the teams using rosters taken from nba.com
def update_teams_from_rosters(data, season="26_27"):
    rosters = data[season]["Rosters"].copy()
    stats = data[season]["LeagueDashPlayerStats"].copy()

    # Team ids
    team_id_map = {
        "ATL": 1610612737,
        "BOS": 1610612738,
        "CLE": 1610612739,
        "NOP": 1610612740,
        "CHI": 1610612741,
        "DAL": 1610612742,
        "DEN": 1610612743,
        "GSW": 1610612744,
        "HOU": 1610612745,
        "LAC": 1610612746,
        "LAL": 1610612747,
        "MIA": 1610612748,
        "MIL": 1610612749,
        "MIN": 1610612750,
        "BKN": 1610612751,
        "NYK": 1610612752,
        "ORL": 1610612753,
        "IND": 1610612754,
        "PHI": 1610612755,
        "PHX": 1610612756,
        "POR": 1610612757,
        "SAC": 1610612758,
        "SAS": 1610612759,
        "OKC": 1610612760,
        "TOR": 1610612761,
        "UTA": 1610612762,
        "MEM": 1610612763,
        "WAS": 1610612764,
        "DET": 1610612765,
        "CHA": 1610612766,
    }

    # Clean player names
    rosters["Player_clean"] = (
        rosters["Player"]
        .astype(str)
        .str.replace("\n", " ", regex=False)
        .str.strip()
    )

    stats["PLAYER_NAME_clean"] = (
        stats["PLAYER_NAME"]
        .astype(str)
        .str.strip()
    )

    # Build player and team
    roster_lookup = (
        rosters
        .drop_duplicates("Player_clean")
        .set_index("Player_clean")
    )

    # Match stats to player
    mapped_team = stats["PLAYER_NAME_clean"].map(
        roster_lookup["Team"]
    )

    matched = mapped_team.notna()
    unmatched = ~matched

    # Update team abbv and id and match player to team, FA if none
    stats["TEAM_ABBREVIATION"] = mapped_team

    stats.loc[unmatched, "TEAM_ABBREVIATION"] = "FA"

    stats["TEAM_ID"] = (
        stats["TEAM_ABBREVIATION"]
        .map(team_id_map)
        .fillna(0)
        .astype("int64")
    )

    # Add roster players missing from stats
    stats_names = set(stats["PLAYER_NAME_clean"])
    roster_names = set(rosters["Player_clean"])

    missing_in_stats = roster_names - stats_names

    if missing_in_stats:
        # Previous season
        previous_season = f"{int(season[:2]) - 1:02d}_{int(season[3:]) - 1:02d}"

        # Example:
        # 26_27 -> 25_26
        if season == "26_27":
            previous_season = "24_25"

        previous_stats = data[previous_season]["LeagueDashPlayerStats"].copy()

        previous_stats["PLAYER_NAME_clean"] = (
            previous_stats["PLAYER_NAME"]
            .astype(str)
            .str.strip()
        )

        previous_lookup = (
            previous_stats
            .drop_duplicates("PLAYER_NAME_clean")
            .set_index("PLAYER_NAME_clean")
        )

        # Numeric columns in current stats
        numeric_cols = stats.select_dtypes(
            include="number"
        ).columns.tolist()

        new_rows = []

        for name in missing_in_stats:

            # Current roster team
            team = roster_lookup.loc[name, "Team"]
            team_id = team_id_map.get(team, 0)

            # Case 1: Player existed in previous season
            if name in previous_lookup.index:

                previous_row = previous_lookup.loc[name].copy()

                if isinstance(previous_row, pd.DataFrame):
                    previous_row = previous_row.iloc[0]

                # Start with an empty current-season row
                row = pd.Series(index=stats.columns, dtype="object")

                # Copy over whatever previous-season stats exist
                for col in stats.columns:
                    if col in previous_row.index:
                        row[col] = previous_row[col]

                # Current season player and team info
                row["PLAYER_NAME"] = name
                row["TEAM_ABBREVIATION"] = team
                row["TEAM_ID"] = team_id

                if "TEAM" in row.index:
                    row["TEAM"] = team

                if "Team" in row.index:
                    row["Team"] = team

            # Case 2: Player did NOT exist in previous season either
            else:

                row = pd.Series(index=stats.columns, dtype="object")

                row["PLAYER_NAME"] = name
                row["TEAM_ABBREVIATION"] = team
                row["TEAM_ID"] = team_id
                row["AGE"] = 0

                # Zero out numeric stats
                for col in numeric_cols:
                    row[col] = 0

            new_rows.append(row)

        # Append all new rows at once
        if new_rows:
            new_rows_df = pd.DataFrame(new_rows)

            stats = pd.concat(
                [stats, new_rows_df],
                ignore_index=True
            )

    # Clean temp
    stats.drop(
        columns="PLAYER_NAME_clean",
        inplace=True,
        errors="ignore"
    )

    # Save
    data[season]["LeagueDashPlayerStats"] = stats

    return data

In [8]:
data = update_teams_from_rosters(data, "26_27")

# Step 3: Cleaning Data

In [9]:
# Helper function that cleans all NBA DataFrames stored in the data dictionary by dropping/renaming
# Expects: data[season][endpoint] = DataFrame
# Returns: Cleaned data dictionary.
def clean_nba_data(data):
    
    # Columns to drop from LeagueDashPlayerStats
    player_stats_drop = [
        'WNBA_FANTASY_PTS', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK',
        'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK',
        'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK',
        'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK', 'TOV_RANK',
        'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK',
        'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK',
        'TD3_RANK', 'WNBA_FANTASY_PTS_RANK', 'FP_HIGH_SCORE_RANK',
        'TEAM_COUNT'
    ]

    # Columns to drop from LeagueDashPtDefend
    pt_defend_drop = [
        'AGE', 'GP', 'G'
    ]

    # Rename LeagueDashPtDefend columns
    pt_defend_rename = {
        "CLOSE_DEF_PERSON_ID": "D_PLAYER_ID",
        "PLAYER_NAME": "D_PLAYER_NAME",
        "PLAYER_LAST_TEAM_ID": "D_PLAYER_LAST_TEAM_ID",
        "PLAYER_LAST_TEAM_ABBREVIATION": "D_PLAYER_LAST_TEAM_ABBREVIATION",
        "PLAYER_POSITION": "D_PLAYER_POSITION",
        "FREQ": "D_FREQ",
        "NORMAL_FG_PCT": "D_NORMAL_FG_PCT",
        "PCT_PLUSMINUS": "D_PCT_PLUSMINUS",
    }

    # Rename LeagueDashPlayerShotLocations columns
    shot_locations_rename = {
        "Unnamed: 0": "PLAYER_ID",
        "Unnamed: 1": "PLAYER_NAME",
        "Unnamed: 2": "TEAM_ID",
        "Unnamed: 3": "TEAM_ABBREVIATION",
        "Unnamed: 4": "AGE",
        "Unnamed: 5": "NICKNAME",
    }

    # Columns to drop from LeagueDashPlayerPtShot
    pt_shot_drop = [
        'AGE', 'GP', 'FGM', 'FGA',
        'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT'
    ]

    # Columns to keep from ScheduleLeagueV2
    schedule_keep = [
        'seasonYear',
        'gameDate',
        'gameId',
        'gameCode',
        'gameStatusText',
        'gameSequence',
        'gameDateTimeEst',
        'seriesGameNumber',
        'gameLabel',
        'gameSubLabel',
        'seriesText',
        'postponedStatus',
        'isNeutral',
        'homeTeam_teamId',
        'homeTeam_teamTricode',
        'homeTeam_wins',
        'homeTeam_losses',
        'homeTeam_score',
        'awayTeam_teamId',
        'awayTeam_teamTricode',
        'awayTeam_wins',
        'awayTeam_losses',
        'awayTeam_score'
    ]

    # Columns to keep from Misc
    misc_keep = [
        'Player',
        'TEAM',
        'AGE',
        'PTS\nOFF TO',
        '2nd\nPTS',
        'FBPs',
        'PITP',
        'Opp PTS\nOFF TO',
        'Opp\n2nd PTS',
        'Opp\nFBPs',
        'Opp\nPITP',
        'BLK',
        'BLKA'
    ]


    # Loop through every season
    for season, endpoints in data.items():

        print(f"\nCleaning {season}...")

        # LeagueDashPlayerStats
        if "LeagueDashPlayerStats" in endpoints:
            endpoints["LeagueDashPlayerStats"].drop(
                columns=player_stats_drop,
                errors="ignore",
                inplace=True
            )
        
        # LeagueDashPtDefend
        if "LeagueDashPtDefend" in endpoints:
            endpoints["LeagueDashPtDefend"].drop(
                columns=pt_defend_drop,
                errors="ignore",
                inplace=True
            )

            endpoints["LeagueDashPtDefend"].rename(
                columns=pt_defend_rename,
                inplace=True
            )
        
        # LeagueDashPlayerShotLocations
        if "LeagueDashPlayerShotLocations" in endpoints:
            endpoints["LeagueDashPlayerShotLocations"].rename(
                columns=shot_locations_rename,
                inplace=True
            )

            # Shot-location NaNs represent no recorded shots in that category
            endpoints["LeagueDashPlayerShotLocations"].fillna(0, inplace=True)
        
        # LeagueDashPlayerPtShot
        if "LeagueDashPlayerPtShot" in endpoints:
            endpoints["LeagueDashPlayerPtShot"].drop(
                columns=pt_shot_drop,
                errors="ignore",
                inplace=True
            )

        # ScheduleLeagueV2
        if "ScheduleLeagueV2" in endpoints:
            df = endpoints["ScheduleLeagueV2"]

            endpoints["ScheduleLeagueV2"] = df[
                [
                    col
                    for col in schedule_keep
                    if col in df.columns
                ]
            ]

        # Misc
        if "Misc" in endpoints:
            df = endpoints["Misc"]

            # Keep only desired columns
            endpoints["Misc"] = df[
                [
                    col
                    for col in misc_keep
                    if col in df.columns
                ]
            ]

            # Fill missing stat values with 0
            misc_stat_columns = [
                col for col in misc_keep
                if col not in ["Player", "TEAM"]
                and col in endpoints["Misc"].columns
            ]

            endpoints["Misc"][misc_stat_columns] = (
                endpoints["Misc"][misc_stat_columns].fillna(0)
            )

        print(f"Finished {season}")

    return data

Note that the data is cleaned within the notebook and is not updated in the original files. Therefore, the folders in the directory still contain the original, uncleaned data.

In [10]:
data = clean_nba_data(data)

Cleaning 26_27...
Finished 26_27

Cleaning 24_25...
Finished 24_25

Cleaning 22_23...
Finished 22_23

Cleaning 21_22...
Finished 21_22

Cleaning 23_24...
Finished 23_24

Cleaning 25_26...
Finished 25_26

/var/folders/0b/n3f548tn3156qpndhm9hlkhh0000gn/T/ipykernel_9238/2089117680.py:172: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  endpoints["Misc"][misc_stat_columns] = (
/var/folders/0b/n3f548tn3156qpndhm9hlkhh0000gn/T/ipykernel_9238/2089117680.py:172: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  endpoints["Misc"][misc_stat_columns] = (
/var/folders/0b/n3f548tn3156qpndhm9hlkhh0000gn/T/ipykernel_9238/2089117680.py:172: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  endpoints["Misc"][misc_stat_columns] = (
/var/folders/0b/n3f548tn3156qpndhm9hlkhh0000gn/T/ipykernel_9238/2089117680.py:172: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  endpoints["Misc"][misc_stat_columns] = (
/var/folders/0b/n3f548tn3156qpndhm9hlkhh0000gn/T/ipykernel_9238/2089117680.py:172: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  endpoints["Misc"][misc_stat_columns] = (
/var/folders/0b/n3f548tn3156qpndhm9hlkhh0000gn/T/ipykernel_9238/2089117680.py:172: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  endpoints["Misc"][misc_stat_columns] = (

# Step 4: Merging Dataframes Together

In [11]:
# Helper function that merges Stats, Shot Locations, Defense,
# Player Shot data, and Misc data for every season.
# Expected structure: data[season][endpoint] = DataFrame
# Returns: merged_data[season] = merged DataFrame
def merge_nba_data(data):

    merged_data = {}

    shot_columns = [
        "Restricted Area", "Restricted Area.1", "Restricted Area.2",
        "In The Paint (Non-RA)", "In The Paint (Non-RA).1", "In The Paint (Non-RA).2",
        "Mid-Range", "Mid-Range.1", "Mid-Range.2",
        "Left Corner 3", "Left Corner 3.1", "Left Corner 3.2",
        "Right Corner 3", "Right Corner 3.1", "Right Corner 3.2",
        "Above the Break 3", "Above the Break 3.1", "Above the Break 3.2",
        "Backcourt", "Backcourt.1", "Backcourt.2",
        "Corner 3", "Corner 3.1", "Corner 3.2"
    ]

    # Normalize player names ONLY for matching across datasets
    def normalize_player_name(name):

        if pd.isna(name):
            return name

        name = str(name).strip()

        # Normalize Jr. -> Jr
        name = name.replace(" Jr.", " Jr")

        # Known cross-source naming difference
        name_overrides = {
            "Bobby Portis Jr": "Bobby Portis",
            "Brandon Boston Jr": "Brandon Boston",
            "Jonas Valanciunas": "Jonas Valančiūnas",
            "Lester Quiñones": "Lester Quinones",
            "Vlatko Cancar": "Vlatko Čančar",
        }

        return name_overrides.get(name, name)

    for season, endpoints in data.items():

        print(f"\nMerging {season}...")

        # Get current-season DataFrames
        stats = endpoints.get("LeagueDashPlayerStats")
        shots = endpoints.get("LeagueDashPlayerShotLocations")
        defense = endpoints.get("LeagueDashPtDefend")
        freq = endpoints.get("LeagueDashPlayerPtShot")
        misc = endpoints.get("Misc")

        # Check required DataFrames
        if stats is None:
            print(f"  Skipping {season}: missing Player Stats")
            continue

        if shots is None:
            print(f"  Skipping {season}: missing Shot Locations")
            continue

        if defense is None:
            print(f"  Skipping {season}: missing Defense")
            continue

        if freq is None:
            print(f"  Skipping {season}: missing Player Shot data")
            continue

        if misc is None:
            print(f"  Skipping {season}: missing Misc data")
            continue

        # Players whose data should ALWAYS come from 24_25
        name_overrides2 = {
            "Damian Lillard",
            "Tyrese Haliburton",
            "Kyrie Irving",
            "Jimmy Butler",
            "Ja Morant",
            "Trae Young",
            "Anthony Davis",
            "Fred VanVleet",
            "Domantas Sabonis",
            "Jaren Jackson Jr.",
            "Zach LaVine",
            "Zach Edey",
            "Walker Kessler"
        }

        # Make copies
        stats = stats.copy()
        shots = shots.copy()
        defense = defense.copy()
        freq = freq.copy()
        misc = misc.copy()

        # Use 24_25 data for these override players
        if season != "24_25":

            source_24 = data["24_25"]

            # Get 24_25 DataFrames
            stats_24 = source_24["LeagueDashPlayerStats"].copy()
            shots_24 = source_24["LeagueDashPlayerShotLocations"].copy()
            defense_24 = source_24["LeagueDashPtDefend"].copy()
            freq_24 = source_24["LeagueDashPlayerPtShot"].copy()
            misc_24 = source_24["Misc"].copy()

            # Make sure 24_25 IDs are numeric too
            stats_24["PLAYER_ID"] = pd.to_numeric(
                stats_24["PLAYER_ID"], errors="coerce"
            ).astype("Int64")

            shots_24["PLAYER_ID"] = pd.to_numeric(
                shots_24["PLAYER_ID"], errors="coerce"
            ).astype("Int64")

            defense_24["D_PLAYER_ID"] = pd.to_numeric(
                defense_24["D_PLAYER_ID"], errors="coerce"
            ).astype("Int64")

            freq_24["PLAYER_ID"] = pd.to_numeric(
                freq_24["PLAYER_ID"], errors="coerce"
            ).astype("Int64")

            # Find override players in 24_25 Stats
            override_stats = stats_24[
                stats_24["PLAYER_NAME"].isin(name_overrides2)
            ].copy()

            override_ids = set(
                override_stats["PLAYER_ID"].dropna()
            )

            if len(override_stats) > 0:
                
                # Stats
                # Remove current-season versions
                stats = stats[
                    ~stats["PLAYER_NAME"].isin(name_overrides2)
                ].copy()

                # Add 24_25 versions
                stats = pd.concat(
                    [stats, override_stats],
                    ignore_index=True
                )

                # Shot locations
                override_shots = shots_24[
                    shots_24["PLAYER_ID"].isin(override_ids)
                ].copy()

                # Remove current-season versions
                shots = shots[
                    ~shots["PLAYER_ID"].isin(override_ids)
                ].copy()

                # Add 24_25 versions
                shots = pd.concat(
                    [shots, override_shots],
                    ignore_index=True
                )

                # Defense
                override_defense = defense_24[
                    defense_24["D_PLAYER_ID"].isin(override_ids)
                ].copy()

                defense = defense[
                    ~defense["D_PLAYER_ID"].isin(override_ids)
                ].copy()

                defense = pd.concat(
                    [defense, override_defense],
                    ignore_index=True
                )

                # Player Shot/ Frequency
                override_freq = freq_24[
                    freq_24["PLAYER_ID"].isin(override_ids)
                ].copy()

                freq = freq[
                    ~freq["PLAYER_ID"].isin(override_ids)
                ].copy()

                freq = pd.concat(
                    [freq, override_freq],
                    ignore_index=True
                )

                # Misc
                misc_24["_MISC_PLAYER_NAME"] = (
                    misc_24["Player"]
                    .apply(normalize_player_name)
                )

                override_names = {
                    normalize_player_name(name)
                    for name in name_overrides2
                }

                override_misc = misc_24[
                    misc_24["_MISC_PLAYER_NAME"].isin(override_names)
                ].copy()

                misc["_MISC_PLAYER_NAME"] = (
                    misc["Player"]
                    .apply(normalize_player_name)
                )

                misc = misc[
                    ~misc["_MISC_PLAYER_NAME"].isin(override_names)
                ].copy()

                misc = pd.concat(
                    [misc, override_misc],
                    ignore_index=True
                )
        # Make player id constant

        stats["PLAYER_ID"] = pd.to_numeric(
            stats["PLAYER_ID"],
            errors="coerce"
        ).astype("Int64")

        shots["PLAYER_ID"] = pd.to_numeric(
            shots["PLAYER_ID"],
            errors="coerce"
        ).astype("Int64")

        defense["D_PLAYER_ID"] = pd.to_numeric(
            defense["D_PLAYER_ID"],
            errors="coerce"
        ).astype("Int64")

        freq["PLAYER_ID"] = pd.to_numeric(
            freq["PLAYER_ID"],
            errors="coerce"
        ).astype("Int64")

        # Clean player names
        stats["PLAYER_NAME"] = (
            stats["PLAYER_NAME"]
            .astype(str)
            .str.strip()
        )

        misc["Player"] = (
            misc["Player"]
            .astype(str)
            .str.strip()
        )

        # Stats + Shot Locations
        merged = stats.merge(
            shots,
            on="PLAYER_ID",
            how="left",
            suffixes=("", "_SHOT")
        )

        existing_shot_columns = [
            col for col in shot_columns
            if col in merged.columns
        ]

        merged[existing_shot_columns] = (
            merged[existing_shot_columns].fillna(0)
        )

        # Merge Defense
        merged = merged.merge(
            defense,
            left_on="PLAYER_ID",
            right_on="D_PLAYER_ID",
            how="left"
        )

        # Merge Player Shot/Frequency Data
        merged = merged.merge(
            freq,
            on="PLAYER_ID",
            how="left",
            suffixes=("", "_CLUTCH")
        )

        # Normalize names for Misc merge
        merged["_MISC_PLAYER_NAME"] = (
            merged["PLAYER_NAME"]
            .apply(normalize_player_name)
        )

        misc["_MISC_PLAYER_NAME"] = (
            misc["Player"]
            .apply(normalize_player_name)
        )

        # Merge Misc
        merged = merged.merge(
            misc,
            on="_MISC_PLAYER_NAME",
            how="left",
            suffixes=("", "_MISC")
        )

        merged.drop(
            columns="_MISC_PLAYER_NAME",
            inplace=True
        )

        # Store merged DataFrame
        merged_data[season] = merged

        print(f"  Merged shape: {merged.shape}")

    return merged_data

In [12]:
merged_data = merge_nba_data(data)

Merging 26_27...
  Merged shape: (697, 100)

Merging 24_25...
  Merged shape: (569, 99)

Merging 22_23...
  Merged shape: (552, 99)

Merging 21_22...
  Merged shape: (617, 99)

Merging 23_24...
  Merged shape: (584, 99)

Merging 25_26...
  Merged shape: (594, 100)

# Step 5: Check Missing Data

In [13]:
# Helper function that inspects rows containing NaN values across all merged seasons
# Expected structure: merged_data[season] = DataFrame
# Returns: None
def inspect_missing_rows(merged_data):

    for season, df in merged_data.items():

        # Find columns containing NaN
        missing_counts = df.isna().sum()
        missing_columns = missing_counts[missing_counts > 0]

        if missing_columns.empty:
            print("\nNo missing values.")
            continue

        # Print rows containing missing values
        rows_with_nan = df[df.isna().any(axis=1)]

        print(f"Rows with missing values: {len(rows_with_nan):,}")

        print(rows_with_nan.to_string(index=False))

In [14]:
inspect_missing_rows(merged_data)

Rows with missing values: 128
 PLAYER_ID        PLAYER_NAME NICKNAME    TEAM_ID TEAM_ABBREVIATION  AGE  GP  W  L  W_PCT         MIN  FGM  FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  OREB  DREB  REB  AST  TOV  STL  BLK  BLKA  PF  PFD  PTS  PLUS_MINUS  NBA_FANTASY_PTS  DD2  TD3  FP_HIGH_SCORE  PLAYER_NAME_SHOT TEAM_ID_SHOT TEAM_ABBREVIATION_SHOT AGE_SHOT NICKNAME_SHOT Restricted Area Restricted Area.1 Restricted Area.2 In The Paint (Non-RA) In The Paint (Non-RA).1 In The Paint (Non-RA).2 Mid-Range Mid-Range.1 Mid-Range.2 Left Corner 3 Left Corner 3.1 Left Corner 3.2 Right Corner 3 Right Corner 3.1 Right Corner 3.2 Above the Break 3 Above the Break 3.1 Above the Break 3.2 Backcourt Backcourt.1 Backcourt.2 Corner 3 Corner 3.1 Corner 3.2  D_PLAYER_ID     D_PLAYER_NAME  D_PLAYER_LAST_TEAM_ID D_PLAYER_LAST_TEAM_ABBREVIATION D_PLAYER_POSITION  D_FREQ  D_FGM  D_FGA  D_FG_PCT  D_NORMAL_FG_PCT  D_PCT_PLUSMINUS PLAYER_NAME_CLUTCH  PLAYER_LAST_TEAM_ID PLAYER_LAST_TEAM_ABBREVIATION    G  FGA_FREQUENCY  EFG_PCT  FG2A_FREQUENCY  FG2M  FG2A  FG2_PCT  FG3A_FREQUENCY            Player TEAM  AGE_MISC  PTS\nOFF TO  2nd\nPTS  FBPs  PITP  Opp PTS\nOFF TO  Opp\n2nd PTS  Opp\nFBPs  Opp\nPITP  BLK_MISC  BLKA_MISC
   1631205      Buddy Boeheim    Buddy          0                FA 26.0   4  2  2  0.500   15.003333    2    6   0.333     2     6    0.333    0    0   0.000     0     0    0    0    0    0    0     1   1    1    6           6              6.0    0    0            6.0     Buddy Boeheim   1610612760                    OKC     26.0         Buddy               0                 0               0.0                     0                       0                     0.0         0           0         0.0           1.0             3.0           0.333            1.0              1.0              1.0                 0                   2                 0.0         0           0           0        2          4        0.5      1631205     Buddy Boeheim           1610612760.0                             OKC                 F     1.0    3.0    9.0     0.333            0.426           -0.093      Buddy Boeheim         1610612760.0                           OKC  2.0            1.0    0.500           0.000   0.0   0.0      NaN           1.000     Buddy Boeheim  OKC      26.0          0.0       0.0   0.0   0.0              1.0           1.0        1.3        2.5       0.0        0.3
   1641732        Colby Jones    Colby          0                FA 24.0   1  0  1  0.000    6.816667    1    3   0.333     0     2    0.000    0    0   0.000     0     4    4    2    0    0    0     0   1    0    2          12              9.8    0    0           10.0       Colby Jones   1610612765                    DET     24.0         Colby               0                 0               0.0                     1                       1                     1.0         0           0         0.0             0               0               0            0.0              2.0              0.0                 0                   0                 0.0         0           0           0        0          2        0.0         <NA>               NaN                    NaN                             NaN               NaN     NaN    NaN    NaN       NaN              NaN              NaN        Colby Jones         1610612765.0                           DET  1.0            1.0    0.333           0.333   1.0   1.0    1.000           0.667       Colby Jones  DET      24.0          0.0       0.0   0.0   2.0              2.0           2.0        2.0        4.0       0.0        0.0
   1642468    Darius Brown II   Darius          0                FA 26.0   1  1  0  1.000    2.666667    0    1   0.000     0     0    0.000    0    0   0.000     0     1    1    0    0    0    0     0   0    0    0          -4              1.2    0    0            1.0   Darius Brown II   1610612739                    CLE     26.0        Darius               0                 0               0.0                     0                       0                     0.0         0           1         0.0             0               0               0            0.0              0.0              0.0                 0                   0                 0.0         0           0           0        0          0        0.0         <NA>               NaN                    NaN                             NaN               NaN     NaN    NaN    NaN       NaN              NaN              NaN    Darius Brown II         1610612739.0                           CLE  1.0            1.0    0.000           1.000   0.0   1.0    0.000           0.000   Darius Brown II  CLE      26.0          0.0       0.0   0.0   0.0              0.0           0.0        0.0        6.0       0.0        0.0
   1643141     Jahmyl Telfort   Jahmyl          0                FA 25.0   8  2  6  0.250   32.033333    0    4   0.000     0     4    0.000    1    4   0.250     0     3    3    1    1    1    0     0   5    2    1          -7              8.1    0    0            9.0    Jahmyl Telfort   1610612746                    LAC     25.0        Jahmyl               0                 0               0.0                     0                       0                     0.0         0           0         0.0           0.0             1.0             0.0            0.0              1.0              0.0                 0                   2                 0.0       0.0         0.0         0.0        0          2        0.0      1643141    Jahmyl Telfort           1610612746.0                             LAC                 G     1.0    2.0    6.0     0.333            0.461           -0.127     Jahmyl Telfort         1610612746.0                           LAC  4.0            1.0    0.000           0.000   0.0   0.0      NaN           1.000    Jahmyl Telfort  LAC      25.0          0.0       0.0   0.1   0.0              1.8           1.1        2.3        2.5       0.0        0.0
    200768         Kyle Lowry     Kyle 1610612755               PHI 40.0  14  9  5  0.643  118.040000    4   25   0.160     4    25    0.160    5    6   0.833     0     9    9   11    4    2    2     0   8    6   17         -39             52.3    0    0           60.0        Kyle Lowry   1610612755                    PHI     40.0          Kyle               0                 0               0.0                     0                       0                     0.0         0           0         0.0           1.0             2.0             0.5            0.0              2.0              0.0                 3                  21               0.143       0.0         0.0         0.0        1          4       0.25       200768        Kyle Lowry           1610612755.0                             PHI                 G     1.0   14.0   34.0     0.412            0.454           -0.043         Kyle Lowry         1610612755.0                           PHI 11.0            1.0    0.240           0.000   0.0   0.0      NaN           1.000        Kyle Lowry  PHI      40.0          0.0       0.1   0.2   0.0              3.1           3.9        2.5        8.1       0.1        0.0
         0     Labaron Philon      NaN          0               PHI  0.0   0  0  0  0.000    0.000000    0    0   0.000     0     0    0.000    0    0   0.000     0     0    0    0    0    0    0     0   0    0    0           0              0.0    0    0            0.0               NaN          NaN                    NaN      NaN           NaN               0                 0                 0                     0                       0                       0         0           0           0             0               0               0              0                0                0                 0                   0                   0         0           0           0        0          0          0         <NA>               NaN                    NaN                             NaN               NaN     NaN    NaN    NaN       NaN              NaN              NaN                NaN                  NaN                           NaN  NaN            NaN      NaN             NaN   NaN   NaN      NaN             NaN               NaN  NaN       NaN          NaN       NaN   NaN   NaN              NaN           NaN        NaN        NaN       NaN        NaN
         0        Caleb Grill      NaN          0               BOS  0.0   0  0  0  0.000    0.000000    0    0   0.000     0     0    0.000    0    0   0.000     0     0    0    0    0    0    0     0   0    0    0           0              0.0    0    0            0.0               NaN          NaN                    NaN      NaN           NaN               0                 0                 0                     0                       0                       0         0           0           0             0               0               0              0                0                0                 0                   0                   0         0           0           0        0          0          0         <NA>               NaN                    NaN                             NaN               NaN     NaN    NaN    NaN       NaN              NaN              NaN                NaN                  NaN                           NaN  NaN            NaN      NaN             NaN   NaN   NaN      NaN             NaN               NaN  NaN       NaN          NaN       NaN   NaN   NaN              NaN           NaN        NaN        NaN       NaN        NaN
         0     Ugonna Onyenso      NaN          0               DET  0.0   0  0  0  0.000    0.000000    0    0   0.000     0     0    0.000    0    0   0.000     0     0    0    0    0    0    0     0   0    0    0           0              0.0    0    0            0.0               NaN          NaN                    NaN      NaN           NaN               0                 0                 0                     0                       0                       0         0           0           0             0               0               0              0                0                0                 0                   0                   0         0           0           0        0          0          0         <NA>               NaN                    NaN                             NaN               NaN     NaN    NaN    NaN       NaN              NaN              NaN                NaN                  NaN                           NaN  NaN            NaN      NaN             NaN   NaN   NaN      NaN             NaN               NaN  NaN       NaN          NaN       NaN   NaN   NaN              NaN           NaN        NaN        NaN       NaN        NaN
   1627732        Ben Simmons      Ben 1610612758               SAC 28.0  51 26 25  0.510 1119.693333  116  223   0.520     0     0    0.000   24   33   0.727    47   194  241  285  102   38   23    10 107   58  256         -56           1053.7    1    0            NaN               NaN          NaN                    NaN      NaN           NaN               0                 0                 0                     0                       0                       0         0           0           0             0               0               0              0                0                0                 0                   0                   0         0           0           0        0          0          0         <NA>               NaN                    NaN                             NaN               NaN     NaN    NaN    NaN       NaN              NaN              NaN                NaN                  NaN                           NaN  NaN            NaN      NaN             NaN   NaN   NaN      NaN             NaN               NaN  NaN       NaN          NaN       NaN   NaN   NaN              NaN           NaN        NaN        NaN       NaN        NaN
         0        Lajae Jones      NaN          0               GSW  0.0   0  0  0  0.000    0.000000    0    0   0.000     0     0    0.000    0    0   0.000     0     0    0    0    0    0    0     0   0    0    0           0              0.0    0    0            0.0               NaN          NaN                    NaN      NaN           NaN               0                 0                 0                     0                       0                       0         0           0           0             0               0               0              0                0                0                 0                   0                   0         0           0           0        0          0          0         <NA>               NaN                    NaN                             NaN               NaN     NaN    NaN    NaN       NaN              NaN              NaN                NaN                  NaN                           NaN  NaN            NaN      NaN             NaN   NaN   NaN      NaN             NaN               NaN  NaN       NaN          NaN       NaN   NaN   NaN              NaN           NaN        NaN        NaN       NaN        NaN
         0    Brayden Burries      NaN          0               MIL  0.0   0  0  0  0.000    0.000000    0    0   0.000     0     0    0.000    0    0   0.000     0     0    0    0    0    0    0     0   0    0    0           0              0.0    0    0            0.0               NaN          NaN                    NaN      NaN           NaN               0                 0                 0                     0                       0                       0         0           0           0             0               0               0              0                0                0                 0                   0                   0         0           0           0        0          0          0         <NA>               NaN                    NaN                             NaN               NaN     NaN    NaN    NaN       NaN              NaN              NaN                NaN                  NaN                           NaN  NaN            NaN      NaN             NaN   NaN   NaN      NaN             NaN               NaN  NaN       NaN          NaN       NaN   NaN   NaN              NaN           NaN        NaN        NaN       NaN        NaN
         0    Chris Cenac Jr.      NaN          0               BOS  0.0   0  0  0  0.000    0.000000    0    0   0.000     0     0    0.000    0    0   0.000     0     0    0    0    0    0    0     0   0    0    0           0              0.0    0    0            0.0               NaN          NaN                    NaN      NaN           NaN               0                 0                 0                     0                       0                       0         0           0           0             0               0               0              0                0                0                 0                   0                   0         0           0           0        0          0          0         <NA>               NaN                    NaN                             NaN               NaN     NaN    NaN    NaN       NaN              NaN              NaN                NaN                  NaN                           NaN  NaN            NaN      NaN             NaN   NaN   NaN      NaN             NaN               NaN  NaN       NaN          NaN       NaN   NaN   NaN              NaN           NaN        NaN        NaN       NaN        NaN
         0       Alpha Diallo      NaN          0               DEN  0.0   0  0  0  0.000    0.000000    0    0   0.000     0     0    0.000    0    0   0.000     0     0    0    0    0    0    0     0   0    0    0           0              0.0    0    0            0.0               NaN          NaN                    NaN      NaN           NaN               0                 0                 0                     0                       0                       0         0           0           0             0               0               0              0                0                0                 0                   0                   0         0           0           0        0          0          0         <NA>               NaN                    NaN                             NaN               NaN     NaN    NaN    NaN       NaN              NaN              NaN                NaN                  NaN                           NaN  NaN            NaN      NaN             NaN   NaN   NaN      NaN             NaN               NaN  NaN       NaN          NaN       NaN   NaN   NaN              NaN           NaN        NaN        NaN       NaN        NaN
         0  Trey Kaufman-Renn      NaN          0               MIN  0.0   0  0  0  0.000    0.000000    0    0   0.000     0     0    0.000    0    0   0.000     0     0    0    0    0    0    0     0   0    0    0           0              0.0    0    0            0.0               NaN          NaN                    NaN      NaN           NaN               0                 0                 0                     0                       0                       0         0           0           0             0               0               0              0                0                0                 0                   0                   0         0           0           0        0          0          0         <NA>               NaN                    NaN                             NaN               NaN     NaN    NaN    NaN       NaN              NaN              NaN                NaN                  NaN                           NaN  NaN            NaN      NaN             NaN   NaN   NaN      NaN             NaN               NaN  NaN       NaN          NaN       NaN   NaN   NaN              NaN           NaN        NaN        NaN       NaN        NaN
         0       Ebuka Okorie      NaN          0               DET  0.0   0  0  0  0.000    0.000000    0    0   0.000     0     0    0.000    0    0   0.000     0     0    0    0    0    0    0     0   0    0    0           0              0.0    0    0            0.0               NaN          NaN                    NaN      NaN           NaN               0                 0                 0                     0                       0                       0         0           0           0             0               0               0              0                0                0                 0                   0                   0         0           0           0        0          0          0         <NA>               NaN                    NaN                             NaN               NaN     NaN    NaN    NaN       NaN              NaN              NaN                NaN                  NaN                           NaN  NaN            NaN      NaN             NaN   NaN   NaN      NaN             NaN               NaN  NaN       NaN          NaN       NaN   NaN   NaN              NaN           NaN        NaN        NaN       NaN        NaN

# Step 6: Create Dataframe with Winning features

In [15]:
col_Altogether = [

    # Player stats
    'PLAYER_ID',
    'PLAYER_NAME',
    'TEAM_ID',
    'TEAM_ABBREVIATION',

    'AGE',
    'GP',
    'W',
    'L',
    'W_PCT',
    'MIN',

    'FGM',
    'FGA',
    'FG_PCT',

    'FG3M',
    'FG3A',
    'FG3_PCT',

    'FTM',
    'FTA',
    'FT_PCT',

    'OREB',
    'DREB',
    'REB',
    'AST',
    'TOV',
    'STL',
    'BLK',
    'BLKA',
    'PF',
    'PFD',

    'PTS',
    'PLUS_MINUS',
    'NBA_FANTASY_PTS',
    'DD2',
    'TD3',

    # Shot locations
    # Base   = FGM
    # .1     = FGA
    # .2     = FG%
    'Restricted Area',
    'Restricted Area.1',
    'Restricted Area.2',

    'In The Paint (Non-RA)',
    'In The Paint (Non-RA).1',
    'In The Paint (Non-RA).2',

    'Mid-Range',
    'Mid-Range.1',
    'Mid-Range.2',

    'Left Corner 3',
    'Left Corner 3.1',
    'Left Corner 3.2',

    'Right Corner 3',
    'Right Corner 3.1',
    'Right Corner 3.2',

    'Above the Break 3',
    'Above the Break 3.1',
    'Above the Break 3.2',

    'Backcourt',
    'Backcourt.1',
    'Backcourt.2',

    # Aggregate of Left Corner 3 + Right Corner 3
    'Corner 3',
    'Corner 3.1',
    'Corner 3.2',

    # Defense
    'D_PLAYER_POSITION',
    'D_FREQ',
    'D_FGM',
    'D_FGA',
    'D_FG_PCT',
    'D_NORMAL_FG_PCT',
    'D_PCT_PLUSMINUS',

    # Player shot
    'FGA_FREQUENCY',
    'EFG_PCT',
    'FG2A_FREQUENCY',
    'FG2M',
    'FG2A',
    'FG2_PCT',
    'FG3A_FREQUENCY',

    # Misc
    'PTSOFFTO',
    '2ndPTS',
    'FBPs',
    'PITP',

    'Opp PTSOFF TO',
    'Opp2nd PTS',
    'OppFBPs',
    'OppPITP'
]

In [16]:
# Helper function that creates the final player-level dataset for every season.
# Expected structure: merged_data[season] = DataFrame
# Returns: player_data[season] = transformed DataFrame
def create_player_dataset(merged_data):

    player_data = {}

    for season, df in merged_data.items():

        print(f"\nCreating player dataset for {season}...")

        # Rename miscellaneous source columns
        df = df.rename(columns={
            'PTS\nOFF TO': 'PTSOFFTO',
            '2nd\nPTS': '2ndPTS',
            'Opp PTS\nOFF TO': 'Opp PTSOFF TO',
            'Opp\n2nd PTS': 'Opp2nd PTS',
            'Opp\nFBPs': 'OppFBPs',
            'Opp\nPITP': 'OppPITP'
        })

        # Start with the columns from col_Altogether
        output = df[
            [
                col
                for col in col_Altogether
                if col in df.columns
            ]
        ].copy()

        # Rename columns 
        output = output.rename(columns={
            'PLAYER_ID': 'PlayerID',
            'PLAYER_NAME': 'PlayerName',
            'TEAM_ID': 'TeamID',
            'TEAM_ABBREVIATION': 'TeamAbbv',

            'AGE': 'Age',
            'W_PCT': 'W_Pct',
            'MIN': 'Min',

            'FG3M': '3PM',
            'OREB': 'OReb',
            'DREB': 'DReb',
            'AST': 'Ast',
            'TOV': 'TO',
            'PTS': 'Pts',

            'D_PLAYER_POSITION': 'Pos'
        })

        # Remaining games
        output['RemainingGames'] = output['GP']

        # Paint points
        paint_fgm = (
            output['Restricted Area']
            .fillna(0)
            .astype(float)
            +
            output['In The Paint (Non-RA)']
            .fillna(0)
            .astype(float)
        )

        output['Pts_Paint'] = paint_fgm * 2

        # Mid-range points
        midrange_fgm = (
            output['Mid-Range']
            .fillna(0)
            .astype(float)
        )

        output['Pts_MidRange'] = midrange_fgm * 2

        # 3-point points
        three_fgm = (
            output['Left Corner 3']
            .fillna(0)
            .astype(float)
            +
            output['Right Corner 3']
            .fillna(0)
            .astype(float)
            +
            output['Above the Break 3']
            .fillna(0)
            .astype(float)
            +
            output['Backcourt']
            .fillna(0)
            .astype(float)
        )

        output['Pts_3PT'] = three_fgm * 3

        # Store transformed player-level dataset
        player_data[season] = output
    return player_data

In [17]:
player_data = create_player_dataset(merged_data)

Creating player dataset for 26_27...

Creating player dataset for 24_25...

Creating player dataset for 22_23...

Creating player dataset for 21_22...

Creating player dataset for 23_24...

Creating player dataset for 25_26...

# Step 7: Create Dataframe with Player Per Game Averages

In [18]:
# Features in the dataframe that I want to shift to PerGame and PerSeason
per_game_cols = [
    'Min', 'FGM', 'FGA', '3PM', 'FG3A',
    'FTM', 'FTA',
    'OReb', 'DReb', 'REB',
    'Ast', 'TO', 'STL', 'BLK', 'BLKA',
    'PF', 'PFD', 'Pts',
    'NBA_FANTASY_PTS', 'DD2', 'TD3',
    'Pts_Paint', 'Pts_MidRange', 'Pts_3PT', 'PLUS_MINUS'
]

feature_cols = [
    'PlayerID', 'PlayerName', 'TeamID', 'TeamAbbv', 'Age', 'GP',
    'W', 'L', 'W_Pct',
    'FG_PCT', 'FG3_PCT', 'FT_PCT',
    'Restricted Area', 'Restricted Area.1', 'Restricted Area.2',
    'In The Paint (Non-RA)', 'In The Paint (Non-RA).1', 'In The Paint (Non-RA).2',
    'Mid-Range', 'Mid-Range.1', 'Mid-Range.2',
    'Left Corner 3', 'Left Corner 3.1', 'Left Corner 3.2',
    'Right Corner 3', 'Right Corner 3.1', 'Right Corner 3.2',
    'Above the Break 3', 'Above the Break 3.1', 'Above the Break 3.2',
    'Backcourt', 'Backcourt.1', 'Backcourt.2',
    'Corner 3', 'Corner 3.1', 'Corner 3.2',
    'Pos',
    'D_FREQ', 'D_FGM', 'D_FGA', 'D_FG_PCT', 'D_NORMAL_FG_PCT',
    'D_PCT_PLUSMINUS',
    'FGA_FREQUENCY', 'EFG_PCT',
    'FG2A_FREQUENCY', 'FG2M', 'FG2A', 'FG2_PCT',
    'FG3A_FREQUENCY',
    'PTSOFFTO', '2ndPTS', 'FBPs', 'PITP',
    'Opp PTSOFF TO', 'Opp2nd PTS', 'OppFBPs', 'OppPITP',
    'RemainingGames'
]

In [19]:
# Helper function that creates a per-game version of each season's player dataset.
#     Counting stats are divided by GP.
#     All other feature columns are carried over unchanged.
# Expected structure: data[season] = DataFrame
# Returns: per_game_data[season] = DataFrame
def create_per_game_avg(data):
    per_game_data = {}

    for season, df in data.items():

        print(f"Creating per-game averages for {season}...")

        # Only keep columns that actually exist
        available_features = [
            col for col in feature_cols
            if col in df.columns
        ]

        available_per_game = [
            col for col in per_game_cols
            if col in df.columns
        ]

        # Start with non-per-game features
        output = df[available_features].copy()

        # Calculate per-game averages
        for col in available_per_game:

            output[col] = (
                pd.to_numeric(df[col], errors='coerce')
                / pd.to_numeric(df['GP'], errors='coerce')
            )

        per_game_data[season] = output

    return per_game_data

In [20]:
PerGameAvg = create_per_game_avg(player_data)

Creating per-game averages for 26_27...
Creating per-game averages for 24_25...
Creating per-game averages for 22_23...
Creating per-game averages for 21_22...
Creating per-game averages for 23_24...
Creating per-game averages for 25_26...

# Step 8: Fill in Rookies

In [21]:
# Copies so we don't accidentally modify the originals
pga_nba2k = PerGameAvg["26_27"].copy()
nba2k = data["26_27"]["NBA2k"].copy()

In [22]:
# Helper function that normalizes player names
def clean_player_name(name):
    if pd.isna(name):
        return ""

    name = str(name)

    # Remove accents
    name = unicodedata.normalize("NFKD", name)
    name = "".join(c for c in name if not unicodedata.combining(c))

    # Lowercase
    name = name.lower()

    # Replace common punctuation with spaces
    name = re.sub(r"[.'’`]", "", name)
    name = re.sub(r"[-]", " ", name)

    # Remove suffixes
    name = re.sub(r"\b(jr|sr|ii|iii|iv|v)\b", "", name)

    # Remove anything that isn't a letter/number/space
    name = re.sub(r"[^a-z0-9 ]", "", name)

    # Collapse whitespace
    name = re.sub(r"\s+", " ", name).strip()

    return name

In [23]:
# Use nba 2k stats to fill rookies data
pga_nba2k["PlayerName_clean"] = pga_nba2k["PlayerName"].apply(clean_player_name)
nba2k["name_clean"] = nba2k["name"].apply(clean_player_name)

pga_nba2k = pga_nba2k.merge(
    nba2k,
    left_on="PlayerName_clean",
    right_on="name_clean",
    how="left"
)

pga_nba2k.drop(
    columns=["PlayerName_clean", "name_clean"],
    inplace=True
)

# Remove players without an NBA 2K match
pga_nba2k = pga_nba2k[
    pga_nba2k["overall"].notna()
].copy()

pga_nba2k = pga_nba2k.drop(columns=[
    'PlayerID', 'PlayerName', 'TeamID', 'TeamAbbv',
    'Age', 'W', 'L', 'W_Pct', 'name', 'slug', 'team', 'era'
])

In [24]:
# Helper function that converts feet to inches. Used for dataframe merging and conversions
def height_to_inches(h):
    if pd.isna(h):
        return np.nan

    h = str(h).strip()

    # Handles formats like 6'11" or 6'11
    match = re.match(r"^(\d+)'(\d+)", h)

    if match:
        feet = int(match.group(1))
        inches = int(match.group(2))
        return feet * 12 + inches

    return np.nan

pga_nba2k['height'] = pga_nba2k['height'].apply(height_to_inches)

In [25]:
# Helper function that assigns primary and secondary positions to numerical values
position_map = {
    'PG': 1,
    'SG': 2,
    'SF': 3,
    'PF': 4,
    'C': 5
}

def split_positions(pos):
    if pd.isna(pos):
        return np.nan, np.nan
    
    pos = str(pos).upper().strip()
    
    # Handle separators such as "-", "/", ",", etc.
    parts = re.split(r'[-/, ]+', pos)
    parts = [p for p in parts if p in position_map]
    
    if len(parts) == 0:
        return np.nan, np.nan
    
    primary = position_map[parts[0]]
    secondary = position_map[parts[1]] if len(parts) > 1 else np.nan
    
    return primary, secondary


pga_nba2k[['primarypos', 'secondarypos']] = (
    pga_nba2k['positions']
    .apply(lambda x: pd.Series(split_positions(x)))
)

In [26]:
# Input features and target features
input_features = [
    'primarypos',
    'secondarypos',
    'height',
    'overall',
    'close_shot',
    'mid_range_shot',
    'three_ball',
    'free_throw',
    'shot_iq',
    'offensive_consistency',
    'driving_layup',
    'standing_dunk',
    'dunk',
    'post_hook',
    'post_fade',
    'post_control',
    'draw_foul',
    'hands',
    'pass_accuracy',
    'ball_handle',
    'speed_with_ball',
    'pass_iq',
    'pass_vision',
    'speed',
    'agility',
    'vertical',
    'strength',
    'stamina',
    'hustle',
    'durability',
    'interior_defense',
    'defense',
    'steal',
    'block',
    'help_defense_iq',
    'pass_perception',
    'defensive_consistency',
    'offensive_rebound',
    'defensive_rebound'
]

target_features = [
    'GP',
    'FG_PCT',
    'FG3_PCT',
    'FT_PCT',
    'Restricted Area',
    'Restricted Area.1',
    'Restricted Area.2',
    'In The Paint (Non-RA)',
    'In The Paint (Non-RA).1',
    'In The Paint (Non-RA).2',
    'Mid-Range',
    'Mid-Range.1',
    'Mid-Range.2',
    'Left Corner 3',
    'Left Corner 3.1',
    'Left Corner 3.2',
    'Right Corner 3',
    'Right Corner 3.1',
    'Right Corner 3.2',
    'Above the Break 3',
    'Above the Break 3.1',
    'Above the Break 3.2',
    'Backcourt',
    'Backcourt.1',
    'Backcourt.2',
    'Corner 3',
    'Corner 3.1',
    'Corner 3.2',
    'D_FREQ',
    'D_FGM',
    'D_FGA',
    'D_FG_PCT',
    'D_NORMAL_FG_PCT',
    'D_PCT_PLUSMINUS',
    'FGA_FREQUENCY',
    'EFG_PCT',
    'FG2A_FREQUENCY',
    'FG2M',
    'FG2A',
    'FG2_PCT',
    'FG3A_FREQUENCY',
    'PTSOFFTO',
    '2ndPTS',
    'FBPs',
    'PITP',
    'Opp PTSOFF TO',
    'Opp2nd PTS',
    'OppFBPs',
    'OppPITP',
    'RemainingGames',
    'Min',
    'FGM',
    'FGA',
    '3PM',
    'FG3A',
    'FTM',
    'FTA',
    'OReb',
    'DReb',
    'REB',
    'Ast',
    'TO',
    'STL',
    'BLK',
    'BLKA',
    'PF',
    'PFD',
    'Pts',
    'NBA_FANTASY_PTS',
    'DD2',
    'TD3',
    'Pts_Paint',
    'Pts_MidRange',
    'Pts_3PT',
    'PLUS_MINUS'
]

In [27]:
# Creating model
model_df = pga_nba2k[
    input_features + target_features
].copy()

# Drop players with missing data features
before = len(model_df)

model_df = model_df.dropna(
    subset=input_features
).copy()

after = len(model_df)

# X = All input features
X_all = model_df[input_features].copy()

# Create one fixed train test split
# Every target uses the EXACT SAME players in train/test.
# This lets us evaluate the whole system consistently.
train_idx, test_idx = train_test_split(
    model_df.index,
    test_size=0.20,
    random_state=42
)

X_train_all = X_all.loc[train_idx]
X_test_all  = X_all.loc[test_idx]

# Train one model for eachtarget features
models = {}
predictions = []
results = []


for target in target_features:

    # Target values
    y = model_df[target]

    # Only use players who actually have this target
    train_mask = y.loc[train_idx].notna()
    test_mask = y.loc[test_idx].notna()

    X_train = X_train_all.loc[train_mask]
    y_train = y.loc[train_idx][train_mask]

    X_test = X_test_all.loc[test_mask]
    y_test = y.loc[test_idx][test_mask]

    # Need enough training data
    if len(X_train) < 20:
        print(f"Skipping {target}: only {len(X_train)} training samples")
        continue

    # XGBoost
    model = XGBRegressor(
        n_estimators=300,
        max_depth=4,
        learning_rate=0.03,
        subsample=0.8,
        colsample_bytree=0.8,
        objective='reg:squarederror',
        random_state=42,
        n_jobs=-1
    )

    # ALL input features go into the model
    model.fit(
        X_train,
        y_train
    )

    # Predict
    y_pred = model.predict(X_test)

    # Metrics
    mae = mean_absolute_error(
        y_test,
        y_pred
    )

    rmse = np.sqrt(
        mean_squared_error(
            y_test,
            y_pred
        )
    )

    r2 = r2_score(
        y_test,
        y_pred
    )

    # Store model
    models[target] = model

    # Store predictions
    pred_df = pd.DataFrame({
        "PlayerIndex": y_test.index,
        "Target": target,
        "Actual": y_test.values,
        "Predicted": y_pred
    })

    predictions.append(pred_df)

    # Store metrics
    results.append({
        "Target": target,
        "Samples": len(y_test),
        "MAE": mae,
        "RMSE": rmse,
        "R2": r2
    })

# Combine Predictions
predictions_df = pd.concat(
    predictions,
    ignore_index=True
)

# Results
results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    "R2",
    ascending=False
).reset_index(drop=True)

print("Model Performance")

print(
    results_df.to_string(index=False)
)

Model Performance
                 Target  Samples       MAE       RMSE        R2
                 D_FREQ       89  0.000000   0.000000  1.000000
          FGA_FREQUENCY       90  0.000000   0.000000  1.000000
                   FG2M       90 30.358836  43.719722  0.877060
                   FG2A       90 58.112618  78.550693  0.873526
                    Pts       92  2.037247   2.740912  0.835631
                    FGM       92  0.710657   0.965202  0.834757
                    Ast       92  0.567180   0.771289  0.829629
        NBA_FANTASY_PTS       92  3.493985   4.729911  0.820516
                    FGA       92  1.393901   2.016612  0.816289
                   PITP       90  1.069111   1.508114  0.796021
    Above the Break 3.1      106 43.455551  62.424546  0.790264
      Above the Break 3      106 15.512074  23.706078  0.787250
                    FTA       92  0.639595   0.881320  0.785848
                  D_FGA       89 96.420051 125.748555  0.779095
                    FTM       92  0.534759   0.733296  0.773386
                    PFD       92  0.536331   0.704903  0.760018
         RemainingGames      106  9.978266  13.148755  0.756032
                     GP      106  9.978266  13.148755  0.756032
                    3PM       92  0.349286   0.462080  0.754097
      Restricted Area.1      106 34.170559  53.849338  0.744269
        Restricted Area      106 23.847696  38.229121  0.734812
                  D_FGM       89 48.530496  63.626375  0.734448
                   OReb       92  0.238411   0.344801  0.732764
              Mid-Range      106  6.877675  12.981816  0.716896
                    BLK       92  0.114821   0.181366  0.703097
            Mid-Range.1      106 15.897382  27.987894  0.701185
             Corner 3.1      106 16.321602  21.226731  0.700068
               Corner 3      106  6.853199   9.153465  0.697210
                    Min       92  3.885245   5.178461  0.692767
                     TO       92  0.337940   0.441482  0.690498
              Pts_Paint       92  1.340532   1.870403  0.688958
                Pts_3PT       92  1.175664   1.574280  0.685743
In The Paint (Non-RA).1      106 29.823526  48.991218  0.682765
                   FG3A       92  0.934309   1.328012  0.681639
               PTSOFFTO       90  0.460381   0.646268  0.678735
        Left Corner 3.1      106  9.028155  11.870184  0.661989
           Pts_MidRange       92  0.290346   0.453779  0.660401
                   DReb       92  0.548211   0.798514  0.660363
  In The Paint (Non-RA)      106 13.767517  24.621224  0.648007
       Right Corner 3.1      106  9.105159  11.465807  0.646388
                    REB       92  0.798175   1.084449  0.645590
         Right Corner 3      106  3.838094   5.097264  0.640522
          Left Corner 3      106  4.035279   5.454802  0.602592
                   FBPs       90  0.548216   0.823976  0.591388
                    STL       92  0.204015   0.301521  0.579053
                 FG_PCT      106  0.074638   0.111545  0.572998
         FG3A_FREQUENCY       90  0.108886   0.134155  0.566768
         FG2A_FREQUENCY       90  0.108666   0.134801  0.562561
                 2ndPTS       90  0.382211   0.503617  0.540863
          Opp PTSOFF TO       90  1.889419   2.363349  0.539285
                OppPITP       90  5.239460   7.170493  0.534954
                OppFBPs       90  1.697543   2.221380  0.491025
             Opp2nd PTS       90  1.531842   2.199040  0.490774
    Above the Break 3.2      106  0.080156   0.115415  0.445186
                    DD2       92  0.035672   0.063296  0.443224
                 FT_PCT      106  0.147238   0.222426  0.431808
                FG3_PCT      106  0.078360   0.117418  0.421906
In The Paint (Non-RA).2      106  0.108013   0.158569  0.413363
        D_NORMAL_FG_PCT       89  0.007135   0.009891  0.387634
       Right Corner 3.2      106  0.121579   0.156353  0.374186
                   BLKA       92  0.152160   0.214637  0.357502
                     PF       92  0.470042   0.602098  0.325201
      Restricted Area.2      106  0.154719   0.221979  0.297722
             Corner 3.2      106  0.113584   0.174214  0.278236
            Mid-Range.2      106  0.146211   0.198718  0.262656
                EFG_PCT       90  0.050445   0.078816  0.236413
        Left Corner 3.2      106  0.147215   0.216787  0.130005
             PLUS_MINUS       92  2.510440   3.761966  0.129373
        D_PCT_PLUSMINUS       89  0.041483   0.060755  0.120065
               D_FG_PCT       89  0.041607   0.062119  0.054600
                FG2_PCT       90  0.072853   0.116825 -0.239483
            Backcourt.2      106  0.060055   0.152993 -0.264426
              Backcourt      106  0.066603   0.167158 -0.509394
            Backcourt.1      106  0.274127   1.073307 -1.375432
                    TD3       92  0.007932   0.025123 -5.942067

In [28]:
# Pull Rookies
rookies = PerGameAvg["26_27"][
    PerGameAvg["26_27"]["PlayerID"] == 0
].copy()

# Pull rookie 2k data
rookies_nba2k = nba2k[
    nba2k["name"].isin(rookies["PlayerName"])
].copy()

# Save players name before dropping it
rookie_names = rookies_nba2k["name"].copy()

# Convert Height
rookies_nba2k["height"] = rookies_nba2k["height"].apply(
    height_to_inches
)

# Create numerical primary and secondary positions
rookies_nba2k[["primarypos", "secondarypos"]] = (
    rookies_nba2k["positions"]
    .apply(
        lambda x: pd.Series(
            split_positions(x)
        )
    )
)

# Convert 2k positions to pergame format
def convert_2k_position(pos):

    if pd.isna(pos):
        return np.nan

    pos = float(pos)

    if pos in [1.0, 2.0]:
        return "G"

    elif pos in [3.0, 4.0]:
        return "F"

    elif pos == 5.0:
        return "C"

    return np.nan


def combine_2k_positions(primary, secondary):

    primary_pos = convert_2k_position(primary)
    secondary_pos = convert_2k_position(secondary)

    # No positions
    if pd.isna(primary_pos) and pd.isna(secondary_pos):
        return np.nan

    # Only secondary exists
    if pd.isna(primary_pos):
        return secondary_pos

    # Only primary exists
    if pd.isna(secondary_pos):
        return primary_pos

    # If both map to the same position, only keep one
    if primary_pos == secondary_pos:
        return primary_pos

    # Both exist and are different
    return f"{primary_pos}-{secondary_pos}"

# Save positions before dropping name
rookie_primarypos = rookies_nba2k["primarypos"].copy()
rookie_secondarypos = rookies_nba2k["secondarypos"].copy()

# Drop unused columns 
columns_to_drop = [
    'team',
    'passing',
    'post_moves',
    'slug',
    'name',
    'era',
    'lateral_quickness',
    'positions',
    'name_clean',
    'acceleration'
]

rookies_nba2k = rookies_nba2k.drop(
    columns=columns_to_drop
)

# Check model inputs
missing_inputs = [
    col for col in input_features
    if col not in rookies_nba2k.columns
]

In [29]:
# Model Rookie input
rookie_X = rookies_nba2k[input_features].copy()

# Create transformed df
rookies_transformed = pd.DataFrame(
    index=rookies_nba2k.index
)

# Reattatch player name
rookies_transformed["PlayerName"] = rookie_names

# Reattatch original positions
rookies_transformed["primarypos"] = rookie_primarypos

rookies_transformed["secondarypos"] = rookie_secondarypos

# Create pergameavg positions
rookies_transformed["position"] = [
    combine_2k_positions(primary, secondary)
    for primary, secondary
    in zip(
        rookie_primarypos,
        rookie_secondarypos
    )
]

# Predict all target features
for target in target_features:

    model = models.get(target)

    if model is not None:

        rookies_transformed[target] = model.predict(
            rookie_X
        )

# Reset index
rookies_transformed = rookies_transformed.reset_index(
    drop=True
)

# Check
print("\nTRANSFORMED ROOKIES:")

print(
    rookies_transformed[
        [
            "PlayerName",
            "primarypos",
            "secondarypos",
            "position"
        ]
    ].to_string(index=False)
)

print("\nShape:")
print(rookies_transformed.shape)

TRANSFORMED ROOKIES:
        PlayerName  primarypos  secondarypos position
   Darryn Peterson         2.0           1.0        G
       AJ Dybantsa         3.0           4.0        F
    Cameron Boozer         4.0           5.0      F-C
      Caleb Wilson         4.0           5.0      F-C
     Keaton Wagler         2.0           1.0        G
  Darius Acuff Jr.         1.0           NaN        G
     Mario Hezonja         3.0           4.0        F
   Mikel Brown Jr.         1.0           2.0        G
 Kingston Flemings         1.0           2.0        G
   Yaxel Lendeborg         4.0           3.0        F
   Brayden Burries         2.0           3.0      G-F
         Aday Mara         5.0           NaN        C
       Karim Lopez         3.0           4.0        F
      Cameron Carr         2.0           3.0      G-F
        Nate Ament         3.0           4.0        F
     Thomas Sorber         5.0           4.0      C-F
      Zuby Ejiofor         5.0           4.0      C-F
   Chris Cenac Jr.         5.0           4.0      C-F
  Hannes Steinbach         5.0           4.0      C-F
      Dailyn Swain         3.0           2.0      F-G
   Tarik Biberovic         3.0           2.0      F-G
      Alpha Diallo         3.0           2.0      F-G
      Ebuka Okorie         1.0           2.0        G
          Koa Peat         4.0           3.0        F
      Alex Karaban         4.0           3.0        F
   Tarris Reed Jr.         5.0           NaN        C
      Allen Graves         4.0           5.0      F-C
     Henri Veesaar         5.0           4.0      C-F
  Joshua Jefferson         4.0           3.0        F
Christian Anderson         1.0           NaN        G
     Meleek Thomas         2.0           1.0        G
    Bruce Thornton         1.0           2.0        G
      Braden Smith         1.0           NaN        G
      Isaiah Evans         2.0           3.0      G-F
    Bennett Stirtz         1.0           2.0        G
 Jayden Quaintance         5.0           4.0      C-F
    Tyler Bilodeau         4.0           5.0      F-C
        Tobi Lawal         4.0           3.0        F
    Trevon Brazile         4.0           5.0      F-C
    Ugonna Onyenso         5.0           NaN        C
       Baba Miller         4.0           3.0        F
      Ryan Conwell         2.0           3.0      G-F
        Otega Oweh         2.0           3.0      G-F
    Izaiyah Nelson         5.0           4.0      C-F
       Maliq Brown         4.0           5.0      F-C
     Jaden Bradley         1.0           2.0        G
      Felix Okpara         5.0           NaN        C
       Tamar Bates         2.0           3.0      G-F
   Dillon Mitchell         4.0           3.0        F
     Kylan Boswell         1.0           NaN        G
     Michael Ajayi         4.0           NaN        F
        Tobe Awaka         4.0           NaN        F
    Jaylin Sellers         2.0           NaN        G
     Bryce Hopkins         4.0           3.0        F
   Quadir Copeland         1.0           NaN        G
   Nick Martinelli         3.0           4.0        F
     Arthur Kaluma         3.0           NaN        F
        AK Okereke         4.0           NaN        F
     Tre Donaldson         1.0           NaN        G
  Jaron Pierre Jr.         2.0           2.0        G
         Malik Dia         4.0           NaN        F
      Tyler Nickel         3.0           2.0      F-G
          Josh Dix         2.0           NaN        G
     Emanuel Sharp         2.0           1.0        G
     Rafael Castro         4.0           5.0      F-C
    Jamarion Sharp         5.0           NaN        C

Shape:
(66, 79)

In [30]:
# Fill rookies pergameavg for the 26_27 season
PerGameAvg["26_27"] = PerGameAvg["26_27"].copy()

rookie_lookup = rookies_transformed.set_index("PlayerName")

# Identify rookies
rookie_mask = PerGameAvg["26_27"]["PlayerName"].isin(
    rookie_lookup.index
)

# Fill model predicted target values
for target in target_features:

    if target in rookie_lookup.columns:

        PerGameAvg["26_27"].loc[
            rookie_mask,
            target
        ] = (
            PerGameAvg["26_27"]
            .loc[rookie_mask, "PlayerName"]
            .map(rookie_lookup[target])
        )

# Fill position into Pos column
PerGameAvg["26_27"].loc[
    rookie_mask,
    "Pos"
] = (
    PerGameAvg["26_27"]
    .loc[rookie_mask, "PlayerName"]
    .map(rookie_lookup["position"])
)

# Check
print(f"Rookies filled: {rookie_mask.sum()}")

print("\nFilled rookies:")

print(
    PerGameAvg["26_27"]
    .loc[
        rookie_mask,
        ["PlayerName", "Pos"] + target_features
    ]
    .to_string(index=False)
)

Rookies filled: 66

Filled rookies:
        PlayerName Pos        GP    FG_PCT   FG3_PCT    FT_PCT Restricted Area Restricted Area.1 Restricted Area.2 In The Paint (Non-RA) In The Paint (Non-RA).1 In The Paint (Non-RA).2  Mid-Range Mid-Range.1 Mid-Range.2 Left Corner 3 Left Corner 3.1 Left Corner 3.2 Right Corner 3 Right Corner 3.1 Right Corner 3.2 Above the Break 3 Above the Break 3.1 Above the Break 3.2 Backcourt Backcourt.1 Backcourt.2   Corner 3 Corner 3.1 Corner 3.2  D_FREQ      D_FGM      D_FGA  D_FG_PCT  D_NORMAL_FG_PCT  D_PCT_PLUSMINUS  FGA_FREQUENCY  EFG_PCT  FG2A_FREQUENCY       FG2M       FG2A  FG2_PCT  FG3A_FREQUENCY  PTSOFFTO   2ndPTS     FBPs     PITP  Opp PTSOFF TO  Opp2nd PTS  OppFBPs   OppPITP  RemainingGames       Min      FGM       FGA       3PM      FG3A      FTM      FTA     OReb     DReb      REB      Ast       TO      STL      BLK     BLKA       PF      PFD       Pts  NBA_FANTASY_PTS       DD2       TD3  Pts_Paint  Pts_MidRange   Pts_3PT  PLUS_MINUS
    Ugonna Onyenso   C  4.262618  0.275317  0.125720  0.402323       10.278433         10.882312          0.347799              3.328786                6.107701                0.296904  -0.086382    0.792391    0.003626      2.393518         6.95808        0.091006       1.227172         2.817969         -0.05425         -0.617728           -1.837828            0.081927  0.057106    0.014071    0.035369   3.915222   9.153785   0.060487     1.0  31.800512  77.222824  0.392793         0.472706        -0.088648            1.0 0.590512        0.850292  21.121639  32.243141 0.710785        0.137731  0.549728 0.878891 0.865887 2.201010       5.937021    4.439012 5.484580 15.893288        4.262618 13.535430 1.387187  2.584323  0.037208  0.357752 0.797488 1.209258 1.167804 1.813413 3.251646 1.443538 0.775479 0.469524 0.638082 0.216810 1.900159 1.036428  3.580183        12.346710  0.004754  0.000669   2.202924      0.026608  0.364326   -1.098979
   Brayden Burries G-F 13.148291  0.073464  0.070522  0.141267       15.255469         21.233685          0.121313              5.547626               13.955998                0.074511   2.464442    8.708954    0.103834      3.516077        8.849788        0.155295       2.264409         7.919094         0.071698         10.476885           34.020721            0.087311 -0.006616   -0.024746   -0.005359   5.452918  14.113131   0.102151     1.0 135.906784 279.876709  0.481942         0.454658         0.027028            1.0 0.500621        0.504359  60.756916 116.985115 0.509604        0.498000  1.143972 0.781641 1.079383 2.119234       6.995143    5.548760 5.621323 18.956129       13.148291 17.061041 2.341149  5.645206  0.916900  2.912925 0.672418 0.858150 0.565344 1.470864 2.176650 1.273368 0.790592 0.586561 0.085849 0.285901 1.592063 0.847821  6.759213        11.957633  0.004748 -0.000186   1.951357      0.247051  3.029989   -2.163233
   Chris Cenac Jr. C-F  3.748776  0.023274  0.006034  0.024205        3.439496          6.850745           0.06505              0.572966                0.585734                0.037292    -0.0994    0.052828    0.025293      0.186579        0.433378        0.011211       0.005617         0.641054        -0.026893         -0.287446           -1.854556            0.012519 -0.001356   -0.037338    0.001106   0.849377   1.302356   0.004108     1.0  59.555397 135.271378  0.466931         0.466245        -0.002775            1.0 0.624916        0.800324  27.068199  47.796978 0.654512        0.194666  0.483468 0.499658 0.608866 2.482475       4.092115    4.369207 3.510139 11.281611        3.748776 11.002671 1.373430  2.148021  0.069818  0.574403 0.427077 0.733020 0.951647 1.803104 2.827135 1.337373 0.627387 0.386844 0.312286 0.130954 1.163351 0.446226  2.976512        10.424672  0.004856  0.000436   2.675916      0.054358  0.162886    0.038588
      Alpha Diallo F-G 10.966946  0.146754  0.101387  0.243904        4.590209          8.503744           0.20809              0.934137                4.562482                0.121342   0.605588    2.467403    0.141492      1.865112        4.984624        0.133341        1.32936         3.292002         0.135363          4.967777           20.009182            0.099052 -0.009277    -0.02557   -0.002825   2.856368   8.239733   0.112855     1.0  65.838615 133.963959  0.500132         0.459876         0.045053            1.0 0.435658        0.434748   8.172390  14.984627 0.384385        0.575672  0.471667 0.230642 0.383916 0.628489       6.317461    4.741601 5.007070 14.930138       10.966946 13.475593 1.058910  2.689564  0.550425  1.852431 0.503112 0.622017 0.301573 0.790813 1.132071 0.987582 0.659954 0.527203 0.129398 0.189563 1.338853 0.614328  2.738008         8.091610 -0.001203 -0.000293   0.912679      0.173826  1.644257   -6.144887
      Ebuka Okorie   G 11.261095  0.091232  0.073046  0.271874        7.808254         11.775661          0.234302              2.709509                7.266591                0.082244   5.049766    11.64811    0.047116      0.018191        1.160321        0.037004       0.426968         2.063732         0.097589          1.780598            6.787989            0.068591 -0.004299    0.057566    0.001838  -0.789619   2.969561   0.129173     1.0  41.417557 101.222527  0.474389         0.448098         0.028972            1.0 0.452616        0.574328  25.156200  67.389679 0.491236        0.433209  0.784463 0.438356 0.891388 1.633516       4.683656    4.795004 3.772183 11.826258       11.261095 11.188794 2.072134  4.027807  0.846302  2.176582 1.078843 1.211532 0.157993 1.238663 1.484235 2.078185 0.889436 0.667367 0.108419 0.468383 1.055109 0.984694  5.511351        10.620977  0.006731 -0.000193   1.343790      0.299507  1.385930   -2.683211
Christian Anderson   G  0.257716  0.027365  0.057772  0.152138       -5.683245         -8.636227          0.074265             -1.599483               -0.866593                0.030583  -0.218926      2.9163    0.043618      0.417413       -1.675427        0.122392      -0.697746        -1.104562         0.069008          -6.16091          -17.191828            0.051185 -0.009678   -0.034047   -0.006061  -1.471956  -1.092518   0.052715     1.0   4.204301   2.639854  0.497757         0.437690         0.029148            1.0 0.489367        0.447966   3.038944   8.179019 0.422347        0.538195  0.500024 0.423424 0.377097 1.340492       3.030613    3.079062 1.953550  8.991393        0.257716  8.457876 1.201073  3.326344  0.633311  1.794492 0.442642 0.474215 0.145652 0.613920 0.794420 2.574532 0.872159 0.460411 0.028094 0.263868 1.010668 0.463327  3.123944         7.078959  0.025150  0.002257   1.095417      0.202497  1.799932   -1.330590
   Tarik Biberovic F-G 17.775105  0.333874  0.370296  0.473996        6.134665          8.686919          0.386981              1.739347               10.228647                0.348304   7.710316   11.561171     0.34308      5.851551        9.850346        0.303937        3.60113         5.699248         0.407063         30.687811           59.340572            0.330402 -0.002342    0.100517   -0.000631   5.407317  16.417212   0.385692     1.0  64.266487 138.808975  0.552598         0.458935         0.065083            1.0 0.610853        0.347185  28.021322  62.092056 0.539347        0.643940  1.191375 0.959549 0.888328 1.380139       5.952108    5.894485 4.810381 17.897087       17.775105 14.062037 1.853850  4.479662  1.301326  2.989059 0.366128 0.444249 0.376578 1.231690 1.449324 1.100753 0.508521 0.274438 0.007288 0.185503 1.481597 0.339717  5.314153         8.893086  0.005146 -0.000116   1.319101      0.302216  3.430492   -0.789030
     Arthur Kaluma   F 26.275908  0.348874  0.165210  0.734718       38.390671         56.603241          0.545917              3.761259               15.018575                0.304268   0.610187     3.59167    0.247941      2.653609        7.469454        0.136245       2.392424        10.029867         0.167125          4.691837           15.128821            0.135902 -0.013289   -0.009465   -0.013251   5.726622   18.74931   0.196794     1.0  55.836555 111.276649  0.493992         0.459293         0.014880            1.0 0.473204        0.495461  38.875057  62.856567 0.538987        0.503420  0.703887 0.516261 0.555746 1.793483       3.059676    2.340202 3.227440  9.972984       26.275908  9.332187 1.417788  2.942658  0.330441  1.218835 0.538533 0.664150 0.876330 1.092130 1.975659 0.663366 0.320791 0.387450 0.107019 0.238420 1.176113 0.662828  3.783317         8.075278 -0.004553 -0.000202   1.701611      0.154895  0.963426   -1.337394
        Tobi Lawal   F -1.386579  0.052375  0.027770 -0.014756         1.72026          3.793101          0.053185              0.733202                1.848479                0.026001  -0.077347   -1.593083    0.059221     -0.059726       -0.246787        0.026843       -0.16721         0.039757         0.018084         -0.524741           -2.389904            0.035573  0.011212    0.009844    0.015313   -0.88731  -1.447697   0.018168     1.0  21.212534  64.209091  0.499150         0.436942         0.026693            1.0 0.593041        0.754375  21.612040  33.169514 0.584784        0.259365  0.735525 0.579809 0.936140 2.608188       4.078720    3.898607 3.475156 12.492043       -1.386579  9.856371 1.179839  2.360969  0.207820  0.915417 0.656477 1.035254 0.542790 1.503276 2.588998 1.286771 0.538104 0.597102 0.284516 0.178128 1.083702 0.602766  2.933019         9.849887  0.000831 -0.001142   2.622958      0.232408  0.569486    0.214456
    Cameron Boozer F-C 46.689255  0.425951  0.269898  0.674234      100.648888        161.720322          0.521888             44.637562              119.473824                 0.36538  34.660702    79.24395    0.356152      6.360579       19.522728        0.346093       8.815447        19.077782         0.398457          34.03479          105.883652            0.261403 -0.005121    0.022101   -0.001516  15.950212  39.442078   0.359428     1.0 269.246216 499.093323  0.472819         0.476701         0.002505            1.0 0.522866        0.601100 217.166901 407.195526 0.518063        0.389962  1.539588 2.286705 1.075184 5.805587       8.856110    7.838088 7.211116 26.560564       46.689255 24.528168 4.366365  8.584586  1.254232  3.211799 1.814478 2.359324 1.896525 5.007397 6.820848 2.237238 1.173134 0.837893 0.206582 0.461986 1.860206 1.950805 11.906636        24.337152  0.137166  0.000531   5.957345      1.253879  3.840427   -0.645173
   Tarris Reed Jr.   C  6.987162  0.106365 -0.021805  0.150993       15.693125         20.010712           0.21255              2.053681                5.927964                0.100852  -0.211893    0.996035    0.082294      -0.40208       -0.645862       -0.052721      -0.656963        -0.887687        -0.014699          0.493478            0.296201           -0.001614 -0.005164    0.015604   -0.003784  -0.871466   -2.80001  -0.019077     1.0  82.264832 181.738144  0.464839         0.470318        -0.020988            1.0 0.599779        0.976866  38.777748  66.404030 0.614051        0.020840  0.545753 1.385506 0.416400 4.053931       6.120721    4.837446 6.113968 16.067743        6.987162 13.399226 1.684977  2.629094 -0.074971 -0.145337 0.651857 1.291776 2.480438 3.240061 5.151613 0.960335 1.114608 0.742211 0.511299 1.020679 1.535181 1.353437  3.700532        14.081145  0.067475  0.000520   3.953843      0.045000 -0.083307   -2.438413
     Thomas Sorber C-F  0.482243  0.011146 -0.007705  0.009290        -0.67025          1.073622           0.04395             -1.349709                 0.50126                0.030837  -0.531259   -1.831342   -0.002722     -0.191066        0.176458       -0.006791      -0.353032        -1.114861        -0.045966         -1.300826            -3.42293           -0.013341  0.001875    0.045585   -0.000645   -0.61394  -0.913385  -0.030601     1.0  45.863884 116.487663  0.182935         0.470148        -0.263047            1.0 0.246566        0.802438  15.520058  24.767647 0.245268        0.200781  0.198295 0.873757 0.329778 2.162711       4.166216    4.306865 3.955073 12.115252        0.482243 10.857376 0.970265  2.519732  0.039283  0.436572 0.474893 0.857851 1.010760 1.891765 3.209146 0.676188 0.465370 0.437685 0.325107 0.221305 1.388167 0.743083  2.484766         9.563046  0.037017  0.000460   1.867114      0.046111  0.080596   -3.640408
   Darryn Peterson   G 12.744284  0.141258  0.112898  0.259814       24.934046         40.804188          0.200854             11.104117               26.363592                0.157201   13.02592    34.31913     0.16404      4.033478        9.613366        0.157505        5.27081         9.094109         0.171891         20.223421           63.955482            0.114512  0.036434    0.072288    0.020699   8.424045  18.480499   0.127243     1.0 200.937698 402.604919  0.481237         0.458477         0.022347            1.0 0.522994        0.586379 181.584335 376.870941 0.502731        0.414326  2.268019 1.419615 2.087390 5.155810       9.432678    8.281881 8.402088 28.146608       12.744284 25.948133 4.884203 11.255432  1.674658  4.783694 2.108328 2.442059 0.648728 2.318960 3.191383 2.392444 1.567954 1.030355 0.209539 0.696009 2.081186 2.216796 14.174298        22.292376  0.017125 -0.000299   5.161788      1.172156  4.935750   -1.349820
     Emanuel Sharp   G  1.710429  0.071419  0.049284  0.077464       -0.062501         -0.432414          0.049759             -0.136941                 2.59723                0.080314    1.24996    1.689569     0.02846      1.173764        2.140476        0.037808       0.291549         2.162266         0.044091          3.631503            9.024003            0.025806  0.002053   -0.023286    0.002249   2.483816   4.531272   0.034507     1.0  25.550549  43.173054  0.521719         0.443414         0.101971            1.0 0.614511        0.281623   5.585306  17.466799 0.596929        0.719094  1.464593 0.776670 0.599649 1.344012       4.706559    6.316783 5.883474 21.468864        1.710429 15.119179 2.430869  5.785010  0.894821  3.028929 0.778687 0.873383 0.382380 0.735053 1.540389 0.771946 0.404375 0.686976 0.047654 0.259669 1.276074 0.780841  6.912402        13.240537  0.004181 -0.000144   1.514144      0.716914  3.357105   -5.399404
     Rafael Castro F-C  0.479005  0.078094 -0.010138  0.053346        2.855586          4.913096          0.077511               1.37343                2.862832                0.008656   -0.30445   -0.761847     0.01944      -0.06902       -0.202713       -0.020216       0.109035        -0.058824        -0.046629         -0.440496           -2.194363           -0.008991 -0.010598   -0.028984   -0.003441   -0.21692   0.455962  -0.025954     1.0  19.657314  32.306412  0.505762         0.478395         0.009865            1.0 0.604152        0.773902  10.504481  13.623206 0.740363        0.217319  0.336095 0.745207 0.600703 2.886125       4.956891    4.850692 5.457188 16.027292        0.479005 13.249867 1.551697  2.976140  0.046280  0.760954 0.745846 1.059908 0.953847 1.749881 2.846633 1.132699 0.567833 0.516291 0.392236 0.142226 1.285045 0.645210  3.925238        11.718247  0.000360  0.000420   3.061987      0.220327  0.280192   -2.159683
     Tre Donaldson   G  6.407414  0.292448  0.146014  0.677784        3.132818          2.759516           0.35267              3.842108                9.887149                0.282353   1.794605    6.637972    0.257715     -0.301025       -2.466285        0.121516      -0.043559        -0.015874         0.134433          1.888421           10.189418            0.141275  0.005055    0.002123   -0.007314  -1.193798   0.300141   0.200916     1.0  17.459238  32.155758  0.504769         0.442247         0.027037            1.0 0.467352        0.584773   9.881027  29.267944 0.599523        0.417618  0.675216 0.380170 0.706941 1.441701       3.768410    3.878560 2.902464 12.913251        6.407414  9.874297 1.291460  2.916478  0.487337  1.792745 0.514954 0.604721 0.211271 0.864903 0.777064 1.145397 0.658032 0.438540 0.205908 0.150353 0.883850 0.504064  3.422229         7.342638  0.002368  0.000595   1.270416      0.497392  1.638102   -1.951346
     Michael Ajayi   F  3.985181  0.301046  0.061573  0.512072        3.755715           7.27081           0.24279              1.427193                1.127152                0.318868  -0.045005     0.19582    0.174949     -0.637059       -0.297923        0.018539      -0.547381        -1.022198        -0.019284          0.008246           -2.661924            0.017816 -0.000209   -0.015805   -0.003534  -1.806546  -3.324514   0.030157     1.0  10.019974  13.295197  0.498683         0.473800         0.023524            1.0 0.552358        0.766540   6.899151  14.801192 0.638888        0.236947  0.467497 1.103415 0.640370 3.010287       4.010375    3.785281 4.319499 11.347241        3.985181 10.780116 1.236014  2.400165  0.006151  0.514500 0.536091 0.808773 1.464707 2.093671 3.581444 0.906069 0.484931 0.490325 0.235784 0.149602 1.175672 0.615347  2.980865        10.732918  0.061613  0.000402   3.050917      0.202735  0.195649   -1.973204
    Tyler Bilodeau F-C  1.970750  0.057245  0.047991  0.036452        0.375981         -0.891984          0.020445              0.456064               -0.460915                0.018309   1.844805     3.10284    0.023433      1.527572        2.814007        0.039189       0.602057         0.926677         0.082114          5.176009           11.115009            0.019257 -0.002957    0.028082   -0.001777   2.463504   4.120193   0.079777     1.0  16.122219  34.161152  0.483051         0.454618         0.014111            1.0 0.557697        0.340871   8.694704  16.148386 0.451492        0.666042  0.787883 0.588758 0.440062 1.103890       3.606079    5.005009 3.559771 13.531106        1.970750 10.776304 1.367908  3.291157  1.151211  2.456795 0.503907 0.671969 0.437468 1.043878 1.211970 0.848124 0.487683 0.244807 0.074380 0.102083 1.132395 0.536697  4.778321         7.860888  0.004319  0.000738   1.054815      0.252849  3.577153   -0.666958
   Mikel Brown Jr.   G  5.881489  0.025677  0.038431  0.073939        6.626463          5.180122          0.052855              4.867123               12.220224                0.050285   1.064893    5.917315    0.027445      0.960145         1.21807        0.034252       0.386063         1.992608        -0.012627          7.569541           17.587746            0.050063 -0.007518   -0.024203   -0.006486   1.460598   2.402739  -0.002832     1.0 125.847336 249.944061  0.484696         0.452054         0.032652            1.0 0.495998        0.557282  58.364109 124.983643 0.488814        0.447294  1.160771 0.632893 1.072117 2.643111       8.638480    6.727172 7.164720 22.583332        5.881489 19.496050 2.652772  6.974987  1.154396  3.773960 1.021409 1.119563 0.255170 1.355249 1.764284 3.954828 1.832121 0.918152 0.102941 0.400791 1.888839 1.206633  7.920315        15.879205  0.032205 -0.000237   2.400925      0.310029  3.354853   -3.409126

/var/folders/0b/n3f548tn3156qpndhm9hlkhh0000gn/T/ipykernel_9238/1517511970.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 4.262618   13.148291    3.748776   10.966946   11.261095    0.25771648
 17.775105   26.275908   -1.3865786  46.689255    6.9871616   0.48224273
 12.744284    1.7104288   0.47900546  6.407414    3.9851806   1.9707501
  5.881489    3.3504097  28.397736    5.2805057   0.76293486 47.798954
  4.140121   34.081177   24.029148    3.2114587   2.6571782   2.272371
  6.916379    7.515614    1.9493376   1.5273962  13.184913    7.6049366
  5.605511   17.868107    2.717323    7.367136    5.860447   12.4462385
 10.910557    4.0978413   5.6570396   7.0710254  12.356931    6.901443
  0.8389959  16.742785    2.855486   10.489775    3.5877585   1.1559951
  5.341297    4.1706443   2.5323644   4.072696    8.433491    8.486126
 -1.416979   10.267068   17.852776    4.445592   10.033653    5.378837  ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  PerGameAvg["26_27"].loc[
/var/folders/0b/n3f548tn3156qpndhm9hlkhh0000gn/T/ipykernel_9238/1517511970.py:16: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 4.262618   13.148291    3.748776   10.966946   11.261095    0.25771648
 17.775105   26.275908   -1.3865786  46.689255    6.9871616   0.48224273
 12.744284    1.7104288   0.47900546  6.407414    3.9851806   1.9707501
  5.881489    3.3504097  28.397736    5.2805057   0.76293486 47.798954
  4.140121   34.081177   24.029148    3.2114587   2.6571782   2.272371
  6.916379    7.515614    1.9493376   1.5273962  13.184913    7.6049366
  5.605511   17.868107    2.717323    7.367136    5.860447   12.4462385
 10.910557    4.0978413   5.6570396   7.0710254  12.356931    6.901443
  0.8389959  16.742785    2.855486   10.489775    3.5877585   1.1559951
  5.341297    4.1706443   2.5323644   4.072696    8.433491    8.486126
 -1.416979   10.267068   17.852776    4.445592   10.033653    5.378837  ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  PerGameAvg["26_27"].loc[

Debugging

In [31]:
matches = PerGameAvg["26_27"][
    PerGameAvg["26_27"]["PlayerName"]
    .astype(str)
    .str.contains("Darius Acuff", case=False, na=False)
]

print(matches.to_string(index=False))

 PlayerID       PlayerName  TeamID TeamAbbv  Age        GP  W  L  W_Pct   FG_PCT  FG3_PCT   FT_PCT Restricted Area Restricted Area.1 Restricted Area.2 In The Paint (Non-RA) In The Paint (Non-RA).1 In The Paint (Non-RA).2 Mid-Range Mid-Range.1 Mid-Range.2 Left Corner 3 Left Corner 3.1 Left Corner 3.2 Right Corner 3 Right Corner 3.1 Right Corner 3.2 Above the Break 3 Above the Break 3.1 Above the Break 3.2 Backcourt Backcourt.1 Backcourt.2   Corner 3 Corner 3.1 Corner 3.2 Pos  D_FREQ      D_FGM      D_FGA  D_FG_PCT  D_NORMAL_FG_PCT  D_PCT_PLUSMINUS  FGA_FREQUENCY  EFG_PCT  FG2A_FREQUENCY      FG2M       FG2A  FG2_PCT  FG3A_FREQUENCY  PTSOFFTO   2ndPTS     FBPs     PITP  Opp PTSOFF TO  Opp2nd PTS  OppFBPs   OppPITP  RemainingGames       Min      FGM      FGA      3PM     FG3A     FTM    FTA     OReb     DReb      REB      Ast       TO      STL     BLK     BLKA       PF      PFD      Pts  NBA_FANTASY_PTS      DD2      TD3  Pts_Paint  Pts_MidRange  Pts_3PT  PLUS_MINUS
        0 Darius Acuff Jr.       0      SAC  0.0 28.397736  0  0    0.0 0.371815 0.373931 0.516518       35.225895         66.658546          0.473592             25.877277               54.936443                0.325745  4.799785   14.401191    0.357576      4.676942       10.453889        0.274957       6.755194        11.253757         0.337427         43.840496           91.569115            0.347752 -0.006866   -0.015715   -0.002935  10.492158   25.19359   0.306126   G     1.0 152.261368 294.657166  0.483532         0.448241         0.025547            1.0 0.513254        0.505294 91.693832 175.374908 0.476649        0.486068  1.306056 0.588499 1.461666 2.952546       7.829787    5.502485 6.334441 20.303371       28.397736 18.203018 3.063381 7.323595 1.599261 4.139513 1.26778 1.5181 0.269908 1.244225 1.491045 5.390798 1.963463 0.713831 0.15138 0.426966 1.589709 1.657784 8.580112        17.061167 0.060968 0.001682   2.416057      0.298837 4.568202   -0.967506

In [32]:
PerGameAvg["26_27"] = PerGameAvg["26_27"].drop_duplicates(
    subset=["PlayerID", "PlayerName"]
)

name_overrides2 = {
    "Damian Lillard": "POR",
    "Tyrese Haliburton": "IND",
    "Kyrie Irving": "DAL",
    "Jimmy Butler": "GSW",
    "Ja Morant": "POR",
    "Trae Young": "WAS",
    "Anthony Davis": "WAS",
    "Fred VanVleet": "HOU",
    "Domantas Sabonis": "SAC",
    "Jaren Jackson Jr.": "UTA",
    "Zach LaVine": "SAC",
    "Zach Edey": "MEM",
    "Walker Kessler": "LAL"
}

PerGameAvg["26_27"].loc[
    PerGameAvg["26_27"]["PlayerName"].isin(name_overrides2),
    "TeamAbbv"
] = PerGameAvg["26_27"]["PlayerName"].map(name_overrides2)

# Step 9: Generate team rosters for each season

In [33]:
# Dicionary of the projected ESPN depth charts for each team
depth_charts = {
    "ATL": {
        "PG": ["C. McCollum", "K. Flemings", "R. Nembhard Jr.", "N. Alexander-Walker", "D. Daniels", "R. Dennis", "K. Gilbert"],
        "SG": ["N. Alexander-Walker", "L. Dort", "C. Kispert", "A. Wiggins", "C. McCollum", "D. Daniels", "B. Hield", "K. Gilbert", "J. Wilson"],
        "SF": ["D. Daniels", "A. Wiggins", "L. Dort", "C. Kispert", "B. Hield", "N. Alexander-Walker", "J. Wilson"],
        "PF": ["J. Johnson", "A. Wiggins", "M. Gueye", "A. Newell", "Z. Ejiofor", "C. Kispert", "J. Wilson"],
        "C": ["O. Okongwu", "J. Landale", "M. Gueye", "Z. Ejiofor", "H. Veesaar", "T. Bradley", "A. Newell"],
    },

    "BOS": {
        "PG": ["D. White", "P. Pritchard", "M. Conley"],
        "SG": ["B. Scheierman", "P. Pritchard", "H. Gonzalez", "D. White", "R. Harper Jr."],
        "SF": ["P. George", "S. Hauser", "B. Scheierman", "H. Gonzalez", "R. Harper Jr.", "J. Walsh", "D. Mitchell"],
        "PF": ["J. Tatum", "J. Walsh", "P. George", "C. Cenac Jr.", "S. Hauser", "R. Harper Jr.", "H. Gonzalez", "L. Garza", "B. Scheierman", "D. Mitchell"],
        "C": ["N. Queta", "M. Robinson", "L. Garza", "C. Cenac Jr.", "A. Williams"],
    },

    "BKN": {
        "PG": ["M. Brown Jr.", "B. Saraf", "N. Traore", "E. Demin", "T. Mann"],
        "SG": ["E. Demin", "D. Powell", "K. Ellis", "M. Brown Jr.", "T. Mann"],
        "SF": ["M. Porter Jr.", "K. Ellis", "N. Clowney", "J. Minott", "T. Mann", "C. Johnson", "D. Powell"],
        "PF": ["J. Randle", "N. Clowney", "J. Jefferson", "D. Wolf", "K. Ellis", "J. Minott", "C. Johnson", "T. Bilodeau"],
        "C": ["D. Sharpe", "M. Wagner", "D. Wolf", "J. Minott", "C. Johnson", "G. Nelson"],
    },

    "CHA": {
        "PG": ["C. White", "D. Schroder", "C. Anderson"],
        "SG": ["K. Knueppel", "G. Allen", "S. James", "C. White", "D. Schroder", "L. McNeeley", "P. Connaughton"],
        "SF": ["B. Miller", "S. James", "G. Allen", "R. O'Neale", "D. Finney-Smith", "L. McNeeley", "T. Salaun", "P. Connaughton"],
        "PF": ["N. Reid", "R. O'Neale", "G. Williams", "D. Finney-Smith", "T. Salaun", "S. James", "H. Steinbach", "L. McNeeley", "P. Connaughton", "P. Hall"],
        "C": ["H. Steinbach", "M. Diabate", "R. Kalkbrenner", "N. Reid", "P. Hall"],
    },

    "CHI": {
        "PG": ["J. Giddey", "T. Jones", "R. Dillingham"],
        "SG": ["N. Powell", "I. Okoro", "T. Jones", "R. Dillingham"],
        "SF": ["M. Buzelis", "D. Swain", "I. Okoro", "N. Powell", "C. Wilson", "L. Miller", "N. Essengue", "P. Williams"],
        "PF": ["C. Wilson", "P. Williams", "D. Swain", "M. Buzelis", "L. Miller", "J. Smith", "N. Essengue", "Z. Collins", "T. Awaka"],
        "C": ["N. Claxton", "J. Smith", "Z. Collins", "T. Awaka", "L. Miller"],
    },

    "CLE": {
        "PG": ["J. Harden", "C. Porter Jr.", "T. Proctor"],
        "SG": ["D. Mitchell", "S. Merrill", "T. Proctor", "J. Tyson", "C. Porter Jr.", "M. Thomas"],
        "SF": ["P. Watson", "J. Tyson", "S. Merrill", "M. Hezonja", "N. Tomlin", "T. Enaruna", "R. Minix"],
        "PF": ["E. Mobley", "P. Watson", "N. Tomlin", "J. Tyson", "M. Hezonja", "T. Enaruna", "R. Minix"],
        "C": ["J. Allen", "E. Mobley", "T. Bryant", "K. Diop", "E. Udeh Jr."],
    },

    "DAL": {
        "PG": ["K. Irving", "M. Sasser", "C. Flagg", "S. de Larrea"],
        "SG": ["M. Christie", "Z. Risacher", "C. Martin", "M. Sasser", "N. Marshall", "S. de Larrea", "J. Poulakidas", "J. Howard", "K. Irving", "V. Ishchenko", "T. Biberovic"],
        "SF": ["C. Flagg", "N. Marshall", "Z. Risacher", "S. Aldama", "C. Martin", "J. Poulakidas", "M. Christie", "P. Washington", "T. Lawal", "J. Howard", "V. Ishchenko", "T. Biberovic"],
        "PF": ["P. Washington", "M. Johnson Jr.", "S. Aldama", "C. Martin", "C. Flagg", "N. Marshall", "T. Lawal", "J. Howard", "T. Biberovic"],
        "C": ["D. Lively II", "D. Gafford", "M. Cisse", "S. Aldama", "M. Johnson Jr.", "P. Washington"],
    },

    "DEN": {
        "PG": ["J. Murray", "T. Jones", "K. Simpson"],
        "SG": ["C. Braun", "D. DeRozan", "J. Strawther", "S. Jones", "L. Walker IV", "T. Jones", "C. Johnson"],
        "SF": ["C. Johnson", "D. DeRozan", "J. Strawther", "L. Walker IV", "A. Diallo", "S. Jones", "C. Braun", "B. Hopkins"],
        "PF": ["A. Gordon", "D. DeRozan", "S. Jones", "A. Diallo", "T. Brazile", "C. Johnson", "M. Bagley III", "B. Hopkins", "Z. Nnaji", "J. Strawther"],
        "C": ["N. Jokic", "M. Bagley III", "A. Gordon", "Z. Nnaji", "D. Holmes II", "T. Brazile"],
    },

    "DET": {
        "PG": ["C. Cunningham", "D. Jenkins", "E. Okorie", "E. Harkless"],
        "SG": ["D. Robinson", "I. Joe", "K. Huerter", "G. Harris", "D. Jenkins", "R. Holland II", "T. Prince", "C. Lanier", "E. Harkless"],
        "SF": ["A. Thompson", "D. Robinson", "I. Joe", "K. Huerter", "J. Green", "T. Prince", "R. Holland II", "G. Harris", "C. Lanier"],
        "PF": ["J. Collins", "R. Holland II", "T. Prince", "I. Jones"],
        "C": ["J. Duren", "P. Reed", "J. Collins", "T. Smith", "U. Onyenso", "I. Jones"],
    },

    "GSW": {
        "PG": ["S. Curry", "D. Melton", "B. Podziemski", "B. Williams", "G. Payton II", "L. Cryer", "W. Richard"],
        "SG": ["B. Podziemski", "D. Melton", "W. Richard", "G. Payton II", "G. Santos", "M. Moody"],
        "SF": ["G. Santos", "Y. Lendeborg", "W. Richard", "G. Payton II", "L. Jones", "G. Niang", "M. Leons", "J. Butler III", "M. Moody"],
        "PF": ["D. Green", "Y. Lendeborg", "G. Santos", "G. Niang", "K. Porzingis", "A. Horford", "L. Jones", "M. Leons", "J. Butler III", "M. Moody"],
        "C": ["K. Porzingis", "A. Horford", "D. Green", "C. Bassey"],
    },

    "HOU": {
        "PG": ["F. VanVleet", "M. Smart", "A. Thompson", "B. Thornton", "R. Sheppard", "B. Bogdanovic", "Q. Copeland", "S. Pedulla"],
        "SG": ["A. Thompson", "R. Sheppard", "M. Smart", "B. Bogdanovic", "T. Eason", "K. Durant", "B. Thornton", "Q. Copeland", "S. Pedulla"],
        "SF": ["K. Durant", "T. Eason", "B. Bogdanovic", "J. Tate", "J. Smith Jr.", "I. Crawford"],
        "PF": ["J. Smith Jr.", "T. Eason", "J. Tate", "A. Sengun", "I. Crawford"],
        "C": ["A. Sengun", "S. Adams", "J. Smith Jr.", "C. Capela", "O. Tshiebwe", "R. Castro"],
    },

    "IND": {
        "PG": ["T. Haliburton", "T. McConnell", "A. Nembhard", "Q. Jackson", "B. Smith", "B. Sheppard"],
        "SG": ["A. Nembhard", "K. Oubre Jr.", "B. Sheppard", "J. Furphy", "Q. Jackson", "A. Nesmith"],
        "SF": ["A. Nesmith", "J. Walker", "K. Oubre Jr.", "J. Furphy", "K. Brown", "J. Slawson", "B. Sheppard", "Q. Jackson"],
        "PF": ["P. Siakam", "O. Toppin", "K. Oubre Jr.", "K. Brown", "L. Nance Jr.", "J. Walker", "J. Slawson", "J. Huff"],
        "C": ["I. Zubac", "L. Nance Jr.", "J. Huff", "K. Brown", "O. Toppin", "P. Siakam"],
    },

    "LAC": {
        "PG": ["D. Garland", "K. Dunn", "K. Wagler", "B. Beal", "J. Miller", "J. Pickett"],
        "SG": ["K. Wagler", "B. Beal", "G. Dick", "K. Dunn", "K. Sanders", "C. Christie", "J. Miller"],
        "SF": ["B. Ingram", "M. Strus", "K. Sanders", "R. Hachimura", "D. Jones Jr.", "G. Dick", "J. Miller", "N. Martinelli", "C. Christie"],
        "PF": ["D. Jones Jr.", "R. Hachimura", "M. Strus", "B. Miller", "K. Sanders", "J. Broome", "N. Martinelli"],
        "C": ["B. Lopez", "I. Jackson", "B. Miller", "Y. Niederhauser", "J. Broome", "J. Sharp"],
    },

    "LAL": {
        "PG": ["L. Doncic", "C. Sexton", "A. Reaves", "Q. Grimes", "B. James"],
        "SG": ["A. Reaves", "C. Sexton", "C. Carr", "M. Thybulle", "Z. Williams", "Q. Grimes", "J. LaRavia", "B. James", "J. Hardy", "D. Knecht", "C. Manon"],
        "SF": ["Q. Grimes", "C. Carr", "M. Thybulle", "Z. Williams", "D. Knecht", "A. Thiero", "J. LaRavia", "J. Hardy", "C. Manon", "A. Kaluma", "A. Okereke"],
        "PF": ["J. LaRavia", "S. Mamukelashvili", "J. Vanderbilt", "M. Thybulle", "Z. Williams", "A. Thiero", "A. Kaluma", "A. Okereke"],
        "C": ["W. Kessler", "K. Looney", "S. Mamukelashvili"],
    },

    "MEM": {
        "PG": ["S. Pippen Jr.", "T. Jerome", "C. Spencer", "J. Small", "W. Clayton Jr.", "D. Russell", "J. Mashack"],
        "SG": ["C. Coward", "T. Jerome", "W. Clayton Jr.", "C. Spencer", "J. Hawkins", "D. Russell", "J. Mashack", "J. Small", "S. Pippen Jr.", "R. Saunders"],
        "SF": ["J. Grant", "J. Wells", "G. Jackson", "K. Lopez", "C. Spencer", "C. Coward", "K. Murray", "O. Prosper", "M. Peavy", "J. Mashack", "R. Saunders"],
        "PF": ["C. Boozer", "T. Hendricks", "I. Stewart", "G. Jackson", "J. Grant", "K. Lopez", "O. Prosper", "K. Murray", "J. Wells"],
        "C": ["Z. Edey", "I. Stewart", "Q. Post", "T. Hendricks", "O. Prosper", "C. Boozer"],
    },

    "MIA": {
        "PG": ["D. Mitchell", "D. Smith", "R. Conwell", "T. Donaldson"],
        "SG": ["T. Hardaway Jr.", "K. Thompson", "R. Conwell", "P. Larsson", "M. Gardner", "D. Smith"],
        "SF": ["A. Wiggins", "K. Thompson", "P. Larsson", "T. Hardaway Jr.", "M. Gardner", "S. Fontecchio", "K. Johnson"],
        "PF": ["G. Antetokounmpo", "B. Portis", "K. Thompson", "A. Wiggins", "S. Fontecchio", "N. Jovic", "M. Gardner", "B. Adebayo", "K. Johnson"],
        "C": ["B. Adebayo", "B. Portis", "N. Richards", "N. Jovic", "V. Goldin"],
    },

    "MIL": {
        "PG": ["R. Rollins", "K. Porter Jr.", "K. Jakucionis", "C. LeVert", "B. Burries", "T. Herro", "C. Ryan", "K. Jones", "A. Green"],
        "SG": ["T. Herro", "B. Burries", "G. Trent Jr.", "C. LeVert", "K. Porter Jr.", "K. Jakucionis", "J. Jaquez Jr.", "A. Green", "C. Ryan", "K. Jones", "R. Rollins"],
        "SF": ["J. Jaquez Jr.", "O. Dieng", "G. Trent Jr.", "N. Ament", "K. Kuzma", "A. Green", "C. LeVert"],
        "PF": ["K. Kuzma", "N. Ament", "O. Dieng", "K. Ware", "J. Jaquez Jr.", "B. Markovic", "J. Sims", "P. Nance"],
        "C": ["M. Turner", "K. Ware", "J. Sims", "O. Dieng", "B. Markovic"],
    },

    "MIN": {
        "PG": ["L. Ball", "I. Evans", "B. Hyland", "A. Dosunmu", "Z. Pullin", "D. DiVincenzo"],
        "SG": ["A. Edwards", "T. Shannon Jr.", "I. Evans", "A. Dosunmu", "B. Hyland", "J. Clark", "C. Williams", "Z. Pullin"],
        "SF": ["A. Dosunmu", "J. Kuminga", "T. Shannon Jr.", "J. Clark", "C. Williams", "J. McDaniels", "I. Evans"],
        "PF": ["J. McDaniels", "J. Kuminga", "E. Freeman", "T. Shannon Jr.", "T. Kaufman-Renn", "T. Lyles", "C. Williams"],
        "C": ["R. Gobert", "J. Beringer", "R. Zikarsky", "E. Freeman", "T. Kaufman-Renn"],
    },

    "NOP": {
        "PG": ["D. Murray", "J. Fears", "J. Poole", "T. Murphy III"],
        "SG": ["T. Murphy III", "B. Mathurin", "J. Fears", "J. Pierre Jr.", "J. Poole", "H. Jones", "B. McGowens", "A. Johnson"],
        "SF": ["S. Bey", "B. Mathurin", "H. Jones", "J. Pierre Jr.", "B. McGowens"],
        "PF": ["Z. Williamson", "D. Queen", "K. Matkovic", "S. Bey", "T. Watford", "M. Dia"],
        "C": ["H. Jones", "Y. Missi", "K. Matkovic", "D. Queen", "D. Jordan", "C. Koloko", "Z. Williamson", "M. Dia"],
    },

    "NYK": {
        "PG": ["J. Brunson", "M. McBride", "J. Alvarado", "T. Kolek", "J. Clarkson", "J. Kayil"],
        "SG": ["J. Hart", "L. Shamet", "M. McBride", "J. Clarkson", "P. Dadiet", "J. Kayil", "T. Nickel"],
        "SF": ["M. Bridges", "J. Clarkson", "J. Hart", "T. Nickel", "L. Shamet", "P. Dadiet"],
        "PF": ["O. Anunoby", "K. Towns", "M. Diawara", "J. Hart", "P. Dadiet"],
        "C": ["K. Towns", "A. Drummond", "M. Diawara"],
    },

    "OKC": {
        "PG": ["S. Gilgeous-Alexander", "A. Mitchell", "B. Stirtz", "N. Topic", "J. McCain", "C. Wallace", "O. Oweh"],
        "SG": ["C. Wallace", "J. McCain", "A. Mitchell", "B. Stirtz", "A. Caruso", "N. Topic", "O. Oweh", "J. Dix"],
        "SF": ["J. Williams", "C. Wallace", "A. Caruso", "K. Williams", "B. Barnhizer", "O. Oweh", "J. Dix"],
        "PF": ["C. Holmgren", "A. Caruso", "K. Williams", "J. Williams", "B. Barnhizer"],
        "C": ["I. Hartenstein", "J. Williams", "A. Mara", "T. Sorber"],
    },

    "ORL": {
        "PG": ["J. Suggs", "A. Black", "J. Carter", "J. Richardson", "A. Morales"],
        "SG": ["D. Bane", "A. Black", "J. Cain", "N. Penda", "J. Richardson", "J. Carter", "A. Morales"],
        "SF": ["F. Wagner", "J. Cain", "T. da Silva", "N. Penda", "D. Bane"],
        "PF": ["P. Banchero", "T. da Silva", "N. Penda", "J. Cain", "J. Isaac", "I. Nelson", "C. Castleton"],
        "C": ["W. Carter Jr.", "N. Vucevic", "G. Bitadze", "I. Nelson", "C. Castleton"],
    },

    "PHI": {
        "PG": ["T. Maxey", "L. Philon Jr.", "A. Simons", "V. Edgecombe", "K. Caldwell-Pope", "C. Love"],
        "SG": ["V. Edgecombe", "A. Simons", "K. Caldwell-Pope", "L. Philon Jr.", "J. Brown", "R. Rupert", "C. Love"],
        "SF": ["J. Brown", "K. Caldwell-Pope", "J. Edwards", "J. Walker", "D. Wade", "L. James", "R. Rupert"],
        "PF": ["L. James", "D. Wade", "D. Barlow", "J. Edwards", "J. Walker", "A. Bona", "R. Rupert"],
        "C": ["J. Embiid", "A. Bona", "A. Hukporti", "D. Barlow", "J. Walker"],
    },

    "PHX": {
        "PG": ["D. Booker", "C. Gillespie", "L. Kennard", "J. Bouyea", "J. Goodwin", "P. Spencer"],
        "SG": ["J. Green", "L. Kennard", "D. Booker", "J. Goodwin", "C. Gillespie", "J. Bouyea", "P. Spencer", "K. Brea"],
        "SF": ["D. Brooks", "J. Goodwin", "K. Peat", "R. Fleming", "R. Dunn", "L. Kennard", "J. Green", "H. Highsmith", "K. Brea"],
        "PF": ["M. Bridges", "R. Dunn", "K. Peat", "R. Fleming", "D. Brooks", "J. Goodwin", "H. Highsmith", "C. Huntley"],
        "C": ["O. Ighodaro", "K. Maluach", "K. Peat", "R. Fleming", "C. Huntley", "M. Williams"],
    },

    "POR": {
        "PG": ["J. Morant", "S. Henderson", "J. Holiday", "B. Wesley", "D. Avdija", "V. Krejci", "D. Lillard", "S. Sharpe"],
        "SG": ["D. Lillard", "J. Holiday", "V. Krejci", "J. Morant", "T. Camara", "B. Wesley", "S. Sharpe", "C. Youngblood", "J. Tonje"],
        "SF": ["T. Camara", "V. Krejci", "J. Sochan", "J. Holiday", "D. Avdija", "S. Cissoko", "S. Sharpe", "J. Kent", "J. Tonje"],
        "PF": ["D. Avdija", "S. Cissoko", "J. Sochan", "M. Potter", "R. Williams III", "J. Kent"],
        "C": ["D. Clingan", "R. Williams III", "M. Potter", "S. Cissoko", "Y. Hansen", "B. Carlson"],
    },

    "SAC": {
        "PG": ["D. Acuff Jr.", "M. Monk", "B. Simmons", "A. Flagler"],
        "SG": ["Z. LaVine", "N. Clifford", "M. Monk", "E. Sharp", "D. Plowden", "A. Flagler"],
        "SF": ["D. Hunter", "N. Clifford", "B. Simmons", "A. Karaban", "M. Monk", "D. Plowden", "K. Murray"],
        "PF": ["K. Murray", "P. Achiuwa", "D. Hunter", "D. Cardwell", "A. Karaban", "D. Plowden", "D. Sabonis", "N. Clifford", "J. Mogbo"],
        "C": ["D. Sabonis", "M. Raynaud", "D. Cardwell", "P. Achiuwa", "J. Mogbo"],
    },

    "SAS": {
        "PG": ["D. Fox", "D. Harper", "J. McLaughlin", "J. Gillespie", "D. Jones Garcia"],
        "SG": ["S. Castle", "D. Harper", "J. Champagnie", "J. McLaughlin", "K. Johnson", "D. Jones Garcia"],
        "SF": ["D. Vassell", "C. Bryant", "K. Johnson", "J. Champagnie", "H. Barnes", "D. Jones Garcia"],
        "PF": ["T. Harris", "J. Champagnie", "K. Johnson", "H. Barnes", "C. Bryant", "J. Quaintance", "L. Kornet", "M. Brown"],
        "C": ["V. Wembanyama", "L. Kornet", "T. Reed Jr.", "J. Quaintance"],
    },

    "TOR": {
        "PG": ["I. Quickley", "J. Shead", "J. Walter", "J. Bradley", "S. Barnes", "C. Hepburn", "M. Smith"],
        "SG": ["R. Barrett", "J. Walter", "J. Shead", "J. Bradley", "A. Martin", "M. Smith"],
        "SF": ["K. Leonard", "A. Graves", "J. Battle", "S. Barnes", "K. Anderson", "J. Walter"],
        "PF": ["S. Barnes", "C. Murray-Boyles", "K. Anderson", "A. Graves", "R. Barrett", "J. Battle"],
        "C": ["J. Poeltl", "C. Murray-Boyles", "T. Jackson-Davis", "J. Battle", "T. Jemison III"],
    },

    "UTA": {
        "PG": ["K. George", "I. Collier", "D. Peterson", "T. Alexander"],
        "SG": ["D. Peterson", "A. Bailey", "J. Okogie", "B. Sensabaugh", "S. Mykhailiuk", "T. Bates", "T. Alexander", "J. Green"],
        "SF": ["L. Markkanen", "B. Sensabaugh", "J. Okogie", "J. Green", "A. Bailey", "S. Mykhailiuk", "H. Ingram", "B. Hinson"],
        "PF": ["J. Jackson Jr.", "K. Filipowski", "A. Bailey", "L. Markkanen", "B. Hinson", "B. Sensabaugh", "H. Ingram", "J. Okogie"],
        "C": ["J. Nurkic", "J. Hayes", "K. Filipowski", "J. Jackson Jr.", "M. Bamba", "B. Hinson"],
    },

    "WAS": {
        "PG": ["T. Young", "B. Carrington", "T. Mann", "T. Johnson"],
        "SG": ["K. George", "T. Johnson", "B. Carrington", "W. Riley", "A. Williams", "T. Mann", "J. Watkins"],
        "SF": ["A. Dybantsa", "B. Coulibaly", "W. Riley", "K. Middleton", "K. George", "J. Champagnie", "T. Johnson", "J. Watkins"],
        "PF": ["A. Davis", "K. Middleton", "J. Champagnie", "W. Riley", "A. Dybantsa", "B. Coulibaly", "T. Vukcevic", "J. Watkins"],
        "C": ["A. Sarr", "D. Ayton", "T. Vukcevic", "A. Davis", "F. Okpara", "J. Champagnie"],
    },
}

In [34]:
# Helper function that creates team rosters
def create_team_rosters(data):

    team_rosters = {}

    for season, df in data.items():

        if "TeamAbbv" not in df.columns:
            raise ValueError(
                f"{season} is missing 'TeamAbbv'"
            )

        team_rosters[season] = {}

        teams = sorted(
            df["TeamAbbv"]
            .dropna()
            .unique()
        )

        for team in teams:

            team_rosters[season][team] = df[
                df["TeamAbbv"] == team
            ].copy()

    return team_rosters

In [35]:
# Helper function that Matches depth chart to rosters
def match_depth_charts_to_rosters(
    depth_charts,
    team_rosters,
    season="26_27"
):

    matched_depth_charts = {}
    unmatched_players = {}

    for team_abbr, positions in depth_charts.items():

        # Check that team exists
        if season not in team_rosters:
            raise ValueError(
                f"Season '{season}' not found in team_rosters"
            )

        if team_abbr not in team_rosters[season]:
            print(
                f"WARNING: {team_abbr} not found in "
                f"team_rosters[{season}]"
            )
            continue

        # Get roster
        roster = team_rosters[season][team_abbr].copy()

        # Create last name column
        roster["_LastName"] = (
            roster["PlayerName"]
            .astype(str)
            .str.strip()
            .str.split()
            .str[-1]
            .str.lower()
        )

        matched_depth_charts[team_abbr] = {}
        unmatched_players[team_abbr] = []

        # Loop through positions
        for position, players in positions.items():

            matched_depth_charts[team_abbr][position] = []

            # Loop through depth chart players
            for depth_player in players:

                # Example:
                # "A. Davis" -> "davis"

                depth_last_name = (
                    depth_player
                    .strip()
                    .split()[-1]
                    .lower()
                )

                # Find matching player(s)
                matches = roster[
                    roster["_LastName"] == depth_last_name
                ]

                # Match found
                if not matches.empty:

                    for _, row in matches.iterrows():

                        matched_depth_charts[
                            team_abbr
                        ][position].append(
                            row["PlayerName"]
                        )

                # No match
                else:

                    unmatched_players[
                        team_abbr
                    ].append(
                        depth_player
                    )

        # Remove temporary column
        roster.drop(
            columns="_LastName",
            inplace=True
        )

    return matched_depth_charts, unmatched_players

In [36]:
# Create team rosters from per game data
team_rosters = create_team_rosters(PerGameAvg)


# Match depth chart to rosters
matched_depth_charts, unmatched_players = (
    match_depth_charts_to_rosters(
        depth_charts,
        team_rosters,
        season="26_27"
    )
)

In [37]:
# Helper function that gets last name
def get_last_name(name):

    suffixes = {
        "jr",
        "jr.",
        "sr",
        "sr.",
        "ii",
        "iii",
        "iv",
        "v"
    }

    parts = (
        str(name)
        .strip()
        .replace(",", "")
        .split()
    )

    if not parts:
        return ""

    # Remove suffix
    if parts[-1].lower() in suffixes and len(parts) > 1:
        parts = parts[:-1]

    return parts[-1].lower()

In [38]:
matched_depth_charts, unmatched_players = match_depth_charts_to_rosters(
    depth_charts,
    team_rosters,
    season="26_27"
)

In [39]:
# Helper function that creates a dictionary of NBA team rosters from player data.
# Expected structure: data[season] = DataFrame
# Required columns: TeamAbbv
# Returns: rosters[season][team_abbreviation] = DataFrame
def create_team_rosters(data):
    team_rosters = {}

    for season, df in data.items():

        if "TeamAbbv" not in df.columns:
            raise ValueError(
                f"{season} is missing 'TeamAbbv'"
            )

        team_rosters[season] = {}

        teams = sorted(
            df["TeamAbbv"]
            .dropna()
            .unique()
        )

        for team in teams:

            team_rosters[season][team] = df[
                df["TeamAbbv"] == team
            ]
            
    return team_rosters

In [40]:
team_rosters = create_team_rosters(PerGameAvg)

# Step 10: Generate 9 Man Rotation

In [41]:
# Helper function that calculates TO%
# Formula:
#     TO% = 100 * TOV / (FGA + 0.44 * FTA + TOV)

# Required columns:
#     FGA - Field goal attempts
#     FTA - Free throw attempts
#     TO  - Turnovers

# Returns:
#     pandas.Series containing TO%
def calculate_team_to_pct(df):
    denominator = df["FGA"] + 0.44 * df["FTA"] + df["TO"]

    return 100 * df["TO"] / denominator

In [42]:
# Helper function that Calculates the percentage of total points scored in the paint.
# Formula:
#     %PTS PITP = (Points in Paint / Total Points) * 100
# Required columns:
#     Pts_Paint - Points scored in the paint
#     Pts       - Total points scored
# Returns:
#     pandas.Series containing %PTS PITP
def calculate_pct_points_in_paint(df):
    return (df["Pts_Paint"] / df["Pts"]) * 100

In [43]:
# Helper function that creates a ghost player
stat_columns = [
    "FGM",
    "FGA",
    "3PM",
    "FG3A",
    "FTM",
    "FTA",
    "OReb",
    "DReb",
    "REB",
    "Ast",
    "TO",
    "STL",
    "BLK",
    "BLKA",
    "PF",
    "PFD",
    "Pts",
    "NBA_FANTASY_PTS",
    "DD2",
    "TD3",
    "Pts_Paint",
    "Pts_MidRange",
    "Pts_3PT",
    "PLUS_MINUS",
    "PTSOFFTO",
    "2ndPTS",
    "FBPs",
    "PITP",
    "Opp PTSOFF TO",
    "Opp2nd PTS",
    "OppFBPs",
    "OppPITP"
]

In [44]:
# Helper function that gets the 9 man rotation of a team
def get_9_man_rotation(team_df):
    
    # Only available players
    available = team_df[
        team_df["RemainingGames"] > 0
    ].copy()

    print(f"Available players: {len(available)}")

    if available.empty:
        print("No available players.")
        return available

    available["Min"] = pd.to_numeric(
        available["Min"],
        errors="coerce"
    ).fillna(0)
    
    # Helper functions to identify positions
    def is_center(pos):
        return "C" in str(pos).upper()

    def is_guard(pos):
        return "G" in str(pos).upper()

    def is_forward(pos):
        return "F" in str(pos).upper()

    # Helper function that counts the number of players at each position
    def count_positions(df):

        centers = df["Pos"].apply(is_center).sum()
        guards = df["Pos"].apply(is_guard).sum()
        forwards = df["Pos"].apply(is_forward).sum()

        return centers, guards, forwards

    # Helper function that gets position minutes
    def position_minutes(df):

        center_minutes = df.loc[
            df["Pos"].apply(is_center),
            "Min"
        ].sum()

        guard_minutes = df.loc[
            df["Pos"].apply(is_guard),
            "Min"
        ].sum()

        forward_minutes = df.loc[
            df["Pos"].apply(is_forward),
            "Min"
        ].sum()

        return (
            center_minutes,
            guard_minutes,
            forward_minutes
        )

    # Ghost source players
    ghost_source = PerGameAvg["26_27"].copy()

    # Helper function to create ghost players
    def get_ghost_template(player_name):

        matches = ghost_source[
            ghost_source["PlayerName"]
            .astype(str)
            .str.contains(
                player_name,
                case=False,
                na=False
            )
        ]

        if matches.empty:
            raise ValueError(
                f"Could not find {player_name} "
                f"in PerGameAvg['26_27']"
            )

        return matches.iloc[0].copy()

    dario_template = get_ghost_template(
        "Dario Saric"
    )

    thanasis_template = get_ghost_template(
        "Thanasis Antetokounmpo"
    )

    lowry_template = get_ghost_template(
        "Kyle Lowry"
    )

    # Helper function to create ghost player
    def create_ghost_player(position, ghost_minutes):

        if position == "C":

            source = dario_template.copy()

        elif position == "F":

            source = thanasis_template.copy()

        elif position == "G":

            source = lowry_template.copy()

        else:

            raise ValueError(
                f"Unknown ghost position: {position}"
            )

        # Source minutes
        source_minutes = pd.to_numeric(
            source["Min"],
            errors="coerce"
        )

        if pd.isna(source_minutes) or source_minutes <= 0:

            raise ValueError(
                f"Invalid source minutes for "
                f"{source['PlayerName']}: "
                f"{source['Min']}"
            )

        ghost_minutes = float(
            ghost_minutes
        )

        # Minute scailing factor
        scale = (
            ghost_minutes /
            source_minutes
        )
        
        # Copy source player
        ghost = source.copy()

        # Identity 
        ghost_ids = {
            "C": -1001,
            "F": -1002,
            "G": -1003
        }

        ghost["PlayerID"] = ghost_ids[position]
        ghost["PlayerName"] = "Jon Snow"

        # Team
        ghost["TeamID"] = (
            team_df["TeamID"].iloc[0]
        )

        ghost["TeamAbbv"] = (
            team_df["TeamAbbv"].iloc[0]
        )

        # Position
        ghost["Pos"] = position

        # Availability
        ghost["GP"] = 0
        ghost["RemainingGames"] = 1

        # Minutes
        ghost["Min"] = ghost_minutes

        # Scale minute depending features
        for stat in stat_columns:

            if stat not in ghost.index:
                continue

            value = pd.to_numeric(
                ghost[stat],
                errors="coerce"
            )

            if pd.notna(value):

                ghost[stat] = (
                    value * scale
                )

        return ghost
    
    # Helper function that adds a ghost player for position
    def add_ghost_for_position(rotation, position):

        (
            center_minutes,
            guard_minutes,
            forward_minutes
        ) = position_minutes(rotation)
        
        # Determine position minute defecits
        if position == "C":

            minutes_needed = max(
                0,
                48.0 - center_minutes
            )

        elif position == "G":

            minutes_needed = max(
                0,
                48.0 - guard_minutes
            )

        elif position == "F":

            minutes_needed = max(
                0,
                48.0 - forward_minutes
            )

        else:

            raise ValueError(
                f"Invalid position: {position}"
            )

        # If no defecit, give small minimum
        if minutes_needed <= 0:

            minutes_needed = 1.0

        # Create ghost
        ghost = create_ghost_player(
            position,
            minutes_needed
        )

        # Find player to remove
        candidates = rotation.copy()

        if position == "C":

            non_centers = candidates[
                ~candidates["Pos"].apply(
                    is_center
                )
            ]

            if not non_centers.empty:

                candidates = non_centers

        elif position == "G":

            non_guards = candidates[
                ~candidates["Pos"].apply(
                    is_guard
                )
            ]

            if not non_guards.empty:

                candidates = non_guards

        elif position == "F":

            non_forwards = candidates[
                ~candidates["Pos"].apply(
                    is_forward
                )
            ]

            if not non_forwards.empty:

                candidates = non_forwards

        # Remove lowest minute expendable players
        remove_idx = candidates[
            "Min"
        ].idxmin()

        removed_name = rotation.loc[
            remove_idx,
            "PlayerName"
        ]

        removed_min = rotation.loc[
            remove_idx,
            "Min"
        ]

        print(
            f"  -> Replacing {removed_name} "
            f"({removed_min:.2f} min) "
            f"with Jon Snow ({position}) "
            f"({minutes_needed:.2f} min)"
        )

        rotation = rotation.drop(
            remove_idx
        )

        rotation = pd.concat(
            [
                rotation,
                ghost.to_frame().T
            ],
            ignore_index=True
        )

        return rotation

    # Sort real player by minutes
    available = available.sort_values(
        "Min",
        ascending=False
    ).reset_index(drop=True)

    # Start wit the top 9 real players
    rotation = available.head(9).copy()

    # Helper function that returns the available real players that arent already in the rotation
    def get_unused_real_players(rotation):

        used_ids = set(rotation["PlayerID"])

        return available[
            ~available["PlayerID"].isin(used_ids)
        ].copy()

# Helper function that returns the highest minute available REAL PLAYER who can play the requiested
#     position and is not already in the rotation, returns non if no real player exists
    def find_real_player_for_position(rotation, position):

        unused = get_unused_real_players(rotation)

        if position == "C":
            candidates = unused[
                unused["Pos"].apply(is_center)
            ]

        elif position == "G":
            candidates = unused[
                unused["Pos"].apply(is_guard)
            ]

        elif position == "F":
            candidates = unused[
                unused["Pos"].apply(is_forward)
            ]

        else:
            raise ValueError(
                f"Invalid position: {position}"
            )

        if candidates.empty:
            return None

        return candidates.sort_values(
            "Min",
            ascending=False
        ).iloc[0]

# Helper function that adds a real player to the rotation
    def add_real_player(rotation, player):
        return pd.concat(
            [
                rotation,
                player.to_frame().T
            ],
            ignore_index=True
        )
    
    # Position requirements
    # We want:
    #     C >= 2
    #     G >= 1
    #     F >= 1
    #
    # But we NEVER create a ghost if a real available
    # roster player can fill the position.
    required_positions = [
        ("C", 2),
        ("G", 1),
        ("F", 1)
    ]

    # Fix position requirements using real players first
    for position, required_count in required_positions:

        current_count = (
            rotation["Pos"]
            .apply(
                {
                    "C": is_center,
                    "G": is_guard,
                    "F": is_forward
                }[position]
            )
            .sum()
        )

        while current_count < required_count:

            # Look for a real available player first
            real_player = find_real_player_for_position(
                rotation,
                position
            )

            if real_player is not None:

                print(
                    f"  -> Adding real player "
                    f"{real_player['PlayerName']} "
                    f"({real_player['Pos']}, "
                    f"{real_player['Min']:.2f} min) "
                    f"to fill {position}"
                )

                # If rotation already has 9 players, remove
                # the lowest-minute player who does NOT play
                # the required position.
                if len(rotation) >= 9:

                    if position == "C":
                        removable = rotation[
                            ~rotation["Pos"].apply(is_center)
                        ]

                    elif position == "G":
                        removable = rotation[
                            ~rotation["Pos"].apply(is_guard)
                        ]

                    else:  # F
                        removable = rotation[
                            ~rotation["Pos"].apply(is_forward)
                        ]

                    if removable.empty:
                        removable = rotation

                    remove_idx = removable["Min"].idxmin()

                    removed_name = rotation.loc[
                        remove_idx,
                        "PlayerName"
                    ]

                    print(
                        f"     Removing {removed_name} "
                        f"to make room."
                    )

                    rotation = rotation.drop(
                        remove_idx
                    ).reset_index(drop=True)

                rotation = add_real_player(
                    rotation,
                    real_player
                )

            else:
                # If no real players exist create fake player Jon Snow
                print(
                    f"  -> No available real {position} "
                    f"player exists."
                )

                # Calculate current minutes at position
                if position == "C":
                    current_minutes = rotation.loc[
                        rotation["Pos"].apply(is_center),
                        "Min"
                    ].sum()

                elif position == "G":
                    current_minutes = rotation.loc[
                        rotation["Pos"].apply(is_guard),
                        "Min"
                    ].sum()

                else:
                    current_minutes = rotation.loc[
                        rotation["Pos"].apply(is_forward),
                        "Min"
                    ].sum()

                minutes_needed = max(
                    1.0,
                    48.0 - current_minutes
                )

                ghost = create_ghost_player(
                    position,
                    minutes_needed
                )

                print(
                    f"     -> Creating Jon Snow "
                    f"({position}, "
                    f"{minutes_needed:.2f} min)"
                )

                rotation = pd.concat(
                    [
                        rotation,
                        ghost.to_frame().T
                    ],
                    ignore_index=True
                )

            current_count = (
                rotation["Pos"]
                .apply(
                    {
                        "C": is_center,
                        "G": is_guard,
                        "F": is_forward
                    }[position]
                )
                .sum()
            )

    # Make sure we have 9 players
    # If we have fewer than 9, fill with REAL AVAILABLE
    # players first.
    #
    # Ghosts are only used if there are literally no more
    # real available players.
    while len(rotation) < 9:

        real_players = get_unused_real_players(rotation)

        if not real_players.empty:

            player = real_players.sort_values(
                "Min",
                ascending=False
            ).iloc[0]

            print(
                f"  -> Adding real player "
                f"{player['PlayerName']} "
                f"({player['Pos']}, "
                f"{player['Min']:.2f} min)"
            )

            rotation = add_real_player(
                rotation,
                player
            )

        else:

            # Absolute last resort if there are no real players left
            print(
                "  -> No unused real players remain. "
                "Creating Jon Snow."
            )

            # Determine the position that is currently
            # most deficient in minutes.

            center_minutes, guard_minutes, forward_minutes = (
                position_minutes(rotation)
            )

            deficits = {
                "C": max(0, 48.0 - center_minutes),
                "G": max(0, 48.0 - guard_minutes),
                "F": max(0, 48.0 - forward_minutes)
            }

            position = max(
                deficits,
                key=deficits.get
            )

            minutes_needed = max(
                1.0,
                deficits[position]
            )

            ghost = create_ghost_player(
                position,
                minutes_needed
            )

            rotation = pd.concat(
                [
                    rotation,
                    ghost.to_frame().T
                ],
                ignore_index=True
            )

    # Final Sort
    rotation["Min"] = pd.to_numeric(
        rotation["Min"],
        errors="coerce"
    ).fillna(0)

    rotation = rotation.sort_values(
        "Min",
        ascending=False
    ).reset_index(drop=True)

    # Assign starter / bench players
    rotation["Rotation_Role"] = [
        "Starter" if i < 5
        else "Bench"
        for i in range(len(rotation))
    ]

    # Final position counts
    centers, guards, forwards = count_positions(
        rotation
    )

    (
        center_minutes,
        guard_minutes,
        forward_minutes
    ) = position_minutes(rotation)

    # Final print
    return rotation

In [45]:
# Manual rotation fixes to player
stat_columns = [
    "FGM",
    "FGA",
    "3PM",
    "FG3A",
    "FTM",
    "FTA",
    "OReb",
    "DReb",
    "REB",
    "Ast",
    "TO",
    "STL",
    "BLK",
    "BLKA",
    "PF",
    "PFD",
    "Pts",
    "NBA_FANTASY_PTS",
    "DD2",
    "TD3",
    "Pts_Paint",
    "Pts_MidRange",
    "Pts_3PT",
    "PLUS_MINUS",
    "PTSOFFTO",
    "2ndPTS",
    "FBPs",
    "PITP",
    "Opp PTSOFF TO",
    "Opp2nd PTS",
    "OppFBPs",
    "OppPITP"
]

# Helper function that normalizes one player's minutes + stats
def normalize_player_downward(
    player_row,
    target_minutes=None,
    target_gp=None
):

    player = player_row.copy()
    
    # Override minutes
    if target_minutes is not None:

        original_minutes = pd.to_numeric(
            player["Min"],
            errors="coerce"
        )

        if pd.isna(original_minutes) or original_minutes <= 0:

            print(
                f"WARNING: Invalid original minutes for "
                f"{player['PlayerName']}"
            )

            return player

        target_minutes = float(target_minutes)

        # Scailing factor
        scale = (
            target_minutes /
            original_minutes
        )

        # Minutes
        player["Min"] = target_minutes

        # Scale stats
        for stat in stat_columns:

            if stat not in player.index:
                continue

            value = pd.to_numeric(
                player[stat],
                errors="coerce"
            )

            if pd.notna(value):

                player[stat] = (
                    value * scale
                )

    # Override GP 
    if target_gp is not None:

        player["GP"] = target_gp

        player["RemainingGames"] = target_gp

    return player


# Helper funciton that applies manual fixes to Specific Teams
# Rules:
# - minutes only:
#     Changes minutes and scales stats.
# - gp only:
#     Changes GP + RemainingGames.
#     Does NOT change minutes or stats.
# - minutes + gp:
#     Changes both.
# - No players are removed.
# - Only the specified team is searched.
# - Only the specified player is modified.
def apply_manual_rotation_fixes(team_rosters, season, fixes):

    # Loop through teams
    for team, player_fixes in fixes.items():

        # Check team exists
        if team not in team_rosters[season]:

            print(
                f"\nWARNING: {team} not found "
                f"in {season}"
            )

            continue

        roster = team_rosters[season][team]

        # Loop through players
        for player_name, settings in player_fixes.items():

            # Get optional seetings
            target_minutes = settings.get(
                "minutes",
                None
            )

            target_gp = settings.get(
                "gp",
                None
            )

            # Find player in the team
            matches = roster[
                roster["PlayerName"]
                .astype(str)
                .str.strip()
                .str.lower()
                ==
                player_name.strip().lower()
            ]

            if matches.empty:

                print(
                    f"\nWARNING: {player_name} "
                    f"not found on {team}"
                )

                continue

            # Get exact row

            idx = matches.index[0]

            # Before values
            old_min = pd.to_numeric(
                roster.loc[idx, "Min"],
                errors="coerce"
            )

            old_gp = pd.to_numeric(
                roster.loc[idx, "GP"],
                errors="coerce"
            )

            old_remaining = pd.to_numeric(
                roster.loc[
                    idx,
                    "RemainingGames"
                ],
                errors="coerce"
            )

            # Normalize
            normalized = normalize_player_downward(
                roster.loc[idx],
                target_minutes=target_minutes,
                target_gp=target_gp
            )

            # Write back to same row
            for column in roster.columns:
                roster.loc[idx, column] = normalized[column]
    return team_rosters

In [46]:
# Manual fixes done
manual_fixes = {

    "POR": {
        "Ja Morant": {
            "minutes": 25,
            "gp": 30
        },
        "Shaedon Sharpe": {
            "minutes": 26,
            "gp": 50
        },
        "Damian Lillard": {
            "minutes": 30,
            "gp": 40
        },
        "Deni Avdija": {
            "minutes": 30,
            "gp": 40
        },
        "Toumani Camara": {
            "minutes": 27,
            "gp": 60
        },
        "Yang Hansen": {
            "minutes": 14
        },
        "Scoot Henderson": {
            "minutes": 17,
            "gp": 60
        }
    },

    "SAC": {
        "Darius Acuff Jr.": {
            "minutes": 28,
            "gp": 50
        },
        "Zach Lavine": {
            "minutes": 28,
            "gp": 30
        },
        "Domantas Sabonis": {
            "minutes": 28,
            "gp": 30
        },
        "Keegan Murray": {
            "minutes": 28,
            "gp": 30
        }
    },

    "ATL": {
        "Luguentz Dort": {
            "minutes": 28
        },
        "Dyson Daniels": {
            "minutes": 29
        },
        "Kingston Fleming": {
            "minutes": 22
        }
    },

    "BKN": {
        "Egor Dëmin": {
            "minutes": 30,
            "gp": 60
        }
    },


    "CHI": {
        "Josh Giddey": {
            "gp": 60
        },
        "Norman Powell": {
            "gp": 65
        },
    },

    "BOS": {
        "Mitchell Robinson": {
            "minutes": 25
        },
        "Jayson Tatum": {
            "gp": 60
        },
        "Paul George 65": {
            "gp": 60
        }
    },

    "CHA": {
        "Coby White": {
            "minutes": 28
        },
        "Bez Mbeng": {
            "minutes": 20,
            "gp": 40
        },

        "Grayson Allen": {
            "minutes": 22,
            "gp": 40
        },

        "Royce O'Neale	": {
            "minutes": 21,
            "gp": 40
        }
    },

    "CLE": {
        "Peyton Watson": {
            "gp": 61
        }
    },

    "DAL": {
        "Kyrie Irving": {
            "minutes": 33,
            "gp": 65
        },
        "Zaccharie Risacher": {
            "minutes": 25,
            "gp": 62
        },
        "Daniel Gafford": {
            "minutes": 25,
            "gp": 62
        },
        "Dereck Lively II": {
            "minutes": 25,
            "gp": 57
        },
        "Naji Marshall	": {
            "minutes": 26,
            "gp": 57
        },
        "Max Christie": {
            "minutes": 25,
            "gp": 57
        },
        "Santi Aldama": {
            "minutes": 22,
            "gp": 57
        }
    },

    "DEN": {
        "Nikola Jokić": {
            "gp": 71
        },
        "Aaron Gordon": {
            "minutes": 29,
            "gp": 64
        },
        "Cameron Johnson": {
            "gp": 59
        },
        "Lonnie Walker IV": {
            "gp": 49
        },
        "Spencer Jones": {
            "minutes": 24
        },
        "Julian Strawther": {
            "minutes": 22
        }
    },

    "DET": {
        "Cade Cunningham": {
            "gp": 75
        },
        "Taurean Prince": {
            "gp": 63
        },
        "Isaiah Joe": {
            "minutes": 23
        },
        "Ronald Holland II": {
            "minutes": 25
        },
        "Paul Reed": {
            "minutes": 25
        }
    },

    "GSW": {
        "Stephen Curry": {
            "minutes": 28,
            "gp": 55
        },
        "Moses Moody": {
            "gp": 0
        },
        "Jimmy Butler II": {
            "gp": 0
        },
        "Kristaps Porziņģis": {
            "gp": 45
        },
        "De'Anthony Melton": {
            "gp": 35
        },
        "Brandon Williams": {
            "minutes": 26,
            "gp": 50
        },
        "Al Horford": {
            "gp": 40
        },
        "Yaxel Lendeborg": {
            "minutes": 25,
            "gp": 40
        },
        "Georges Niang": {
            "gp": 0,
            "minutes": 0
        }

    },


    "IND": {
        "Pascal Siakam": {
            "gp": 73
        },
        "Kelly Oubre Jr.": {
            "gp": 64
        },
        "Andrew Nembhard": {
            "gp": 64
        },
        "Ivica Zubac": {
            "gp": 68
        },
        "Aaron Nesmith": {
            "gp": 65
        },
        "Johnny Furphy": {
            "gp": 40
        },
        "Obi Toppin": {
            "gp": 40
        },
    },
    
    "LAC": {
        "Darius Garland": {
            "gp": 71
        },
        "Max Strus": {
            "gp": 75
        },
        "Bradley Beal": {
            "minutes": 28,
            "gp": 65
        }
    },

    "LAL": {
        "Luka Dončić": {
            "gp": 60
        },
        "Austin Reaves": {
            "gp": 60
        },
        "Walker Kessler": {
            "gp": 55
        },
        "Matisse Thybulle": {
            "gp": 657
        },
        "Kevon Looney": {
            "minutes": 20,
            "gp": 40
        }
    },

    "MEM": {
        "Cameron Boozer": {
            "minutes": 28,
            "gp": 60
        },
        "Jerami Grant": {
            "gp": 71
        },
        "Cedric Coward": {
            "minutes": 30,
            "gp": 65
        },
        "Ty Jerome": {
            "gp": 50
        }
    },

    "MIA": {
        "Giannis Antetokounmpo": {
            "minutes": 33,
            "gp": 70
        }
    },

    "MIL": {
        "Kevin Porter Jr.": {
            "gp": 65
        },
        "Kel'el Ware": {
            "minutes": 25
        }
    },

    "MIN": {
        "LaMelo Ball": {
            "minutes": 33,
            "gp": 75
        },
    
        "Terrence Shannon Jr": {
            "gp": 65
        },
        "Jonathan Kuminga": {
            "minutes": 30,
            "gp": 70
        },
        "Donte DiVincenzo": {
            "minutes": 30,
            "gp": 5
        },
        "Bones Hyland": {
            "minutes": 21,
        },
        "Trey Lyles": {
            "gp": 0
        },
        "Rocco Zikarsky": {
            "gp": 30,
            "minutes": 12,
        }
    },

    "NOP": {
        "Trey Murphy III": {
            "gp": 65
        },
        "Zion Williamson": {
            "gp": 60
        },
        "Bennedict Mathurin": {
            "gp": 55
        },
        "Jordan Poole": {
            "gp": 55
        },
        "Miles McBride": {
            "gp": 65
        },
        "Landry Shamet": {
            "gp": 65
        },
        "Saddiq Bey": {
            "gp": 65
        }
    },

    "HOU": {
        "Steven Adams": {
            "gp": 60
        },
        "Bogdan Bogdanović": {
            "gp": 50
        },
    },

    "OKC": {
        "Shai Gilgeous-Alexander": {
            "gp": 72
        },
        "Jalen Williams": {
            "gp": 70
        },
        "Isaiah Hartenstein": {
            "gp": 65
        },
        "Ajay Mitchell": {
            "gp": 65
        },
        "Chet Holmgren": {
            "gp": 71
        },
        "Alex Caruso": {
            "minutes": 22,
            "gp": 65
        },
        "Jared McCain": {
            "minutes": 25,
            "gp": 66
        },
        "Kenrich Williams": {
            "gp": 65
        },
        "Aday Mara": {
            "gp": 65
        },
        "Jaylin Williams": {
            "minutes": 24
        }
    },

    "ORL": {
        "Franz Wagner": {
            "gp": 65
        },
        "Nikola Vučević": {
            "gp": 65
        },
        "Jalen Suggs": {
            "gp": 69
        },
        "Goga Bitadze": {
            "gp": 65
        },
    },

    "PHI": {
        "Joel Embiid": {
            "gp": 65
        },
        "Anfernee Simons": {
            "gp": 60
        }
    },

    "PHX": {
        "Devin Booker": {
            "gp": 75
        },
        "Dillon Brooks": {
            "gp": 65
        },
        "Jalen Green": {
            "gp": 65
        },
        "Mark Williams": {
            "minutes": 28,
            "gp": 65
        },

        "Khaman Maluach": {
            "minutes": 28,
            "gp": 65
        }
    },

    "SAS": {
        "Dylan Harper": {
            "minutes": 28,
            "gp": 65
        },
        "Victor Wembanyama": {
            "minutes": 32,
            "gp": 65
        },
        "De’Aaron Fox": {
            "minutes": 26
        }
    },

    "TOR": {
        "Collin Murray-Boyles": {
            "minutes": 28,
            "gp": 75
        },
        "Allen Graves": {
            "minutes": 17,
            "gp": 55
        },
        "Jakob Poeltl": {
            "gp":70
        },
        "Kawhi Leonard": {
            "gp": 72
        },
        "RJ Barrett": {
            "gp": 66
        }
    },

    "UTA": {
        "Lauri Markkanen": {
            "gp": 65
        },
        "Keyonte George": {
            "gp": 65
        },
        "Darryn Peterson": {
            "minutes": 28,
            "gp": 65
        },
        "Jaren Jackson Jr.": {
            "minutes": 31
        },
        "Hayden Gray": {
            "gp": 40
        },
        "Josh Okogie": {
            "minutes": 25
        },
        "Mo Bamba": {
            "minutes": 20,
            "gp": 50
        }
    },

    "WAS": {
        "AJ Dybantsa": {
            "gp": 50
        },
        "Trae Young": {
            "minutes": 28,
            "gp": 45

        },
        "Anthony Davis": {
            "minutes": 28,
            "gp": 45
        },
        "Bub Carrington": {
            "gp": 50
        }
    }
}

In [47]:
team_rosters = apply_manual_rotation_fixes(
    team_rosters,
    season="26_27",
    fixes=manual_fixes
)

WARNING: Kingston Fleming not found on ATL

WARNING: Paul George 65 not found on BOS

WARNING: Jimmy Butler II not found on GSW

WARNING: Miles McBride not found on NOP

WARNING: Landry Shamet not found on NOP

WARNING: De’Aaron Fox not found on SAS

In [48]:
# Helper function that normalizes minutes and stats for a 9-man rotation of a team to 240 minutes.
# Rules:
#     - Convert Min to numeric values.
#     - Calculate the current total minutes for the 9-man rotation.
#     - Scale each player's minutes proportionally so the total equals 240.
#     - Preserve the relative distribution of minutes between players.
# Returns: The normalized rotation as a copy of the original DataFrame.
def normalize_rotation(rotation):
    rotation = rotation.copy()

    rotation["Min"] = pd.to_numeric(
        rotation["Min"],
        errors="coerce"
    ).fillna(0)

    # Preserve original minutes
    rotation["OriginalMin"] = rotation["Min"]

    total_minutes = rotation["Min"].sum()

    if total_minutes <= 0:
        return rotation

    # Scale minutes
    rotation["Min"] = (
        rotation["Min"] / total_minutes
    ) * 240

    # Scale per-game stats to the new minutes
    stat_columns = [
        'Ast',
        'DReb',
        '3PM',
        'FTM',
        'PTSOFFTO',
        'Pts_Paint', 'Pts_MidRange', 'Pts_3PT'
    ]
    for stat in stat_columns:
        rotation[stat] = (
            rotation[stat] *
            rotation["Min"] /
            rotation["OriginalMin"]
        )

    return rotation

In [49]:
# Helper fucntion that subtracts 1 from GP for every player in the 9-man rotation.
# team_df: Mutable team roster.
# rotation:Current 9-man rotation.
def subtract_games_Played(team_df, rotation):
    player_ids = rotation["PlayerID"]
    mask = team_df["PlayerID"].isin(player_ids)
    team_df.loc[mask, "RemainingGames"] -= 1
    return team_df

Debugging (Prints the total roster metrics and rotation information)

In [50]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

columns_to_display = [
    "PlayerName",
    "Pos",
    "TeamAbbv",
    "GP",
    "Min",
    "Ast",
    "BLK",
    "DReb",
    "FTM",
    "3PM",
    "PTSOFFTO",
    "Pts_Paint"
]

season = "26_27"

for team in sorted(team_rosters[season].keys()):

    # Prints the full roster df
    print(f"{team} Roster")

    roster = team_rosters[season][team].copy()

    roster["Min"] = pd.to_numeric(
        roster["Min"],
        errors="coerce"
    )

    display(
        roster
        .sort_values("Min", ascending=False)[
            columns_to_display
        ]
    )

    # Get 9 man rotation
    rotation = get_9_man_rotation(
        team_rosters[season][team]
    )

    rotation["Min"] = pd.to_numeric(
        rotation["Min"],
        errors="coerce"
    ).fillna(0)

    # 9 man rotation df
    print(f"\n{team} 9-man rotation")

    display(
        rotation
        .sort_values("Min", ascending=False)[
            columns_to_display
        ]
    )

    # Primary positions
    rotation["PrimaryPos"] = (
        rotation["Pos"]
        .fillna("")
        .astype(str)
        .str.upper()
        .str.split("-")
        .str[0]
        .str.strip()
    )
    
    # Split by primary positions
    guards = rotation[
        rotation["PrimaryPos"] == "G"
    ].sort_values(
        "Min",
        ascending=False
    )

    forwards = rotation[
        rotation["PrimaryPos"] == "F"
    ].sort_values(
        "Min",
        ascending=False
    )

    centers = rotation[
        rotation["PrimaryPos"] == "C"
    ].sort_values(
        "Min",
        ascending=False
    )

    # Minute totals
    guard_minutes = guards["Min"].sum()
    forward_minutes = forwards["Min"].sum()
    center_minutes = centers["Min"].sum()

    total_minutes = rotation["Min"].sum()

    position_total = (
        guard_minutes
        + forward_minutes
        + center_minutes
    )

    unassigned_minutes = (
        total_minutes
        - position_total
    )

    # Exact rotation print format
    print(f"\n{team} 9 man rotation")

    # Guards
    print("\nGuards")

    for _, player in guards.iterrows():

        print(
            f"{player['PlayerName']:<25} "
            f"{player['Min']:>5.1f} min  "
            f"({player['Pos']})"
        )

    print(
        f"Guard total: "
        f"{guard_minutes:.1f} minutes"
    )

    # Forwards
    print("\nForwards")

    for _, player in forwards.iterrows():

        print(
            f"{player['PlayerName']:<25} "
            f"{player['Min']:>5.1f} min  "
            f"({player['Pos']})"
        )

    print(
        f"Forward total: "
        f"{forward_minutes:.1f} minutes"
    )

    # Centers
    print("\nCenters")

    for _, player in centers.iterrows():

        print(
            f"{player['PlayerName']:<25} "
            f"{player['Min']:>5.1f} min  "
            f"({player['Pos']})"
        )

    print(
        f"Center total: "
        f"{center_minutes:.1f} minutes"
    )

    # Totals
    print(
        f"Total rotation minutes: {total_minutes:.1f}"
    )

    print(
        f"Position total:         {position_total:.1f}"
    )

    print(
        f"Unassigned minutes:     {unassigned_minutes:.1f}"
    )

ATL Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
231,Jalen Johnson,F,ATL,72.000000,35.161088,7.861111,0.430556,8.875000,4.180556,1.666667,4.100000,11.611111
422,Nickeil Alexander-Walker,G,ATL,78.000000,33.374060,3.666667,0.538462,2.769231,3.551282,3.217949,3.700000,6.435897
442,Onyeka Okongwu,F-C,ATL,74.000000,31.040113,3.121622,1.067568,5.702703,2.067568,1.945946,2.100000,7.189189
69,CJ McCollum,G,ATL,76.000000,29.781206,3.855263,0.460526,2.500000,2.407895,2.513158,2.700000,6.210526
167,Dyson Daniels,G,ATL,76.000000,29.000000,5.168007,0.356811,3.867373,0.863253,0.253221,1.749526,8.586488
367,Luguentz Dort,G,ATL,69.000000,28.000000,1.287362,0.408927,2.862488,0.666399,1.938616,1.463049,1.847743
273,Jock Landale,C,ATL,68.000000,22.148186,1.691176,0.529412,3.000000,1.176471,1.088235,1.400000,5.882353
6,Aaron Wiggins,G,ATL,65.000000,21.753538,1.676923,0.430769,2.430769,0.815385,1.476923,2.000000,3.876923
484,Ryan Nembhard,G,ATL,60.000000,19.514667,5.266667,0.033333,2.000000,0.416667,0.800000,1.000000,2.400000
621,Kingston Flemings,G,ATL,2.657178,19.406816,3.832737,0.109483,1.340224,0.816844,1.290178,1.010489,1.975077
107,Corey Kispert,F,ATL,58.000000,18.613908,1.586207,0.155172,1.810345,1.327586,1.500000,1.800000,3.310345
328,Keshon Gilbert,G,ATL,4.000000,18.445833,3.000000,1.000000,0.750000,1.750000,0.000000,0.500000,2.000000
178,Gabe Vincent,G,ATL,53.000000,16.586384,1.433962,0.056604,0.698113,0.377358,1.113208,0.400000,0.490566
67,Buddy Hield,G,ATL,51.000000,16.064150,1.392157,0.176471,1.745098,0.588235,1.450980,1.700000,2.392157
237,Jalen Wilson,F,ATL,54.000000,15.911512,0.925926,0.037037,1.796296,1.277778,1.000000,0.900000,1.888889
408,Mouhamed Gueye,F,ATL,77.000000,15.309567,0.896104,0.506494,2.415584,0.519481,0.519481,0.900000,2.259740
469,RayJ Dennis,G,ATL,17.000000,12.131373,1.941176,0.235294,1.058824,0.470588,0.823529,0.900000,1.294118
645,Zuby Ejiofor,C-F,ATL,4.097841,11.727354,0.805555,0.415739,2.079255,0.741494,0.116970,0.780056,2.578624
34,Asa Newell,F,ATL,44.000000,11.361553,0.590909,0.340909,1.181818,0.363636,0.659091,1.500000,2.818182
524,Tony Bradley,C-F,ATL,41.000000,10.992358,0.536585,0.170732,1.365854,0.780488,0.048780,0.400000,2.829268
317,Keaton Wallace,G,ATL,53.000000,10.113019,1.773585,0.094340,1.000000,0.226415,0.716981,0.400000,0.905660
640,Henri Veesaar,C-F,ATL,2.717323,9.508652,0.583475,0.363811,2.297655,0.540242,0.425446,0.363615,2.370391
599,William Baker,NaN,ATL,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 22

ATL 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Jalen Johnson,F,ATL,72.0,35.161088,7.861111,0.430556,8.875000,4.180556,1.666667,4.100000,11.611111
1,Nickeil Alexander-Walker,G,ATL,78.0,33.374060,3.666667,0.538462,2.769231,3.551282,3.217949,3.700000,6.435897
2,Onyeka Okongwu,F-C,ATL,74.0,31.040113,3.121622,1.067568,5.702703,2.067568,1.945946,2.100000,7.189189
3,CJ McCollum,G,ATL,76.0,29.781206,3.855263,0.460526,2.500000,2.407895,2.513158,2.700000,6.210526
4,Dyson Daniels,G,ATL,76.0,29.000000,5.168007,0.356811,3.867373,0.863253,0.253221,1.749526,8.586488
5,Luguentz Dort,G,ATL,69.0,28.000000,1.287362,0.408927,2.862488,0.666399,1.938616,1.463049,1.847743
6,Jock Landale,C,ATL,68.0,22.148186,1.691176,0.529412,3.000000,1.176471,1.088235,1.400000,5.882353
7,Aaron Wiggins,G,ATL,65.0,21.753538,1.676923,0.430769,2.430769,0.815385,1.476923,2.000000,3.876923
8,Ryan Nembhard,G,ATL,60.0,19.514667,5.266667,0.033333,2.000000,0.416667,0.800000,1.000000,2.400000

ATL 9 man rotation

Guards
Nickeil Alexander-Walker   33.4 min  (G)
CJ McCollum                29.8 min  (G)
Dyson Daniels              29.0 min  (G)
Luguentz Dort              28.0 min  (G)
Aaron Wiggins              21.8 min  (G)
Ryan Nembhard              19.5 min  (G)
Guard total: 161.4 minutes

Forwards
Jalen Johnson              35.2 min  (F)
Onyeka Okongwu             31.0 min  (F-C)
Forward total: 66.2 minutes

Centers
Jock Landale               22.1 min  (C)
Center total: 22.1 minutes
Total rotation minutes: 249.8
Position total:         249.8
Unassigned minutes:     0.0
BKN Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
306,Julius Randle,F-C,BKN,79.000000,33.041730,5.037975,0.227848,5.063291,5.037975,1.379747,2.800000,10.202532
395,Michael Porter Jr.,F,BKN,52.000000,32.473141,3.038462,0.250000,5.730769,3.750000,3.384615,3.500000,8.307692
169,Egor Dëmin,G,BKN,60.000000,30.000000,3.967258,0.389846,3.302226,1.238335,2.843584,1.311718,2.155620
431,Noah Clowney,F-C,BKN,66.000000,26.970657,1.636364,0.681818,3.348485,2.727273,1.954545,1.700000,3.424242
515,Terance Mann,G-F,BKN,63.000000,24.270106,3.015873,0.238095,2.063492,1.000000,0.888889,1.000000,3.142857
433,Nolan Traore,G,BKN,56.000000,22.203423,3.803571,0.410714,1.517857,1.321429,1.089286,1.100000,4.035714
156,Drake Powell,G-F,BKN,63.000000,20.944656,1.444444,0.222222,1.428571,1.095238,0.809524,1.000000,2.317460
120,Danny Wolf,F,BKN,57.000000,20.827398,2.228070,0.561404,3.929825,1.473684,1.192982,1.400000,3.789474
40,Ben Saraf,G,BKN,44.000000,20.825417,3.295455,0.181818,1.636364,1.659091,0.431818,1.400000,4.590909
326,Keon Ellis,G,BKN,72.000000,20.536644,1.000000,0.638889,1.347222,0.708333,1.263889,1.600000,2.027778
84,Chaney Johnson,G-F,BKN,17.000000,20.446078,2.117647,0.529412,2.705882,1.647059,0.529412,1.600000,4.352941
602,Mikel Brown Jr.,G,BKN,5.881489,19.496050,3.954828,0.102941,1.355249,1.021409,1.154396,1.160771,2.400925
128,Day'Ron Sharpe,C,BKN,62.000000,18.708306,2.338710,0.419355,3.903226,1.661290,0.145161,1.400000,6.612903
298,Josh Minott,F,BKN,49.000000,17.014932,0.938776,0.489796,2.244898,0.979592,1.306122,1.300000,2.530612
625,Joshua Jefferson,F,BKN,6.916379,14.111206,1.633141,0.137146,1.538885,0.683725,0.277076,0.631075,1.626298
405,Moritz Wagner,F-C,BKN,36.000000,11.849861,0.750000,0.055556,2.444444,1.638889,0.611111,0.800000,3.333333
601,Tyler Bilodeau,F-C,BKN,1.970750,10.776304,0.848124,0.074380,1.043878,0.503907,1.151211,0.787883,1.054815
187,Grant Nelson,F,BKN,4.000000,8.752500,1.250000,1.250000,1.250000,1.750000,0.000000,1.800000,2.500000

Available players: 18

BKN 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Julius Randle,F-C,BKN,79.0,33.041730,5.037975,0.227848,5.063291,5.037975,1.379747,2.800000,10.202532
1,Michael Porter Jr.,F,BKN,52.0,32.473141,3.038462,0.250000,5.730769,3.750000,3.384615,3.500000,8.307692
2,Egor Dëmin,G,BKN,60.0,30.000000,3.967258,0.389846,3.302226,1.238335,2.843584,1.311718,2.155620
3,Noah Clowney,F-C,BKN,66.0,26.970657,1.636364,0.681818,3.348485,2.727273,1.954545,1.700000,3.424242
4,Terance Mann,G-F,BKN,63.0,24.270106,3.015873,0.238095,2.063492,1.000000,0.888889,1.000000,3.142857
5,Nolan Traore,G,BKN,56.0,22.203423,3.803571,0.410714,1.517857,1.321429,1.089286,1.100000,4.035714
6,Drake Powell,G-F,BKN,63.0,20.944656,1.444444,0.222222,1.428571,1.095238,0.809524,1.000000,2.317460
7,Danny Wolf,F,BKN,57.0,20.827398,2.228070,0.561404,3.929825,1.473684,1.192982,1.400000,3.789474
8,Ben Saraf,G,BKN,44.0,20.825417,3.295455,0.181818,1.636364,1.659091,0.431818,1.400000,4.590909

BKN 9 man rotation

Guards
Egor Dëmin                 30.0 min  (G)
Terance Mann               24.3 min  (G-F)
Nolan Traore               22.2 min  (G)
Drake Powell               20.9 min  (G-F)
Ben Saraf                  20.8 min  (G)
Guard total: 118.2 minutes

Forwards
Julius Randle              33.0 min  (F-C)
Michael Porter Jr.         32.5 min  (F)
Noah Clowney               27.0 min  (F-C)
Danny Wolf                 20.8 min  (F)
Forward total: 113.3 minutes

Centers
Center total: 0.0 minutes
Total rotation minutes: 231.6
Position total:         231.6
Unassigned minutes:     0.0
BOS Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
143,Derrick White,G,BOS,77.000000,34.090346,5.376623,1.272727,3.285714,2.389610,2.714286,2.100000,4.207792
262,Jayson Tatum,F-G,BOS,60.000000,32.615625,5.312500,0.187500,9.500000,4.062500,2.937500,2.800000,7.250000
458,Payton Pritchard,G,BOS,79.000000,32.348397,5.164557,0.126582,3.075949,1.531646,2.683544,1.900000,5.898734
456,Paul George,F,BOS,37.000000,30.676532,3.594595,0.432432,4.756757,2.459459,2.702703,2.300000,3.783784
418,Neemias Queta,C,BOS,76.000000,25.344825,1.657895,1.315789,5.342105,1.618421,0.013158,1.300000,8.473684
401,Mitchell Robinson,C-F,BOS,60.000000,25.000000,1.106852,1.489994,5.810975,0.893996,0.000000,1.149424,6.343116
487,Sam Hauser,F,BOS,78.000000,24.796795,1.461538,0.294872,3.128205,0.217949,2.538462,1.300000,0.871795
39,Baylor Scheierman,G,BOS,77.000000,18.562381,1.506494,0.077922,2.753247,0.363636,1.259740,0.600000,1.064935
146,Devin Carter,G,BOS,38.000000,18.417588,2.657895,0.236842,2.342105,1.763158,0.789474,1.700000,4.684211
397,Mike Conley,G,BOS,54.000000,18.357377,2.907407,0.259259,1.388889,0.833333,1.037037,0.800000,0.518519
293,Jordan Walsh,G,BOS,68.000000,17.823088,0.794118,0.455882,2.750000,0.647059,0.705882,1.200000,2.558824
369,Luka Garza,C,BOS,69.000000,16.201570,0.956522,0.405797,1.811594,1.304348,0.797101,1.100000,4.260870
197,Hugo González,G,BOS,74.000000,14.647703,0.540541,0.283784,2.486486,0.175676,0.567568,0.800000,2.000000
651,Dillon Mitchell,F,BOS,0.838996,11.431761,0.976986,0.342039,2.179477,0.619312,0.197666,0.572922,2.861510
580,Chris Cenac Jr.,C-F,BOS,3.748776,11.002671,1.337373,0.312286,1.803104,0.427077,0.069818,0.483468,2.675916
476,Ron Harper Jr.,G-F,BOS,29.000000,10.949195,0.758621,0.310345,1.137931,0.103448,0.965517,0.600000,1.241379
20,Amari Williams,F-C,BOS,22.000000,6.623788,0.454545,0.454545,1.409091,0.454545,0.000000,0.100000,0.909091
389,Max Shulga,G,BOS,11.000000,3.297727,0.181818,0.000000,0.272727,0.181818,0.090909,0.000000,0.181818
575,Caleb Grill,NaN,BOS,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
630,Milos Uzan,NaN,BOS,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
666,Tucker DeVries,NaN,BOS,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 18

BOS 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Derrick White,G,BOS,77.0,34.090346,5.376623,1.272727,3.285714,2.389610,2.714286,2.100000,4.207792
1,Jayson Tatum,F-G,BOS,60.0,32.615625,5.312500,0.187500,9.500000,4.062500,2.937500,2.800000,7.250000
2,Payton Pritchard,G,BOS,79.0,32.348397,5.164557,0.126582,3.075949,1.531646,2.683544,1.900000,5.898734
3,Paul George,F,BOS,37.0,30.676532,3.594595,0.432432,4.756757,2.459459,2.702703,2.300000,3.783784
4,Neemias Queta,C,BOS,76.0,25.344825,1.657895,1.315789,5.342105,1.618421,0.013158,1.300000,8.473684
5,Mitchell Robinson,C-F,BOS,60.0,25.000000,1.106852,1.489994,5.810975,0.893996,0.000000,1.149424,6.343116
6,Sam Hauser,F,BOS,78.0,24.796795,1.461538,0.294872,3.128205,0.217949,2.538462,1.300000,0.871795
7,Baylor Scheierman,G,BOS,77.0,18.562381,1.506494,0.077922,2.753247,0.363636,1.259740,0.600000,1.064935
8,Devin Carter,G,BOS,38.0,18.417588,2.657895,0.236842,2.342105,1.763158,0.789474,1.700000,4.684211

BOS 9 man rotation

Guards
Derrick White              34.1 min  (G)
Payton Pritchard           32.3 min  (G)
Baylor Scheierman          18.6 min  (G)
Devin Carter               18.4 min  (G)
Guard total: 103.4 minutes

Forwards
Jayson Tatum               32.6 min  (F-G)
Paul George                30.7 min  (F)
Sam Hauser                 24.8 min  (F)
Forward total: 88.1 minutes

Centers
Neemias Queta              25.3 min  (C)
Mitchell Robinson          25.0 min  (C-F)
Center total: 50.3 minutes
Total rotation minutes: 241.9
Position total:         241.9
Unassigned minutes:     0.0
CHA Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
344,Kon Knueppel,G-F,CHA,81.000000,31.490700,3.382716,0.234568,4.135802,2.407407,3.370370,2.100000,5.382716
57,Brandon Miller,F,CHA,65.000000,30.281718,3.338462,0.676923,3.830769,3.061538,3.138462,3.300000,6.430769
97,Coby White,G,CHA,50.000000,28.000000,4.480759,0.112019,3.427780,4.413547,2.576436,2.128360,6.228255
417,Naz Reid,C-F,CHA,77.000000,26.069481,2.207792,1.012987,5.025974,1.168831,2.103896,2.300000,5.792208
410,Moussa Diabaté,F,CHA,73.000000,26.013105,1.931507,0.986301,4.958904,1.589041,0.013699,1.400000,6.191781
139,Dennis Schröder,G,CHA,70.000000,24.232833,4.871429,0.157143,2.242857,2.442857,1.071429,1.300000,3.857143
501,Sion James,G,CHA,82.000000,22.479024,1.987805,0.243902,2.902439,1.000000,1.012195,1.000000,1.341463
189,Grayson Allen,G,CHA,40.000000,22.000000,2.923781,0.194919,1.769262,2.159100,2.384006,2.599916,3.058724
483,Ryan Kalkbrenner,C,CHA,69.000000,21.436691,0.782609,1.463768,3.043478,1.202899,0.000000,0.700000,6.318841
478,Royce O'Neale,F,CHA,40.000000,21.000000,1.973744,0.303653,2.970105,0.256207,2.011700,1.184246,0.891980
43,Bez Mbeng,G,CHA,40.000000,20.000000,2.519378,0.203176,1.584770,0.650162,0.243811,1.523817,3.575891
188,Grant Williams,F,CHA,36.000000,19.762593,1.555556,0.500000,2.666667,1.222222,1.444444,0.800000,1.111111
154,Dorian Finney-Smith,F,CHA,37.000000,16.765180,0.972973,0.162162,1.567568,0.216216,0.729730,0.500000,0.918919
519,Tidjane Salaün,F,CHA,37.000000,15.550811,0.729730,0.189189,3.324324,0.702703,0.972973,0.900000,2.378378
363,Liam McNeeley,F,CHA,31.000000,11.855538,0.774194,0.096774,1.935484,1.032258,0.774194,0.800000,0.903226
448,PJ Hall,C,CHA,19.000000,11.230439,0.526316,0.526316,2.210526,1.210526,0.157895,1.100000,2.842105
600,Michael Ajayi,F,CHA,3.985181,10.780116,0.906069,0.235784,2.093671,0.536091,0.006151,0.467497,3.050917
653,Hannes Steinbach,C-F,CHA,2.855486,10.221944,0.772592,0.369854,2.728347,0.707021,0.090845,0.449137,2.332422
654,Kylan Boswell,G,CHA,10.489775,9.372994,1.010312,0.141813,0.587054,0.465233,0.305324,0.533308,1.164464
585,Christian Anderson,G,CHA,0.257716,8.457876,2.574532,0.028094,0.613920,0.442642,0.633311,0.500024,1.095417
452,Pat Connaughton,G,CHA,42.000000,7.059960,0.428571,0.023810,1.095238,0.309524,0.500000,0.200000,0.809524
32,Antonio Reeves,G,CHA,10.000000,6.767667,0.300000,0.000000,0.600000,0.000000,0.700000,0.000000,0.400000
563,Xavier Tillman,F,CHA,30.000000,6.129278,0.433333,0.166667,0.800000,0.033333,0.100000,0.400000,1.133333

Available players: 23

CHA 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Kon Knueppel,G-F,CHA,81.0,31.490700,3.382716,0.234568,4.135802,2.407407,3.370370,2.100000,5.382716
1,Brandon Miller,F,CHA,65.0,30.281718,3.338462,0.676923,3.830769,3.061538,3.138462,3.300000,6.430769
2,Coby White,G,CHA,50.0,28.000000,4.480759,0.112019,3.427780,4.413547,2.576436,2.128360,6.228255
3,Naz Reid,C-F,CHA,77.0,26.069481,2.207792,1.012987,5.025974,1.168831,2.103896,2.300000,5.792208
4,Moussa Diabaté,F,CHA,73.0,26.013105,1.931507,0.986301,4.958904,1.589041,0.013699,1.400000,6.191781
5,Dennis Schröder,G,CHA,70.0,24.232833,4.871429,0.157143,2.242857,2.442857,1.071429,1.300000,3.857143
6,Sion James,G,CHA,82.0,22.479024,1.987805,0.243902,2.902439,1.000000,1.012195,1.000000,1.341463
7,Grayson Allen,G,CHA,40.0,22.000000,2.923781,0.194919,1.769262,2.159100,2.384006,2.599916,3.058724
8,Ryan Kalkbrenner,C,CHA,69.0,21.436691,0.782609,1.463768,3.043478,1.202899,0.000000,0.700000,6.318841

CHA 9 man rotation

Guards
Kon Knueppel               31.5 min  (G-F)
Coby White                 28.0 min  (G)
Dennis Schröder            24.2 min  (G)
Sion James                 22.5 min  (G)
Grayson Allen              22.0 min  (G)
Guard total: 128.2 minutes

Forwards
Brandon Miller             30.3 min  (F)
Moussa Diabaté             26.0 min  (F)
Forward total: 56.3 minutes

Centers
Naz Reid                   26.1 min  (C-F)
Ryan Kalkbrenner           21.4 min  (C)
Center total: 47.5 minutes
Total rotation minutes: 232.0
Position total:         232.0
Unassigned minutes:     0.0
CHI Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
295,Josh Giddey,G,CHI,60.000000,32.062160,9.148148,0.500000,7.055556,3.222222,1.907407,2.600000,7.703704
435,Norman Powell,G,CHI,65.000000,29.602356,2.465517,0.241379,3.103448,4.534483,2.689655,3.400000,7.896552
386,Matas Buzelis,F,CHI,77.000000,29.198030,2.051948,1.506494,4.818182,2.428571,2.246753,1.500000,6.883117
419,Nic Claxton,C,CHI,69.000000,27.831401,3.666667,1.115942,4.492754,2.043478,0.043478,1.800000,9.188406
529,Tre Jones,G,CHI,65.000000,26.959590,5.384615,0.169231,2.553846,2.938462,0.630769,2.400000,8.923077
203,Isaac Okoro,F-G,CHI,63.000000,26.903016,1.587302,0.460317,1.650794,1.412698,1.158730,1.200000,4.380952
635,Caleb Wilson,F-C,CHI,5.605511,21.085169,1.404064,0.964940,3.697298,1.465797,0.325147,1.499070,4.629956
234,Jalen Smith,F-C,CHI,53.000000,20.667704,1.226415,0.792453,4.849057,1.301887,1.547170,1.200000,4.150943
455,Patrick Williams,F,CHI,72.000000,20.469167,1.458333,0.361111,2.305556,0.750000,1.319444,0.800000,2.000000
569,Zach Collins,F-C,CHI,10.000000,18.373667,1.500000,0.400000,4.000000,1.400000,0.900000,1.700000,5.200000
362,Leonard Miller,F,CHI,46.000000,15.623080,0.869565,0.326087,2.760870,0.847826,0.695652,1.200000,4.826087
473,Rob Dillingham,G,CHI,65.000000,14.922359,2.200000,0.092308,1.723077,0.630769,0.646154,0.800000,2.953846
632,Tobe Awaka,F,CHI,13.184913,13.285712,1.442847,0.265548,1.785688,0.798302,0.015640,0.684042,3.531743
655,Dailyn Swain,F-G,CHI,3.587759,10.567909,0.872142,0.138724,1.245267,0.495696,0.436484,0.731570,1.192928
649,Jaylin Sellers,G,CHI,12.356931,10.263718,0.661083,0.222881,1.511176,0.788552,0.655424,0.682015,1.164811
430,Noa Essengue,F,CHI,2.000000,3.016667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

Available players: 16

CHI 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Josh Giddey,G,CHI,60.000000,32.062160,9.148148,0.500000,7.055556,3.222222,1.907407,2.60000,7.703704
1,Norman Powell,G,CHI,65.000000,29.602356,2.465517,0.241379,3.103448,4.534483,2.689655,3.40000,7.896552
2,Matas Buzelis,F,CHI,77.000000,29.198030,2.051948,1.506494,4.818182,2.428571,2.246753,1.50000,6.883117
3,Nic Claxton,C,CHI,69.000000,27.831401,3.666667,1.115942,4.492754,2.043478,0.043478,1.80000,9.188406
4,Tre Jones,G,CHI,65.000000,26.959590,5.384615,0.169231,2.553846,2.938462,0.630769,2.40000,8.923077
5,Isaac Okoro,F-G,CHI,63.000000,26.903016,1.587302,0.460317,1.650794,1.412698,1.158730,1.20000,4.380952
6,Caleb Wilson,F-C,CHI,5.605511,21.085169,1.404064,0.964940,3.697298,1.465797,0.325147,1.49907,4.629956
7,Jalen Smith,F-C,CHI,53.000000,20.667704,1.226415,0.792453,4.849057,1.301887,1.547170,1.20000,4.150943
8,Patrick Williams,F,CHI,72.000000,20.469167,1.458333,0.361111,2.305556,0.750000,1.319444,0.80000,2.000000

CHI 9 man rotation

Guards
Josh Giddey                32.1 min  (G)
Norman Powell              29.6 min  (G)
Tre Jones                  27.0 min  (G)
Guard total: 88.6 minutes

Forwards
Matas Buzelis              29.2 min  (F)
Isaac Okoro                26.9 min  (F-G)
Caleb Wilson               21.1 min  (F-C)
Jalen Smith                20.7 min  (F-C)
Patrick Williams           20.5 min  (F)
Forward total: 118.3 minutes

Centers
Nic Claxton                27.8 min  (C)
Center total: 27.8 minutes
Total rotation minutes: 234.8
Position total:         234.8
Unassigned minutes:     0.0
CLE Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
242,James Harden,G,CLE,70.000000,34.835643,7.957143,0.400000,4.228571,6.614286,3.071429,2.600000,6.657143
152,Donovan Mitchell,G,CLE,70.000000,33.458048,5.685714,0.285714,3.800000,5.314286,3.200000,4.400000,10.571429
175,Evan Mobley,C,CLE,65.000000,31.912128,3.600000,1.738462,6.615385,2.769231,0.953846,2.200000,11.846154
462,Peyton Watson,G,CLE,61.000000,29.588117,2.055556,1.129630,3.981481,2.555556,1.500000,2.100000,6.592593
249,Jarrett Allen,C,CLE,56.000000,27.127143,1.785714,0.839286,5.928571,3.303571,0.017857,2.600000,11.464286
260,Jaylon Tyson,G-F,CLE,66.000000,26.931566,2.227273,0.424242,3.333333,1.196970,2.015152,2.000000,5.575758
488,Sam Merrill,G,CLE,52.000000,26.482179,2.403846,0.134615,2.019231,1.134615,3.038462,1.500000,2.038462
643,Mario Hezonja,F,CLE,12.446239,18.449821,1.409572,0.280387,2.416763,0.706178,1.304858,1.098455,1.655890
109,Craig Porter Jr.,G,CLE,64.000000,17.932214,3.203125,0.593750,2.109375,0.375000,0.515625,0.900000,2.312500
414,Nae'Qwan Tomlin,F,CLE,64.000000,15.681849,0.828125,0.531250,1.562500,0.734375,0.421875,1.400000,3.843750
622,Meleek Thomas,G,CLE,2.272371,13.644823,1.460583,0.050560,1.307427,0.499184,0.906887,1.061284,1.446624
518,Thomas Bryant,C-F,CLE,60.000000,12.196944,0.550000,0.433333,2.433333,0.883333,0.783333,1.100000,2.866667
550,Tyrese Proctor,G,CLE,50.000000,10.901733,1.480000,0.000000,1.060000,0.800000,0.920000,1.300000,1.440000
538,Tristan Enaruna,F,CLE,9.000000,9.459259,0.777778,0.000000,0.777778,0.666667,0.333333,1.200000,2.444444
472,Riley Minix,F,CLE,9.000000,6.453704,0.555556,0.111111,0.444444,0.333333,0.444444,0.400000,2.000000
615,Khalifa Diop,NaN,CLE,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
647,"Ernest Udeh, Jr.",NaN,CLE,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 15

CLE 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,James Harden,G,CLE,70.000000,34.835643,7.957143,0.400000,4.228571,6.614286,3.071429,2.600000,6.657143
1,Donovan Mitchell,G,CLE,70.000000,33.458048,5.685714,0.285714,3.800000,5.314286,3.200000,4.400000,10.571429
2,Evan Mobley,C,CLE,65.000000,31.912128,3.600000,1.738462,6.615385,2.769231,0.953846,2.200000,11.846154
3,Peyton Watson,G,CLE,61.000000,29.588117,2.055556,1.129630,3.981481,2.555556,1.500000,2.100000,6.592593
4,Jarrett Allen,C,CLE,56.000000,27.127143,1.785714,0.839286,5.928571,3.303571,0.017857,2.600000,11.464286
5,Jaylon Tyson,G-F,CLE,66.000000,26.931566,2.227273,0.424242,3.333333,1.196970,2.015152,2.000000,5.575758
6,Sam Merrill,G,CLE,52.000000,26.482179,2.403846,0.134615,2.019231,1.134615,3.038462,1.500000,2.038462
7,Mario Hezonja,F,CLE,12.446239,18.449821,1.409572,0.280387,2.416763,0.706178,1.304858,1.098455,1.655890
8,Craig Porter Jr.,G,CLE,64.000000,17.932214,3.203125,0.593750,2.109375,0.375000,0.515625,0.900000,2.312500

CLE 9 man rotation

Guards
James Harden               34.8 min  (G)
Donovan Mitchell           33.5 min  (G)
Peyton Watson              29.6 min  (G)
Jaylon Tyson               26.9 min  (G-F)
Sam Merrill                26.5 min  (G)
Craig Porter Jr.           17.9 min  (G)
Guard total: 169.2 minutes

Forwards
Mario Hezonja              18.4 min  (F)
Forward total: 18.4 minutes

Centers
Evan Mobley                31.9 min  (C)
Jarrett Allen              27.1 min  (C)
Center total: 59.0 minutes
Total rotation minutes: 246.7
Position total:         246.7
Unassigned minutes:     0.0
DAL Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
106,Cooper Flagg,F,DAL,70.000000,33.483690,4.514286,0.914286,5.428571,4.042857,1.028571,2.900000,11.285714
687,Kyrie Irving,G,DAL,65.000000,33.000000,4.226086,0.420779,3.293054,3.585770,2.634443,3.018633,8.488762
447,P.J. Washington,F,DAL,56.000000,30.993214,1.750000,1.071429,5.535714,2.232143,1.357143,1.600000,7.464286
415,Naji Marshall,F,DAL,57.000000,26.000000,2.869389,0.071437,3.369449,2.714609,0.738183,1.938326,7.977140
568,Zaccharie Risacher,F,DAL,62.000000,25.000000,1.263925,0.598701,3.093291,0.964575,1.579907,2.339925,4.523522
388,Max Christie,G,DAL,57.000000,25.000000,1.681904,0.300738,2.606394,1.392305,2.004919,1.286490,2.650948
140,Dereck Lively II,C,DAL,57.000000,25.000000,2.819386,2.385634,4.988144,1.735007,0.000000,1.366318,4.771268
118,Daniel Gafford,F-C,DAL,62.000000,25.000000,1.213960,1.444193,5.023282,2.302337,0.000000,1.496519,8.581439
490,Santi Aldama,F-C,DAL,57.000000,22.000000,2.313705,0.569245,4.039803,1.395568,1.285392,1.737115,5.215018
278,John Poulakidas,G,DAL,13.000000,19.495000,0.846154,0.307692,2.000000,0.461538,2.384615,1.800000,0.615385
73,Caleb Martin,F,DAL,58.000000,14.762270,1.396552,0.258621,1.982759,0.637931,0.344828,0.600000,1.931034
164,Dwight Powell,F-C,DAL,63.000000,14.355741,1.079365,0.333333,2.555556,1.238095,0.031746,0.600000,1.968254
586,Tarik Biberovic,F-G,DAL,17.775105,14.062037,1.100753,0.007288,1.231690,0.366128,1.301326,1.191375,1.319101
409,Moussa Cisse,C,DAL,38.000000,13.936316,0.236842,1.184211,3.342105,1.000000,0.000000,0.500000,3.473684
269,Jett Howard,G,DAL,55.000000,12.642182,0.818182,0.200000,1.163636,0.672727,0.981818,0.500000,1.672727
379,Marcus Sasser,G,DAL,38.000000,12.013246,1.973684,0.105263,0.842105,0.394737,1.157895,1.000000,1.052632
589,Tobi Lawal,F,DAL,-1.386579,9.856371,1.286771,0.284516,1.503276,0.656477,0.207820,0.735525,2.622958
603,Sergio de Larrea,NaN,DAL,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
628,Vsevolod Ishchenko,NaN,DAL,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
661,Morez Johnson,NaN,DAL,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 16

DAL 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Cooper Flagg,F,DAL,70.0,33.483690,4.514286,0.914286,5.428571,4.042857,1.028571,2.900000,11.285714
1,Kyrie Irving,G,DAL,65.0,33.000000,4.226086,0.420779,3.293054,3.585770,2.634443,3.018633,8.488762
2,P.J. Washington,F,DAL,56.0,30.993214,1.750000,1.071429,5.535714,2.232143,1.357143,1.600000,7.464286
3,Naji Marshall,F,DAL,57.0,26.000000,2.869389,0.071437,3.369449,2.714609,0.738183,1.938326,7.977140
4,Daniel Gafford,F-C,DAL,62.0,25.000000,1.213960,1.444193,5.023282,2.302337,0.000000,1.496519,8.581439
5,Dereck Lively II,C,DAL,57.0,25.000000,2.819386,2.385634,4.988144,1.735007,0.000000,1.366318,4.771268
6,Max Christie,G,DAL,57.0,25.000000,1.681904,0.300738,2.606394,1.392305,2.004919,1.286490,2.650948
7,Zaccharie Risacher,F,DAL,62.0,25.000000,1.263925,0.598701,3.093291,0.964575,1.579907,2.339925,4.523522
8,Santi Aldama,F-C,DAL,57.0,22.000000,2.313705,0.569245,4.039803,1.395568,1.285392,1.737115,5.215018

DAL 9 man rotation

Guards
Kyrie Irving               33.0 min  (G)
Max Christie               25.0 min  (G)
Guard total: 58.0 minutes

Forwards
Cooper Flagg               33.5 min  (F)
P.J. Washington            31.0 min  (F)
Naji Marshall              26.0 min  (F)
Daniel Gafford             25.0 min  (F-C)
Zaccharie Risacher         25.0 min  (F)
Santi Aldama               22.0 min  (F-C)
Forward total: 162.5 minutes

Centers
Dereck Lively II           25.0 min  (C)
Center total: 25.0 minutes
Total rotation minutes: 245.5
Position total:         245.5
Unassigned minutes:     0.0
DEN Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
239,Jamal Murray,G,DEN,75.000000,35.358556,7.133333,0.386667,3.973333,4.613333,3.266667,2.300000,7.760000
425,Nikola Jokić,C,DEN,71.000000,34.843923,10.723077,0.815385,9.907692,6.138462,1.723077,2.600000,14.338462
93,Christian Braun,G,DEN,44.000000,31.798598,2.727273,0.272727,3.409091,1.795455,0.977273,2.100000,7.000000
134,DeMar DeRozan,G-F,DEN,77.000000,31.240455,4.103896,0.298701,2.480519,4.857143,0.610390,2.000000,5.688312
78,Cameron Johnson,F,DEN,59.000000,30.500586,2.444444,0.388889,3.018519,1.740741,2.037037,1.600000,3.703704
3,Aaron Gordon,F,DEN,64.000000,29.000000,2.770264,0.288569,4.559393,3.607115,1.760272,1.662158,6.752519
63,Bruce Brown,G-F,DEN,82.000000,24.363272,2.121951,0.243902,2.841463,1.170732,0.695122,1.300000,4.414634
503,Spencer Jones,F,DEN,64.000000,24.000000,0.863925,0.491251,2.269920,0.525131,0.965563,0.758899,2.473196
595,Lonnie Walker IV,NaN,DEN,49.000000,23.835167,2.500000,0.250000,2.850000,1.200000,2.250000,NaN,0.000000
305,Julian Strawther,G,DEN,57.000000,22.000000,1.559244,0.153368,2.607261,1.456999,1.482560,1.602699,4.140944
384,Marvin Bagley III,F,DEN,60.000000,20.015056,1.416667,0.716667,3.600000,1.583333,0.400000,1.300000,7.533333
552,Tyus Jones,G,DEN,67.000000,14.605647,2.373134,0.044776,0.955224,0.104478,0.597015,0.400000,0.835821
126,David Roddy,F,DEN,5.000000,14.603333,0.800000,0.200000,2.400000,1.400000,0.600000,1.200000,4.800000
581,Alpha Diallo,F-G,DEN,10.966946,13.475593,0.987582,0.129398,0.790813,0.503112,0.550425,0.471667,0.912679
310,KJ Simpson,G,DEN,20.000000,12.880500,2.150000,0.000000,1.400000,0.550000,0.600000,0.600000,2.100000
570,Zeke Nnaji,F-C,DEN,52.000000,12.038237,0.557692,0.461538,1.980769,0.653846,0.269231,0.600000,2.076923
664,Bryce Hopkins,F,DEN,4.072696,10.669102,0.779925,0.129829,1.278802,0.517992,0.267063,0.605839,1.631941
609,Trevon Brazile,F-C,DEN,5.280506,9.088111,0.695028,0.348986,1.256718,0.573832,0.116472,0.725818,1.580890
110,Curtis Jones,G,DEN,10.000000,8.771667,1.000000,0.000000,0.900000,0.100000,0.600000,0.000000,0.600000
113,DaRon Holmes II,F,DEN,25.000000,8.380400,0.640000,0.240000,1.080000,0.440000,0.800000,0.300000,0.720000

Available players: 20
  -> Adding real player Zeke Nnaji (F-C, 12.04 min) to fill C
     Removing Lonnie Walker IV to make room.

DEN 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Jamal Murray,G,DEN,75.0,35.358556,7.133333,0.386667,3.973333,4.613333,3.266667,2.3,7.76
1,Nikola Jokić,C,DEN,71.0,34.843923,10.723077,0.815385,9.907692,6.138462,1.723077,2.6,14.338462
2,Christian Braun,G,DEN,44.0,31.798598,2.727273,0.272727,3.409091,1.795455,0.977273,2.1,7.0
3,DeMar DeRozan,G-F,DEN,77.0,31.240455,4.103896,0.298701,2.480519,4.857143,0.61039,2.0,5.688312
4,Cameron Johnson,F,DEN,59.0,30.500586,2.444444,0.388889,3.018519,1.740741,2.037037,1.6,3.703704
5,Aaron Gordon,F,DEN,64.0,29.000000,2.770264,0.288569,4.559393,3.607115,1.760272,1.662158,6.752519
6,Bruce Brown,G-F,DEN,82.0,24.363272,2.121951,0.243902,2.841463,1.170732,0.695122,1.3,4.414634
7,Spencer Jones,F,DEN,64.0,24.000000,0.863925,0.491251,2.26992,0.525131,0.965563,0.758899,2.473196
8,Zeke Nnaji,F-C,DEN,52.0,12.038237,0.557692,0.461538,1.980769,0.653846,0.269231,0.6,2.076923

DEN 9 man rotation

Guards
Jamal Murray               35.4 min  (G)
Christian Braun            31.8 min  (G)
DeMar DeRozan              31.2 min  (G-F)
Bruce Brown                24.4 min  (G-F)
Guard total: 122.8 minutes

Forwards
Cameron Johnson            30.5 min  (F)
Aaron Gordon               29.0 min  (F)
Spencer Jones              24.0 min  (F)
Zeke Nnaji                 12.0 min  (F-C)
Forward total: 95.5 minutes

Centers
Nikola Jokić               34.8 min  (C)
Center total: 34.8 minutes
Total rotation minutes: 253.1
Position total:         253.1
Unassigned minutes:     -0.0
DET Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
70,Cade Cunningham,G,DET,75.000000,33.932370,9.906250,0.843750,4.671875,4.843750,1.953125,4.300000,10.468750
229,Jalen Duren,C,DET,70.000000,28.226476,1.971429,0.842857,6.742857,4.585714,0.000000,2.700000,14.571429
162,Duncan Robinson,F,DET,77.000000,27.443615,2.064935,0.285714,2.285714,1.077922,2.857143,1.800000,2.363636
276,John Collins,F-C,DET,69.000000,27.122874,1.014493,0.739130,3.724638,1.710145,1.289855,2.300000,7.072464
35,Ausar Thompson,G-F,DET,73.000000,25.967260,3.123288,0.945205,3.671233,1.493151,0.082192,2.200000,7.863014
477,Ronald Holland II,F,DET,78.000000,25.000000,1.531815,0.435358,3.740853,1.934924,0.806218,2.892712,5.837021
457,Paul Reed,F,DET,65.000000,25.000000,2.220672,1.665504,4.552377,2.026363,0.360859,2.526014,10.270607
513,Taurean Prince,F,DET,63.000000,23.511667,1.769231,0.230769,2.961538,0.230769,2.346154,1.500000,1.461538
208,Isaiah Joe,G,DET,71.000000,23.000000,1.434215,0.167834,2.258126,1.678337,2.761626,2.491567,1.434215
330,Kevin Huerter,G-F,DET,69.000000,22.450386,2.579710,0.478261,2.985507,0.797101,1.449275,1.400000,4.579710
170,Elijah Harkless,G,DET,26.000000,20.954359,2.884615,0.230769,1.653846,1.884615,0.807692,1.700000,2.307692
119,Daniss Jenkins,G,DET,72.000000,20.212500,3.861111,0.208333,1.597222,1.861111,1.013889,1.400000,3.305556
253,Javonte Green,G,DET,82.000000,17.633679,0.682927,0.304878,2.048780,1.280488,1.146341,1.700000,2.146341
181,Gary Harris,G,DET,48.000000,13.766007,1.062500,0.187500,0.937500,0.166667,0.583333,0.500000,0.625000
576,Ugonna Onyenso,C,DET,4.262618,13.535430,1.443538,0.638082,1.813413,0.797488,0.037208,0.549728,2.202924
583,Ebuka Okorie,G,DET,11.261095,11.188794,2.078185,0.108419,1.238663,1.078843,0.846302,0.784463,1.343790
560,Wendell Moore Jr.,G,DET,6.000000,9.925833,0.666667,0.333333,0.833333,0.333333,0.000000,0.700000,1.333333
523,Tolu Smith,F,DET,15.000000,9.162778,0.866667,0.400000,1.800000,1.333333,0.000000,0.700000,2.400000
86,Chaz Lanier,G,DET,34.000000,7.706029,0.500000,0.000000,0.441176,0.147059,0.558824,0.300000,0.176471
202,Isaac Jones,F,DET,7.000000,5.097619,0.142857,0.142857,0.428571,0.428571,0.000000,0.100000,0.857143

Available players: 20

DET 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Cade Cunningham,G,DET,75.0,33.932370,9.906250,0.843750,4.671875,4.843750,1.953125,4.300000,10.468750
1,Jalen Duren,C,DET,70.0,28.226476,1.971429,0.842857,6.742857,4.585714,0.000000,2.700000,14.571429
2,Duncan Robinson,F,DET,77.0,27.443615,2.064935,0.285714,2.285714,1.077922,2.857143,1.800000,2.363636
3,John Collins,F-C,DET,69.0,27.122874,1.014493,0.739130,3.724638,1.710145,1.289855,2.300000,7.072464
4,Ausar Thompson,G-F,DET,73.0,25.967260,3.123288,0.945205,3.671233,1.493151,0.082192,2.200000,7.863014
5,Ronald Holland II,F,DET,78.0,25.000000,1.531815,0.435358,3.740853,1.934924,0.806218,2.892712,5.837021
6,Paul Reed,F,DET,65.0,25.000000,2.220672,1.665504,4.552377,2.026363,0.360859,2.526014,10.270607
7,Taurean Prince,F,DET,63.0,23.511667,1.769231,0.230769,2.961538,0.230769,2.346154,1.500000,1.461538
8,Isaiah Joe,G,DET,71.0,23.000000,1.434215,0.167834,2.258126,1.678337,2.761626,2.491567,1.434215

DET 9 man rotation

Guards
Cade Cunningham            33.9 min  (G)
Ausar Thompson             26.0 min  (G-F)
Isaiah Joe                 23.0 min  (G)
Guard total: 82.9 minutes

Forwards
Duncan Robinson            27.4 min  (F)
John Collins               27.1 min  (F-C)
Ronald Holland II          25.0 min  (F)
Paul Reed                  25.0 min  (F)
Taurean Prince             23.5 min  (F)
Forward total: 128.1 minutes

Centers
Jalen Duren                28.2 min  (C)
Center total: 28.2 minutes
Total rotation minutes: 239.2
Position total:         239.2
Unassigned minutes:     -0.0
FA Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
522,Toby Okani,F,FA,6.0,36.181667,1.000000,0.500000,2.000000,0.166667,1.500000,1.2,4.333333
23,Andersson Garcia,F,FA,5.0,33.750000,2.800000,0.800000,5.000000,1.400000,0.200000,1.2,3.200000
323,Kennedy Chandler,G,FA,11.0,32.293333,6.727273,0.181818,2.818182,2.545455,1.363636,2.5,7.818182
366,Lucas Williamson,G,FA,7.0,31.962857,2.571429,0.142857,3.857143,1.142857,2.142857,2.4,2.857143
304,Julian Reese,F,FA,13.0,30.884615,1.846154,0.615385,6.307692,2.153846,0.000000,1.7,9.384615
...,...,...,...,...,...,...,...,...,...,...,...,...
179,Garrett Temple,G-F,FA,22.0,3.315303,0.409091,0.090909,0.363636,0.272727,0.136364,0.2,0.000000
504,Stanley Umude,G,FA,2.0,3.283333,0.500000,0.000000,0.000000,0.000000,0.000000,0.0,1.000000
532,Trentyn Flowers,F,FA,2.0,2.775000,0.500000,0.000000,0.000000,0.000000,0.000000,1.0,2.000000
123,Darius Brown II,NaN,FA,1.0,2.666667,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.000000
525,Tosan Evbuomwan,F,FA,5.0,1.542667,0.000000,0.000000,0.200000,0.000000,0.000000,0.0,0.000000

Available players: 93
  -> Adding real player Josh Oduro (C, 27.26 min) to fill C
     Removing Russell Westbrook to make room.
  -> Adding real player Lawson Lovering (C, 24.63 min) to fill C
     Removing Adama Bal to make room.

FA 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Toby Okani,F,FA,6.0,36.181667,1.0,0.5,2.0,0.166667,1.5,1.2,4.333333
1,Andersson Garcia,F,FA,5.0,33.750000,2.8,0.8,5.0,1.4,0.2,1.2,3.2
2,Kennedy Chandler,G,FA,11.0,32.293333,6.727273,0.181818,2.818182,2.545455,1.363636,2.5,7.818182
3,Lucas Williamson,G,FA,7.0,31.962857,2.571429,0.142857,3.857143,1.142857,2.142857,2.4,2.857143
4,Julian Reese,F,FA,13.0,30.884615,1.846154,0.615385,6.307692,2.153846,0.0,1.7,9.384615
5,Dariq Whitehead,G-F,FA,6.0,30.469444,1.5,0.0,3.666667,0.833333,3.166667,2.5,5.0
6,Trevon Scott,F,FA,6.0,30.372500,1.666667,0.833333,3.5,0.666667,1.0,0.5,3.666667
7,Josh Oduro,C,FA,3.0,27.255556,1.333333,0.0,4.0,1.0,0.0,0.7,6.666667
8,Lawson Lovering,C,FA,2.0,24.632500,1.5,0.5,4.5,1.0,0.0,1.0,6.0

FA 9 man rotation

Guards
Kennedy Chandler           32.3 min  (G)
Lucas Williamson           32.0 min  (G)
Dariq Whitehead            30.5 min  (G-F)
Guard total: 94.7 minutes

Forwards
Toby Okani                 36.2 min  (F)
Andersson Garcia           33.8 min  (F)
Julian Reese               30.9 min  (F)
Trevon Scott               30.4 min  (F)
Forward total: 131.2 minutes

Centers
Josh Oduro                 27.3 min  (C)
Lawson Lovering            24.6 min  (C)
Center total: 51.9 minutes
Total rotation minutes: 277.8
Position total:         277.8
Unassigned minutes:     0.0
GSW Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
271,Jimmy Butler III,F,GSW,38.0,31.096754,4.868421,0.210526,3.236842,6.526316,0.842105,3.500000,9.736842
54,Brandin Podziemski,G,GSW,82.0,28.447236,3.707317,0.182927,4.231707,2.341463,1.865854,2.500000,4.804878
505,Stephen Curry,G,GSW,55.0,28.000000,4.277774,0.358237,2.886971,4.298847,4.003828,4.077583,5.689651
157,Draymond Green,F,GSW,68.0,27.483652,5.529412,0.617647,4.705882,0.867647,1.485294,0.900000,2.941176
58,Brandon Williams,G,GSW,50.0,26.000000,4.550660,0.355520,2.861938,4.284020,0.639937,2.346434,8.034759
406,Moses Moody,G,GSW,0.0,25.664972,1.633333,0.566667,2.483333,1.450000,2.516667,1.600000,2.733333
637,Yaxel Lendeborg,F,GSW,40.0,25.000000,3.102992,0.553446,3.270031,1.379853,1.326433,1.465073,3.396234
347,Kristaps Porziņģis,F-C,GSW,45.0,24.027865,2.531250,1.187500,3.968750,4.156250,1.687500,2.300000,5.687500
131,De'Anthony Melton,G,GSW,35.0,22.964422,2.551020,0.408163,2.428571,2.040816,1.469388,2.000000,5.265306
12,Al Horford,C-F,GSW,40.0,21.537444,2.577778,1.133333,3.888889,0.488889,1.644444,0.900000,2.533333
191,Gui Santos,F,GSW,68.0,20.520049,2.338235,0.323529,2.808824,1.279412,1.147059,1.800000,4.411765
561,Will Richard,G,GSW,69.0,19.953696,1.347826,0.130435,1.521739,0.666667,1.028986,1.700000,2.463768
416,Nate Williams,G,GSW,14.0,17.083571,1.000000,0.000000,0.714286,0.928571,0.928571,1.700000,4.285714
353,LJ Cryer,G,GSW,18.0,16.230370,1.000000,0.000000,1.333333,0.944444,2.055556,1.200000,0.666667
182,Gary Payton II,G,GSW,73.0,15.647671,1.684932,0.287671,2.246575,0.356164,0.506849,1.800000,5.589041
495,Seth Curry,G,GSW,10.0,13.300000,1.000000,0.000000,0.800000,1.100000,1.200000,0.700000,1.000000
85,Charles Bassey,C-F,GSW,13.0,11.746410,0.538462,0.846154,2.615385,1.076923,0.000000,0.700000,4.615385
116,Dalen Terry,F,GSW,48.0,11.479722,1.375000,0.312500,1.250000,0.333333,0.500000,0.900000,1.791667
376,Malevy Leons,F,GSW,25.0,11.058867,0.920000,0.360000,0.920000,0.600000,0.160000,0.600000,2.160000
591,Georges Niang,NaN,GSW,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
578,Lajae Jones,NaN,GSW,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
611,Alex Toohey,NaN,GSW,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 18

GSW 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Jimmy Butler III,F,GSW,38.0,31.096754,4.868421,0.210526,3.236842,6.526316,0.842105,3.500000,9.736842
1,Brandin Podziemski,G,GSW,82.0,28.447236,3.707317,0.182927,4.231707,2.341463,1.865854,2.500000,4.804878
2,Stephen Curry,G,GSW,55.0,28.000000,4.277774,0.358237,2.886971,4.298847,4.003828,4.077583,5.689651
3,Draymond Green,F,GSW,68.0,27.483652,5.529412,0.617647,4.705882,0.867647,1.485294,0.900000,2.941176
4,Brandon Williams,G,GSW,50.0,26.000000,4.550660,0.355520,2.861938,4.284020,0.639937,2.346434,8.034759
5,Yaxel Lendeborg,F,GSW,40.0,25.000000,3.102992,0.553446,3.270031,1.379853,1.326433,1.465073,3.396234
6,Kristaps Porziņģis,F-C,GSW,45.0,24.027865,2.531250,1.187500,3.968750,4.156250,1.687500,2.300000,5.687500
7,De'Anthony Melton,G,GSW,35.0,22.964422,2.551020,0.408163,2.428571,2.040816,1.469388,2.000000,5.265306
8,Al Horford,C-F,GSW,40.0,21.537444,2.577778,1.133333,3.888889,0.488889,1.644444,0.900000,2.533333

GSW 9 man rotation

Guards
Brandin Podziemski         28.4 min  (G)
Stephen Curry              28.0 min  (G)
Brandon Williams           26.0 min  (G)
De'Anthony Melton          23.0 min  (G)
Guard total: 105.4 minutes

Forwards
Jimmy Butler III           31.1 min  (F)
Draymond Green             27.5 min  (F)
Yaxel Lendeborg            25.0 min  (F)
Kristaps Porziņģis         24.0 min  (F-C)
Forward total: 107.6 minutes

Centers
Al Horford                 21.5 min  (C-F)
Center total: 21.5 minutes
Total rotation minutes: 234.6
Position total:         234.6
Unassigned minutes:     0.0
HOU Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
21,Amen Thompson,G-F,HOU,79.000000,37.381646,5.316456,0.607595,4.797468,3.848101,0.316456,3.100000,12.708861
329,Kevin Durant,F,HOU,78.000000,36.407991,4.769231,0.910256,4.935897,5.230769,2.384615,3.500000,8.410256
682,Fred VanVleet,G,HOU,60.000000,35.188306,5.550000,0.416667,3.150000,1.850000,2.650000,2.200000,2.666667
215,Jabari Smith Jr.,F,HOU,77.000000,35.134610,1.857143,0.922078,5.467532,2.103896,2.298701,2.100000,5.272727
19,Alperen Sengun,C,HOU,72.000000,33.301319,6.180556,1.069444,5.902778,3.611111,0.555556,2.900000,14.000000
380,Marcus Smart,G,HOU,62.000000,28.531909,2.983871,0.370968,2.193548,1.709677,1.564516,0.900000,2.419355
471,Reed Sheppard,G,HOU,82.000000,26.181992,3.378049,0.658537,2.560976,0.841463,2.768293,2.100000,3.219512
512,Tari Eason,F,HOU,60.000000,25.818417,1.500000,0.466667,4.200000,0.866667,1.550000,2.000000,4.633333
507,Steven Adams,C,HOU,60.000000,22.823906,1.500000,0.625000,4.093750,1.468750,0.000000,0.600000,4.312500
50,Bogdan Bogdanović,G,HOU,50.000000,19.654783,2.217391,0.130435,2.304348,0.869565,1.434783,0.600000,1.565217
444,Oscar Tshiebwe,F-C,HOU,27.000000,16.608148,1.185185,0.185185,3.777778,1.000000,0.000000,1.000000,6.592593
4,Aaron Holiday,G,HOU,57.000000,13.697047,1.052632,0.087719,0.789474,0.614035,1.175439,0.800000,1.192982
597,Rafael Castro,F-C,HOU,0.479005,13.249867,1.132699,0.392236,1.749881,0.745846,0.046280,0.336095,3.061987
96,Clint Capela,C,HOU,75.000000,12.342156,0.666667,0.840000,2.466667,0.600000,0.013333,0.400000,3.120000
620,Quadir Copeland,G,HOU,3.211459,12.030621,1.492189,0.189056,0.878900,0.582117,0.204501,0.487153,1.148566
675,Bruce Thornton,G,HOU,10.033653,10.268869,1.272634,0.032791,0.660515,0.495417,0.851950,0.620419,0.868081
303,Julian Phillips,F,HOU,48.000000,8.896181,0.208333,0.145833,0.541667,0.375000,0.416667,0.500000,1.250000
221,Jae'Sean Tate,F,HOU,46.000000,8.798333,0.543478,0.065217,0.869565,0.152174,0.217391,0.200000,1.913043
205,Isaiah Crawford,F,HOU,14.000000,6.578571,0.357143,0.214286,0.928571,0.357143,0.214286,0.100000,0.714286
263,Jeff Green,F,HOU,30.000000,5.827222,0.266667,0.066667,0.600000,0.166667,0.400000,0.400000,0.666667
494,Sean Pedulla,G,HOU,7.000000,4.428571,0.714286,0.000000,0.428571,0.000000,0.428571,0.300000,0.571429

Available players: 21

HOU 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Amen Thompson,G-F,HOU,79.0,37.381646,5.316456,0.607595,4.797468,3.848101,0.316456,3.1,12.708861
1,Kevin Durant,F,HOU,78.0,36.407991,4.769231,0.910256,4.935897,5.230769,2.384615,3.5,8.410256
2,Fred VanVleet,G,HOU,60.0,35.188306,5.550000,0.416667,3.150000,1.850000,2.650000,2.2,2.666667
3,Jabari Smith Jr.,F,HOU,77.0,35.134610,1.857143,0.922078,5.467532,2.103896,2.298701,2.1,5.272727
4,Alperen Sengun,C,HOU,72.0,33.301319,6.180556,1.069444,5.902778,3.611111,0.555556,2.9,14.000000
5,Marcus Smart,G,HOU,62.0,28.531909,2.983871,0.370968,2.193548,1.709677,1.564516,0.9,2.419355
6,Reed Sheppard,G,HOU,82.0,26.181992,3.378049,0.658537,2.560976,0.841463,2.768293,2.1,3.219512
7,Tari Eason,F,HOU,60.0,25.818417,1.500000,0.466667,4.200000,0.866667,1.550000,2.0,4.633333
8,Steven Adams,C,HOU,60.0,22.823906,1.500000,0.625000,4.093750,1.468750,0.000000,0.6,4.312500

HOU 9 man rotation

Guards
Amen Thompson              37.4 min  (G-F)
Fred VanVleet              35.2 min  (G)
Marcus Smart               28.5 min  (G)
Reed Sheppard              26.2 min  (G)
Guard total: 127.3 minutes

Forwards
Kevin Durant               36.4 min  (F)
Jabari Smith Jr.           35.1 min  (F)
Tari Eason                 25.8 min  (F)
Forward total: 97.4 minutes

Centers
Alperen Sengun             33.3 min  (C)
Steven Adams               22.8 min  (C)
Center total: 56.1 minutes
Total rotation minutes: 280.8
Position total:         280.8
Unassigned minutes:     0.0
IND Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
690,Tyrese Haliburton,G,IND,73.00000,33.567009,9.219178,0.671233,2.958904,2.589041,2.986301,2.900000,5.013699
451,Pascal Siakam,F,IND,73.00000,33.171801,3.806452,0.403226,5.193548,4.225806,1.693548,3.000000,12.483871
322,Kelly Oubre Jr.,F-G,IND,64.00000,31.486233,1.600000,0.480000,4.040000,2.220000,1.720000,2.400000,6.360000
26,Andrew Nembhard,G-F,IND,64.00000,31.326199,7.666667,0.140351,2.368421,3.385965,1.877193,2.000000,5.403509
212,Ivica Zubac,C,IND,68.00000,30.139549,2.187500,0.833333,7.229167,2.104167,0.000000,1.700000,11.791667
5,Aaron Nesmith,G-F,IND,65.00000,29.665556,1.911111,0.511111,3.088889,2.044444,2.333333,1.400000,3.688889
246,Jarace Walker,F,IND,76.00000,25.702412,2.526316,0.342105,4.500000,1.802632,1.750000,1.500000,3.868421
233,Jalen Slawson,F,IND,13.00000,23.888462,2.769231,1.076923,3.846154,0.923077,1.153846,0.800000,2.923077
608,Keion Brooks Jr.,NaN,IND,14.00000,23.698690,0.928571,0.714286,3.285714,1.571429,1.000000,NaN,0.000000
41,Ben Sheppard,G,IND,65.00000,21.391949,1.753846,0.092308,2.338462,0.600000,1.292308,1.300000,2.307692
255,Jay Huff,C,IND,82.00000,20.966382,1.475610,1.865854,3.060976,1.000000,1.451220,1.100000,4.048780
281,Johnny Furphy,G,IND,40.00000,18.372952,1.171429,0.200000,3.457143,0.485714,0.657143,1.000000,2.685714
465,Quenton Jackson,G,IND,49.00000,18.314796,2.857143,0.122449,1.755102,2.000000,0.857143,1.700000,4.204082
437,Obi Toppin,F,IND,40.00000,17.655208,2.291667,0.041667,3.875000,1.750000,1.541667,1.300000,4.750000
509,T.J. McConnell,G,IND,56.00000,17.187589,5.125000,0.178571,1.821429,0.446429,0.285714,1.100000,5.000000
340,Kobe Brown,F,IND,61.00000,15.776667,1.311475,0.196721,1.918033,0.770492,0.852459,1.100000,2.393443
357,Larry Nance Jr.,F-C,IND,35.00000,12.822000,0.971429,0.171429,1.828571,0.171429,0.600000,0.700000,1.714286
604,Braden Smith,G,IND,3.35041,9.943037,2.987338,0.124675,1.024433,0.680524,0.624073,0.619803,1.198956
624,M.J. Iraldi,NaN,IND,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
629,Cameron Hildreth,NaN,IND,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
639,Wade Taylor IV,NaN,IND,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 18
  -> Adding real player Jay Huff (C, 20.97 min) to fill C
     Removing Keion Brooks Jr. to make room.

IND 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Tyrese Haliburton,G,IND,73.0,33.567009,9.219178,0.671233,2.958904,2.589041,2.986301,2.9,5.013699
1,Pascal Siakam,F,IND,73.0,33.171801,3.806452,0.403226,5.193548,4.225806,1.693548,3.0,12.483871
2,Kelly Oubre Jr.,F-G,IND,64.0,31.486233,1.6,0.48,4.04,2.22,1.72,2.4,6.36
3,Andrew Nembhard,G-F,IND,64.0,31.326199,7.666667,0.140351,2.368421,3.385965,1.877193,2.0,5.403509
4,Ivica Zubac,C,IND,68.0,30.139549,2.1875,0.833333,7.229167,2.104167,0.0,1.7,11.791667
5,Aaron Nesmith,G-F,IND,65.0,29.665556,1.911111,0.511111,3.088889,2.044444,2.333333,1.4,3.688889
6,Jarace Walker,F,IND,76.0,25.702412,2.526316,0.342105,4.5,1.802632,1.75,1.5,3.868421
7,Jalen Slawson,F,IND,13.0,23.888462,2.769231,1.076923,3.846154,0.923077,1.153846,0.8,2.923077
8,Jay Huff,C,IND,82.0,20.966382,1.47561,1.865854,3.060976,1.0,1.45122,1.1,4.04878

IND 9 man rotation

Guards
Tyrese Haliburton          33.6 min  (G)
Andrew Nembhard            31.3 min  (G-F)
Aaron Nesmith              29.7 min  (G-F)
Guard total: 94.6 minutes

Forwards
Pascal Siakam              33.2 min  (F)
Kelly Oubre Jr.            31.5 min  (F-G)
Jarace Walker              25.7 min  (F)
Jalen Slawson              23.9 min  (F)
Forward total: 114.2 minutes

Centers
Ivica Zubac                30.1 min  (C)
Jay Huff                   21.0 min  (C)
Center total: 51.1 minutes
Total rotation minutes: 259.9
Position total:         259.9
Unassigned minutes:     0.0
LAC Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
56,Brandon Ingram,F,LAC,77.000000,33.816407,3.688312,0.714286,4.766234,3.792208,1.753247,3.500000,7.324675
124,Darius Garland,G,LAC,71.000000,29.872815,6.688889,0.177778,1.977778,2.333333,2.711111,2.500000,7.022222
480,Rui Hachimura,F,LAC,68.000000,28.331838,0.838235,0.308824,2.720588,0.735294,1.705882,2.000000,3.264706
52,Bradley Beal,G,LAC,65.000000,28.000000,2.315644,0.000000,0.694693,1.389387,1.620951,2.084080,4.168160
345,Kris Dunn,G,LAC,82.000000,27.195122,3.597561,0.170732,2.597561,0.756098,0.975610,1.500000,3.487805
142,Derrick Jones Jr.,F,LAC,50.000000,26.990167,1.380000,1.000000,2.240000,1.420000,1.100000,2.000000,5.280000
390,Max Strus,G-F,LAC,75.000000,24.024583,2.000000,0.000000,4.666667,0.583333,2.750000,1.000000,2.333333
291,Jordan Miller,G,LAC,60.000000,22.079667,2.266667,0.183333,2.200000,2.266667,0.633333,1.800000,5.600000
61,Brook Lopez,C,LAC,75.000000,21.803644,1.293333,1.160000,3.013333,0.746667,1.520000,1.300000,2.800000
342,Kobe Sanders,G,LAC,68.000000,19.873775,1.602941,0.147059,1.823529,0.838235,1.176471,1.100000,2.411765
626,Keaton Wagler,G,LAC,7.515614,18.974911,4.195638,0.135339,1.626933,1.303615,1.132571,1.350155,2.747508
423,Nicolas Batum,G-F,LAC,74.000000,17.494527,0.864865,0.310811,2.175676,0.121622,1.243243,0.600000,0.027027
207,Isaiah Jackson,F,LAC,55.000000,16.514758,0.945455,0.890909,3.218182,1.236364,0.000000,1.500000,5.490909
673,Jamarion Sharp,C,LAC,17.852776,16.330606,1.469943,1.179356,2.749325,0.999390,0.234866,0.580181,4.401364
232,Jalen Pickett,G,LAC,50.000000,16.129600,2.300000,0.100000,1.920000,0.300000,0.980000,0.700000,1.440000
186,Gradey Dick,G-F,LAC,76.000000,14.035373,0.671053,0.092105,1.381579,1.013158,0.736842,1.600000,2.263158
663,Nick Martinelli,F,LAC,2.532364,11.650359,0.461872,0.201768,0.641277,0.499187,1.065034,0.710408,1.622055
566,Yuki Kawamura,G,LAC,18.000000,11.612222,2.611111,0.000000,1.444444,0.944444,0.611111,0.800000,0.666667
631,Baba Miller,F,LAC,1.527396,10.921566,0.788624,0.252302,1.964810,0.612629,0.159389,0.600627,1.755319
565,Yanic Konan Niederhäuser,C,LAC,41.000000,10.333618,0.292683,0.731707,1.951220,1.146341,0.024390,0.400000,3.073171
74,Cam Christie,G,LAC,55.000000,8.722727,0.563636,0.054545,1.072727,0.690909,0.218182,0.700000,1.272727
543,TyTy Washington Jr.,G,LAC,16.000000,5.508021,1.062500,0.187500,0.312500,0.000000,0.187500,0.300000,0.750000
280,Johni Broome,F,LAC,11.000000,4.978333,0.363636,0.181818,0.818182,0.181818,0.000000,0.200000,0.727273
434,Norchad Omier,F,LAC,6.000000,3.944444,0.333333,0.000000,0.500000,0.500000,0.000000,0.300000,2.333333
605,Narcisse Ngoy,NaN,LAC,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 24
  -> Adding real player Jamarion Sharp (C, 16.33 min) to fill C
     Removing Jordan Miller to make room.

LAC 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Brandon Ingram,F,LAC,77.0,33.816407,3.688312,0.714286,4.766234,3.792208,1.753247,3.5,7.324675
1,Darius Garland,G,LAC,71.0,29.872815,6.688889,0.177778,1.977778,2.333333,2.711111,2.5,7.022222
2,Rui Hachimura,F,LAC,68.0,28.331838,0.838235,0.308824,2.720588,0.735294,1.705882,2.0,3.264706
3,Bradley Beal,G,LAC,65.0,28.000000,2.315644,0.0,0.694693,1.389387,1.620951,2.08408,4.16816
4,Kris Dunn,G,LAC,82.0,27.195122,3.597561,0.170732,2.597561,0.756098,0.97561,1.5,3.487805
5,Derrick Jones Jr.,F,LAC,50.0,26.990167,1.38,1.0,2.24,1.42,1.1,2.0,5.28
6,Max Strus,G-F,LAC,75.0,24.024583,2.0,0.0,4.666667,0.583333,2.75,1.0,2.333333
7,Brook Lopez,C,LAC,75.0,21.803644,1.293333,1.16,3.013333,0.746667,1.52,1.3,2.8
8,Jamarion Sharp,C,LAC,17.852776,16.330606,1.469943,1.179356,2.749325,0.99939,0.234866,0.580181,4.401364

LAC 9 man rotation

Guards
Darius Garland             29.9 min  (G)
Bradley Beal               28.0 min  (G)
Kris Dunn                  27.2 min  (G)
Max Strus                  24.0 min  (G-F)
Guard total: 109.1 minutes

Forwards
Brandon Ingram             33.8 min  (F)
Rui Hachimura              28.3 min  (F)
Derrick Jones Jr.          27.0 min  (F)
Forward total: 89.1 minutes

Centers
Brook Lopez                21.8 min  (C)
Jamarion Sharp             16.3 min  (C)
Center total: 38.1 minutes
Total rotation minutes: 236.4
Position total:         236.4
Unassigned minutes:     0.0
LAL Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
368,Luka Dončić,F-G,LAL,60.000000,35.759401,8.281250,0.531250,7.093750,7.859375,3.968750,4.400000,10.468750
36,Austin Reaves,G,LAL,60.000000,34.542157,5.490196,0.392157,4.058824,6.333333,2.313725,3.400000,9.215686
691,Walker Kessler,C,LAL,55.000000,30.005517,1.672414,2.379310,7.603448,1.362069,0.103448,1.200000,0.689655
464,Quentin Grimes,G,LAL,75.000000,29.409622,3.253333,0.373333,3.026667,2.653333,1.693333,2.600000,5.146667
226,Jake LaRavia,F,LAL,82.000000,25.139878,1.768293,0.463415,2.560976,1.414634,0.951220,1.500000,3.926829
105,Collin Sexton,G,LAL,68.000000,23.723578,3.279412,0.147059,1.676471,3.205882,1.647059,2.100000,6.558824
571,Ziaire Williams,F,LAL,56.000000,22.879762,1.071429,0.375000,1.857143,2.125000,1.535714,2.600000,3.285714
489,Sandro Mamukelashvili,F-C,LAL,80.000000,21.883646,1.887500,0.512500,3.587500,1.475000,1.437500,1.900000,5.325000
334,Kevon Looney,F,LAL,40.000000,20.000000,2.211478,0.650435,4.553043,0.455304,0.130087,0.546365,2.861913
248,Jarred Vanderbilt,F,LAL,65.000000,17.349872,1.292308,0.292308,3.261538,0.507692,0.446154,0.900000,2.553846
387,Matisse Thybulle,G-F,LAL,657.000000,15.988333,0.900000,0.533333,1.400000,0.700000,1.233333,1.900000,1.400000
218,Jaden Hardy,G,LAL,57.000000,15.756082,1.017544,0.105263,1.245614,0.964912,1.824561,1.300000,2.140351
665,Cameron Carr,G-F,LAL,8.433491,11.532944,0.965672,0.167484,1.034879,0.568151,0.914472,0.829912,1.295893
117,Dalton Knecht,F,LAL,54.000000,10.239414,0.388889,0.203704,1.129630,0.296296,0.703704,0.600000,1.629630
588,Arthur Kaluma,F,LAL,26.275908,9.332187,0.663366,0.107019,1.092130,0.538533,0.330441,0.703887,1.701611
60,Bronny James,G,LAL,42.000000,8.940278,1.214286,0.095238,0.428571,0.142857,0.523810,0.500000,0.904762
674,AK Okereke,F,LAL,4.445592,6.250069,0.559232,0.151800,0.858619,0.712393,0.222289,0.269080,1.115389
10,Adou Thiero,G,LAL,25.000000,5.956133,0.400000,0.080000,0.760000,0.560000,0.040000,0.400000,1.200000
90,Chris Mañon,G,LAL,9.000000,5.120556,0.333333,0.222222,0.888889,0.333333,0.000000,0.400000,0.444444

Available players: 19

LAL 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Luka Dončić,F-G,LAL,60.0,35.759401,8.281250,0.531250,7.093750,7.859375,3.968750,4.400000,10.468750
1,Austin Reaves,G,LAL,60.0,34.542157,5.490196,0.392157,4.058824,6.333333,2.313725,3.400000,9.215686
2,Walker Kessler,C,LAL,55.0,30.005517,1.672414,2.379310,7.603448,1.362069,0.103448,1.200000,0.689655
3,Quentin Grimes,G,LAL,75.0,29.409622,3.253333,0.373333,3.026667,2.653333,1.693333,2.600000,5.146667
4,Jake LaRavia,F,LAL,82.0,25.139878,1.768293,0.463415,2.560976,1.414634,0.951220,1.500000,3.926829
5,Collin Sexton,G,LAL,68.0,23.723578,3.279412,0.147059,1.676471,3.205882,1.647059,2.100000,6.558824
6,Ziaire Williams,F,LAL,56.0,22.879762,1.071429,0.375000,1.857143,2.125000,1.535714,2.600000,3.285714
7,Sandro Mamukelashvili,F-C,LAL,80.0,21.883646,1.887500,0.512500,3.587500,1.475000,1.437500,1.900000,5.325000
8,Kevon Looney,F,LAL,40.0,20.000000,2.211478,0.650435,4.553043,0.455304,0.130087,0.546365,2.861913

LAL 9 man rotation

Guards
Austin Reaves              34.5 min  (G)
Quentin Grimes             29.4 min  (G)
Collin Sexton              23.7 min  (G)
Guard total: 87.7 minutes

Forwards
Luka Dončić                35.8 min  (F-G)
Jake LaRavia               25.1 min  (F)
Ziaire Williams            22.9 min  (F)
Sandro Mamukelashvili      21.9 min  (F-C)
Kevon Looney               20.0 min  (F)
Forward total: 125.7 minutes

Centers
Walker Kessler             30.0 min  (C)
Center total: 30.0 minutes
Total rotation minutes: 243.3
Position total:         243.3
Unassigned minutes:     0.0
MEM Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
83,Cedric Coward,G,MEM,65.000000,30.000000,3.210370,0.506901,5.275520,2.628373,1.745991,2.095189,7.434541
264,Jerami Grant,F,MEM,71.000000,29.738626,2.140351,0.631579,2.508772,4.596491,2.385965,2.800000,6.280702
590,Cameron Boozer,F-C,MEM,60.000000,28.000000,2.553907,0.235823,5.716168,2.071308,1.431762,1.757509,6.800576
258,Jaylen Wells,F,MEM,69.000000,26.386111,1.608696,0.130435,2.304348,1.942029,1.869565,1.900000,3.594203
75,Cam Spencer,G,MEM,72.000000,23.811829,5.555556,0.152778,1.986111,1.750000,2.027778,1.800000,2.083333
346,Kris Murray,F,MEM,57.000000,23.389649,1.421053,0.385965,2.035088,0.684211,0.596491,1.100000,3.333333
211,Isaiah Stewart,F-C,MEM,58.000000,22.709224,1.137931,1.603448,3.344828,1.706897,0.689655,1.600000,6.172414
542,Ty Jerome,G-F,MEM,50.000000,22.579222,5.666667,0.266667,2.066667,3.266667,2.800000,2.700000,6.666667
222,Jahmai Mashack,G,MEM,31.000000,21.714570,2.225806,0.451613,1.870968,0.612903,0.612903,1.000000,3.741935
693,Zach Edey,C,MEM,66.000000,21.450985,0.984848,1.287879,4.787879,1.363636,0.272727,1.100000,1.818182
177,GG Jackson,F,MEM,55.000000,21.413909,1.472727,0.800000,3.381818,2.036364,1.163636,2.000000,6.763636
493,Scotty Pippen Jr.,G,MEM,10.000000,21.186667,4.700000,0.400000,1.400000,1.800000,1.000000,2.500000,5.800000
558,Walter Clayton Jr.,G,MEM,69.000000,20.442536,4.043478,0.275362,1.652174,1.579710,1.086957,0.900000,2.521739
251,Javon Small,G,MEM,41.000000,20.241667,3.682927,0.219512,2.243902,1.658537,1.463415,1.800000,3.317073
111,D'Angelo Russell,G,MEM,26.000000,19.029808,4.000000,0.076923,2.038462,1.653846,1.269231,1.500000,3.307692
514,Taylor Hendricks,F,MEM,59.000000,18.957034,0.932203,0.508475,2.644068,0.830508,1.067797,1.200000,3.288136
440,Olivier-Maxence Prosper,F,MEM,53.000000,18.558333,0.962264,0.245283,2.415094,1.622642,1.132075,2.000000,4.905660
466,Quinten Post,C,MEM,67.000000,17.301468,1.402985,0.522388,3.000000,0.507463,1.388060,0.800000,2.746269
393,Micah Peavy,G-F,MEM,61.000000,14.966148,1.000000,0.147541,1.163934,0.360656,0.459016,1.300000,2.426230
289,Jordan Hawkins,G,MEM,51.000000,13.568137,0.823529,0.196078,1.333333,0.450980,0.921569,1.000000,1.058824
633,Karim Lopez,F,MEM,7.604937,11.770597,1.164033,0.218574,1.863946,0.705514,0.252397,0.551883,1.913994
636,Richie Saunders,NaN,MEM,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 21

MEM 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Cedric Coward,G,MEM,65.0,30.000000,3.210370,0.506901,5.275520,2.628373,1.745991,2.095189,7.434541
1,Jerami Grant,F,MEM,71.0,29.738626,2.140351,0.631579,2.508772,4.596491,2.385965,2.800000,6.280702
2,Cameron Boozer,F-C,MEM,60.0,28.000000,2.553907,0.235823,5.716168,2.071308,1.431762,1.757509,6.800576
3,Jaylen Wells,F,MEM,69.0,26.386111,1.608696,0.130435,2.304348,1.942029,1.869565,1.900000,3.594203
4,Cam Spencer,G,MEM,72.0,23.811829,5.555556,0.152778,1.986111,1.750000,2.027778,1.800000,2.083333
5,Kris Murray,F,MEM,57.0,23.389649,1.421053,0.385965,2.035088,0.684211,0.596491,1.100000,3.333333
6,Isaiah Stewart,F-C,MEM,58.0,22.709224,1.137931,1.603448,3.344828,1.706897,0.689655,1.600000,6.172414
7,Ty Jerome,G-F,MEM,50.0,22.579222,5.666667,0.266667,2.066667,3.266667,2.800000,2.700000,6.666667
8,Jahmai Mashack,G,MEM,31.0,21.714570,2.225806,0.451613,1.870968,0.612903,0.612903,1.000000,3.741935

MEM 9 man rotation

Guards
Cedric Coward              30.0 min  (G)
Cam Spencer                23.8 min  (G)
Ty Jerome                  22.6 min  (G-F)
Jahmai Mashack             21.7 min  (G)
Guard total: 98.1 minutes

Forwards
Jerami Grant               29.7 min  (F)
Cameron Boozer             28.0 min  (F-C)
Jaylen Wells               26.4 min  (F)
Kris Murray                23.4 min  (F)
Isaiah Stewart             22.7 min  (F-C)
Forward total: 130.2 minutes

Centers
Center total: 0.0 minutes
Total rotation minutes: 228.3
Position total:         228.3
Unassigned minutes:     0.0
MIA Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
184,Giannis Antetokounmpo,F,MIA,70.000000,33.000000,6.223839,0.762103,8.065587,7.366993,0.476314,4.686932,21.338876
38,Bam Adebayo,C-F,MIA,73.000000,32.392945,3.178082,0.671233,7.986301,4.506849,1.739726,3.500000,9.095890
27,Andrew Wiggins,F,MIA,68.000000,30.332328,2.676471,1.014706,3.147059,1.867647,2.029412,2.700000,6.205882
127,Davion Mitchell,G,MIA,70.000000,28.575071,6.471429,0.157143,2.214286,0.600000,1.285714,1.400000,4.485714
520,Tim Hardaway Jr.,G-F,MIA,80.000000,26.591250,1.350000,0.125000,2.362500,1.987500,2.800000,1.500000,1.900000
460,Pelle Larsson,G,MIA,70.000000,26.416333,3.371429,0.228571,2.500000,2.628571,0.885714,1.900000,6.057143
48,Bobby Portis Jr.,F,MIA,67.000000,24.168856,1.567164,0.179104,5.059701,0.716418,2.014925,2.000000,3.880597
339,Klay Thompson,G,MIA,69.000000,21.693188,1.391304,0.318841,1.811594,0.521739,2.927536,1.500000,1.246377
426,Nikola Jović,F,MIA,47.000000,17.191879,2.170213,0.361702,2.723404,1.468085,0.957447,1.300000,2.893617
500,Simone Fontecchio,F,MIA,70.000000,16.749571,1.442857,0.128571,2.214286,1.228571,1.757143,1.200000,1.942857
161,Dru Smith,G,MIA,70.000000,16.304405,2.571429,0.300000,1.585714,1.242857,0.542857,1.100000,2.571429
420,Nick Richards,C,MIA,48.000000,14.598125,0.333333,0.666667,3.458333,1.354167,0.104167,0.800000,4.000000
598,Tre Donaldson,G,MIA,6.407414,9.874297,1.145397,0.205908,0.864903,0.514954,0.487337,0.675216,1.270416
670,Ryan Conwell,G-F,MIA,10.267068,9.353064,0.764629,0.017614,1.361604,0.473933,0.848484,0.796294,1.158011
412,Myron Gardner,F,MIA,45.000000,9.122333,0.977778,0.177778,1.844444,0.422222,0.577778,0.500000,1.466667
327,Keshad Johnson,F,MIA,32.000000,8.735052,0.250000,0.250000,1.125000,0.656250,0.406250,1.000000,2.312500
223,Jahmir Young,G,MIA,14.000000,4.156786,0.642857,0.000000,0.142857,0.142857,0.214286,0.100000,0.857143
556,Vladislav Goldin,C,MIA,9.000000,2.662407,0.333333,0.333333,0.666667,0.111111,0.000000,0.000000,0.666667
534,Trevor Keels,G,MIA,8.000000,1.868333,0.000000,0.000000,0.250000,0.000000,0.250000,0.000000,0.250000
658,J'Vonne Hadley,NaN,MIA,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 19
  -> Adding real player Nick Richards (C, 14.60 min) to fill C
     Removing Nikola Jović to make room.

MIA 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Giannis Antetokounmpo,F,MIA,70.0,33.000000,6.223839,0.762103,8.065587,7.366993,0.476314,4.686932,21.338876
1,Bam Adebayo,C-F,MIA,73.0,32.392945,3.178082,0.671233,7.986301,4.506849,1.739726,3.5,9.09589
2,Andrew Wiggins,F,MIA,68.0,30.332328,2.676471,1.014706,3.147059,1.867647,2.029412,2.7,6.205882
3,Davion Mitchell,G,MIA,70.0,28.575071,6.471429,0.157143,2.214286,0.6,1.285714,1.4,4.485714
4,Tim Hardaway Jr.,G-F,MIA,80.0,26.591250,1.35,0.125,2.3625,1.9875,2.8,1.5,1.9
5,Pelle Larsson,G,MIA,70.0,26.416333,3.371429,0.228571,2.5,2.628571,0.885714,1.9,6.057143
6,Bobby Portis Jr.,F,MIA,67.0,24.168856,1.567164,0.179104,5.059701,0.716418,2.014925,2.0,3.880597
7,Klay Thompson,G,MIA,69.0,21.693188,1.391304,0.318841,1.811594,0.521739,2.927536,1.5,1.246377
8,Nick Richards,C,MIA,48.0,14.598125,0.333333,0.666667,3.458333,1.354167,0.104167,0.8,4.0

MIA 9 man rotation

Guards
Davion Mitchell            28.6 min  (G)
Tim Hardaway Jr.           26.6 min  (G-F)
Pelle Larsson              26.4 min  (G)
Klay Thompson              21.7 min  (G)
Guard total: 103.3 minutes

Forwards
Giannis Antetokounmpo      33.0 min  (F)
Andrew Wiggins             30.3 min  (F)
Bobby Portis Jr.           24.2 min  (F)
Forward total: 87.5 minutes

Centers
Bam Adebayo                32.4 min  (C-F)
Nick Richards              14.6 min  (C)
Center total: 47.0 minutes
Total rotation minutes: 237.8
Position total:         237.8
Unassigned minutes:     0.0
MIL Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
333,Kevin Porter Jr.,G-F,MIL,65.000000,33.184605,7.368421,0.500000,4.315789,3.605263,1.210526,3.000000,7.578947
485,Ryan Rollins,G,MIL,74.000000,32.101126,5.594595,0.418919,3.837838,1.689189,2.486486,2.100000,6.270270
545,Tyler Herro,G,MIL,33.000000,31.292525,4.121212,0.363636,4.363636,3.000000,2.545455,3.000000,8.424242
1,AJ Green,G,MIL,78.000000,29.101709,1.948718,0.102564,2.358974,0.679487,2.974359,1.200000,0.538462
225,Jaime Jaquez Jr.,G,MIL,75.000000,28.282800,4.693333,0.280000,3.720000,2.213333,0.773333,2.600000,9.893333
411,Myles Turner,C-F,MIL,71.000000,26.926808,1.450704,1.619718,4.267606,1.845070,2.070423,1.600000,3.239437
350,Kyle Kuzma,F,MIL,69.000000,26.170169,2.666667,0.405797,3.710145,1.956522,1.202899,2.000000,6.753623
319,Kel'el Ware,C,MIL,77.000000,25.000000,0.821682,1.232523,6.998972,1.041776,1.349907,1.581738,7.307103
108,Cormac Ryan,G,MIL,11.000000,24.607121,1.727273,0.272727,1.818182,2.181818,2.454545,3.500000,4.545455
183,Gary Trent Jr.,G,MIL,65.000000,21.190487,1.215385,0.046154,0.907692,0.615385,1.892308,1.100000,1.107692
268,Jericho Sims,C,MIL,67.000000,19.669179,1.552239,0.253731,3.328358,0.656716,0.000000,0.600000,4.328358
446,Ousmane Dieng,F,MIL,57.000000,19.288977,2.385965,0.298246,2.649123,0.561404,1.105263,1.200000,2.701754
80,Caris LeVert,G,MIL,60.000000,19.240250,2.650000,0.683333,1.566667,0.950000,1.000000,1.300000,3.033333
315,Kasparas Jakučionis,G,MIL,53.000000,17.823176,2.584906,0.132075,1.792453,1.094340,1.245283,1.200000,1.320755
579,Brayden Burries,G-F,MIL,13.148291,17.061041,1.273368,0.085849,1.470864,0.672418,0.916900,1.143972,1.951357
312,Kam Jones,G,MIL,37.000000,16.657432,3.216216,0.000000,1.216216,0.108108,0.594595,0.400000,2.324324
461,Pete Nance,F,MIL,47.000000,15.682943,1.021277,0.297872,2.085106,0.085106,1.063830,0.600000,2.127660
642,Nate Ament,F,MIL,5.860447,12.555256,0.792274,0.026020,0.920085,0.604662,0.519220,0.865989,1.448442
587,Malique Lewis,NaN,MIL,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
669,John Butler Jr.,NaN,MIL,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
672,Bogoljub Marković,NaN,MIL,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 18

MIL 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Kevin Porter Jr.,G-F,MIL,65.0,33.184605,7.368421,0.500000,4.315789,3.605263,1.210526,3.000000,7.578947
1,Ryan Rollins,G,MIL,74.0,32.101126,5.594595,0.418919,3.837838,1.689189,2.486486,2.100000,6.270270
2,Tyler Herro,G,MIL,33.0,31.292525,4.121212,0.363636,4.363636,3.000000,2.545455,3.000000,8.424242
3,AJ Green,G,MIL,78.0,29.101709,1.948718,0.102564,2.358974,0.679487,2.974359,1.200000,0.538462
4,Jaime Jaquez Jr.,G,MIL,75.0,28.282800,4.693333,0.280000,3.720000,2.213333,0.773333,2.600000,9.893333
5,Myles Turner,C-F,MIL,71.0,26.926808,1.450704,1.619718,4.267606,1.845070,2.070423,1.600000,3.239437
6,Kyle Kuzma,F,MIL,69.0,26.170169,2.666667,0.405797,3.710145,1.956522,1.202899,2.000000,6.753623
7,Kel'el Ware,C,MIL,77.0,25.000000,0.821682,1.232523,6.998972,1.041776,1.349907,1.581738,7.307103
8,Cormac Ryan,G,MIL,11.0,24.607121,1.727273,0.272727,1.818182,2.181818,2.454545,3.500000,4.545455

MIL 9 man rotation

Guards
Kevin Porter Jr.           33.2 min  (G-F)
Ryan Rollins               32.1 min  (G)
Tyler Herro                31.3 min  (G)
AJ Green                   29.1 min  (G)
Jaime Jaquez Jr.           28.3 min  (G)
Cormac Ryan                24.6 min  (G)
Guard total: 178.6 minutes

Forwards
Kyle Kuzma                 26.2 min  (F)
Forward total: 26.2 minutes

Centers
Myles Turner               26.9 min  (C-F)
Kel'el Ware                25.0 min  (C)
Center total: 51.9 minutes
Total rotation minutes: 256.7
Position total:         256.7
Unassigned minutes:     0.0
MIN Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
30,Anthony Edwards,G,MIN,61.000000,35.026120,3.704918,0.803279,4.360656,5.704918,3.360656,3.900000,9.639344
354,LaMelo Ball,G,MIN,75.000000,33.000000,8.407657,0.294432,4.612761,2.633527,4.449188,2.944316,6.739212
220,Jaden McDaniels,F,MIN,73.000000,31.731689,2.726027,1.000000,3.205479,2.013699,1.410959,2.500000,7.232877
479,Rudy Gobert,C,MIN,76.000000,31.316404,1.684211,1.631579,7.539474,2.092105,0.000000,1.600000,8.789474
153,Donte DiVincenzo,G,MIN,5.000000,30.000000,3.764981,0.408976,3.235718,0.938238,2.935001,1.775435,1.996763
285,Jonathan Kuminga,F,MIN,70.000000,30.000000,2.998206,0.397353,5.526813,3.214944,1.264304,2.470811,8.091544
37,Ayo Dosunmu,G,MIN,69.000000,27.261498,3.608696,0.260870,2.753623,1.840580,1.782609,2.300000,7.130435
99,Cody Williams,F,MIN,67.000000,24.336443,2.044776,0.388060,2.044776,1.253731,0.417910,1.400000,5.313433
51,Bones Hyland,G,MIN,71.000000,21.000000,3.354523,0.303335,1.855694,1.141965,2.069812,2.280362,2.854913
584,Trey Lyles,NaN,MIN,0.000000,19.558285,1.188406,0.333333,3.420290,0.811594,1.173913,NaN,0.000000
257,Jaylen Clark,G,MIN,68.000000,13.054461,0.632353,0.132353,0.970588,0.647059,0.485294,1.000000,1.882353
676,Isaiah Evans,G-F,MIN,5.378837,12.805644,0.774610,0.068161,0.975998,0.516934,0.952931,0.801083,1.445801
516,Terrence Shannon Jr,G-F,MIN,65.000000,12.504070,0.883721,0.023256,0.906977,1.302326,0.720930,0.800000,1.953488
475,Rocco Zikarsky,C,MIN,30.000000,12.000000,0.657835,1.644587,3.947008,1.315669,0.000000,0.000000,3.289173
172,Enrique Freeman,F,MIN,4.000000,9.302083,0.500000,0.750000,2.000000,0.750000,0.500000,0.800000,0.500000
573,Zyon Pullin,G,MIN,5.000000,8.516667,1.800000,0.000000,0.400000,0.800000,0.200000,0.400000,3.200000
272,Joan Beringer,F,MIN,40.000000,7.853292,0.300000,0.650000,1.175000,0.650000,0.000000,0.400000,3.250000
582,Trey Kaufman-Renn,NaN,MIN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 16
  -> Adding real player Rocco Zikarsky (C, 12.00 min) to fill C
     Removing Bones Hyland to make room.

MIN 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Anthony Edwards,G,MIN,61.0,35.026120,3.704918,0.803279,4.360656,5.704918,3.360656,3.9,9.639344
1,LaMelo Ball,G,MIN,75.0,33.000000,8.407657,0.294432,4.612761,2.633527,4.449188,2.944316,6.739212
2,Jaden McDaniels,F,MIN,73.0,31.731689,2.726027,1.0,3.205479,2.013699,1.410959,2.5,7.232877
3,Rudy Gobert,C,MIN,76.0,31.316404,1.684211,1.631579,7.539474,2.092105,0.0,1.6,8.789474
4,Donte DiVincenzo,G,MIN,5.0,30.000000,3.764981,0.408976,3.235718,0.938238,2.935001,1.775435,1.996763
5,Jonathan Kuminga,F,MIN,70.0,30.000000,2.998206,0.397353,5.526813,3.214944,1.264304,2.470811,8.091544
6,Ayo Dosunmu,G,MIN,69.0,27.261498,3.608696,0.26087,2.753623,1.84058,1.782609,2.3,7.130435
7,Cody Williams,F,MIN,67.0,24.336443,2.044776,0.38806,2.044776,1.253731,0.41791,1.4,5.313433
8,Rocco Zikarsky,C,MIN,30.0,12.000000,0.657835,1.644587,3.947008,1.315669,0.0,0.0,3.289173

MIN 9 man rotation

Guards
Anthony Edwards            35.0 min  (G)
LaMelo Ball                33.0 min  (G)
Donte DiVincenzo           30.0 min  (G)
Ayo Dosunmu                27.3 min  (G)
Guard total: 125.3 minutes

Forwards
Jaden McDaniels            31.7 min  (F)
Jonathan Kuminga           30.0 min  (F)
Cody Williams              24.3 min  (F)
Forward total: 86.1 minutes

Centers
Rudy Gobert                31.3 min  (C)
Rocco Zikarsky             12.0 min  (C)
Center total: 43.3 minutes
Total rotation minutes: 254.7
Position total:         254.7
Unassigned minutes:     0.0
NOP Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
537,Trey Murphy III,F,NOP,65.000000,35.464217,3.787879,0.363636,4.757576,3.303030,3.242424,4.000000,7.848485
486,Saddiq Bey,G-F,NOP,65.000000,31.188542,2.527778,0.097222,3.875000,3.444444,2.097222,2.700000,7.416667
42,Bennedict Mathurin,G-F,NOP,55.000000,30.000278,2.388889,0.240741,4.407407,5.407407,1.388889,3.000000,6.222222
572,Zion Williamson,F,NOP,60.000000,29.694570,3.209677,0.548387,3.677419,5.370968,0.016129,3.100000,15.387097
196,Herbert Jones,F,NOP,56.000000,28.363958,2.767857,0.482143,2.553571,0.892857,1.428571,1.300000,3.285714
137,Dejounte Murray,G,NOP,14.000000,27.815476,6.357143,0.214286,5.071429,2.785714,1.357143,2.400000,8.142857
265,Jeremiah Fears,G,NOP,82.000000,25.754919,3.402439,0.365854,2.926829,2.365854,1.231707,2.400000,7.439024
141,Derik Queen,C,NOP,81.000000,24.980000,3.679012,0.913580,5.382716,2.679012,0.283951,1.300000,7.407407
292,Jordan Poole,G,NOP,55.000000,23.929145,3.051282,0.384615,1.743590,2.512821,2.461538,1.600000,3.230769
64,Bryce McGowens,G,NOP,42.000000,20.950794,1.476190,0.190476,1.809524,1.761905,0.904762,1.500000,3.428571
567,Yves Missi,C,NOP,66.000000,19.652071,1.272727,1.530303,3.060606,0.863636,0.000000,0.700000,4.818182
132,DeAndre Jordan,C,NOP,12.000000,16.566667,0.916667,0.833333,4.166667,0.916667,0.000000,0.200000,3.500000
531,Trendon Watford,G-F,NOP,53.000000,16.296541,2.490566,0.415094,2.566038,1.132075,0.188679,0.600000,4.754717
314,Karlo Matković,F-C,NOP,62.000000,14.705753,0.806452,0.870968,2.532258,0.483871,0.612903,0.800000,3.322581
650,Malik Dia,F,NOP,6.901443,13.653548,0.866621,0.094585,1.480870,0.934064,0.262969,0.601486,1.590311
94,Christian Koloko,C,NOP,27.000000,13.209938,0.666667,0.851852,1.851852,0.370370,0.037037,0.500000,2.074074
667,Jaron Pierre Jr.,G,NOP,8.486126,9.735594,0.315899,0.081191,0.747366,0.512405,0.662427,0.402048,1.380933
2,AJ Johnson,G,NOP,48.000000,9.446528,0.979167,0.062500,0.854167,0.708333,0.250000,0.500000,1.875000
341,Kobe Bufkin,G,NOP,16.000000,7.467708,0.625000,0.187500,0.750000,0.687500,0.312500,0.300000,1.250000
71,Caleb Houstan,G,NOP,18.000000,4.192593,0.222222,0.055556,0.333333,0.166667,0.611111,0.400000,0.222222
612,Christian Shumate,NaN,NOP,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 20
  -> Adding real player Yves Missi (C, 19.65 min) to fill C
     Removing Jordan Poole to make room.

NOP 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Trey Murphy III,F,NOP,65.0,35.464217,3.787879,0.363636,4.757576,3.30303,3.242424,4.0,7.848485
1,Saddiq Bey,G-F,NOP,65.0,31.188542,2.527778,0.097222,3.875,3.444444,2.097222,2.7,7.416667
2,Bennedict Mathurin,G-F,NOP,55.0,30.000278,2.388889,0.240741,4.407407,5.407407,1.388889,3.0,6.222222
3,Zion Williamson,F,NOP,60.0,29.694570,3.209677,0.548387,3.677419,5.370968,0.016129,3.1,15.387097
4,Herbert Jones,F,NOP,56.0,28.363958,2.767857,0.482143,2.553571,0.892857,1.428571,1.3,3.285714
5,Dejounte Murray,G,NOP,14.0,27.815476,6.357143,0.214286,5.071429,2.785714,1.357143,2.4,8.142857
6,Jeremiah Fears,G,NOP,82.0,25.754919,3.402439,0.365854,2.926829,2.365854,1.231707,2.4,7.439024
7,Derik Queen,C,NOP,81.0,24.980000,3.679012,0.91358,5.382716,2.679012,0.283951,1.3,7.407407
8,Yves Missi,C,NOP,66.0,19.652071,1.272727,1.530303,3.060606,0.863636,0.0,0.7,4.818182

NOP 9 man rotation

Guards
Saddiq Bey                 31.2 min  (G-F)
Bennedict Mathurin         30.0 min  (G-F)
Dejounte Murray            27.8 min  (G)
Jeremiah Fears             25.8 min  (G)
Guard total: 114.8 minutes

Forwards
Trey Murphy III            35.5 min  (F)
Zion Williamson            29.7 min  (F)
Herbert Jones              28.4 min  (F)
Forward total: 93.5 minutes

Centers
Derik Queen                25.0 min  (C)
Yves Missi                 19.7 min  (C)
Center total: 44.6 minutes
Total rotation minutes: 252.9
Position total:         252.9
Unassigned minutes:     -0.0
NYK Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
228,Jalen Brunson,G,NYK,74.000000,34.997387,6.797297,0.108108,2.918919,4.783784,2.635135,3.400000,9.108108
436,OG Anunoby,F-G,NYK,67.000000,33.192114,2.164179,0.716418,3.970149,2.731343,2.343284,2.400000,6.417910
396,Mikal Bridges,G-F,NYK,82.000000,32.828476,3.707317,0.756098,2.841463,0.987805,1.902439,2.500000,5.926829
313,Karl-Anthony Towns,C-F,NYK,75.000000,30.957089,3.013333,0.533333,8.746667,4.760000,1.506667,2.900000,10.133333
297,Josh Hart,G,NYK,66.000000,30.205682,4.803030,0.257576,5.954545,1.363636,1.515152,2.300000,5.454545
400,Miles McBride,G,NYK,41.000000,26.342317,2.585366,0.219512,1.853659,0.902439,2.731707,1.800000,1.512195
616,Tyler Nickel,F-G,NYK,47.798954,23.060858,5.295606,1.026274,4.681950,2.855291,1.536689,2.127913,6.346894
356,Landry Shamet,G,NYK,51.000000,22.961863,1.411765,0.176471,1.352941,1.058824,2.019608,1.500000,1.803922
294,Jose Alvarado,G,NYK,69.000000,19.858502,3.391304,0.115942,2.101449,0.507246,1.463768,1.100000,2.376812
24,Andre Drummond,C,NYK,63.000000,19.535688,1.269841,0.777778,5.269841,0.841270,0.507937,0.800000,4.031746
287,Jordan Clarkson,G,NYK,72.000000,17.770301,1.333333,0.125000,0.902778,1.083333,0.972222,1.200000,4.138889
546,Tyler Kolek,G,NYK,62.000000,11.728414,2.741935,0.064516,1.322581,0.225806,0.709677,0.600000,1.870968
403,Mohamed Diawara,F,NYK,69.000000,9.190604,0.768116,0.086957,1.144928,0.260870,0.695652,0.700000,0.927536
332,Kevin McCullar Jr.,G,NYK,21.000000,7.380635,0.952381,0.000000,0.809524,0.095238,0.380952,0.300000,1.047619
449,Pacôme Dadiet,F,NYK,29.000000,4.681379,0.413793,0.034483,0.793103,0.310345,0.241379,0.500000,0.620690
623,Jack Kayil,NaN,NYK,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 15
  -> Adding real player Andre Drummond (C, 19.54 min) to fill C
     Removing Jose Alvarado to make room.

NYK 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Jalen Brunson,G,NYK,74.0,34.997387,6.797297,0.108108,2.918919,4.783784,2.635135,3.4,9.108108
1,OG Anunoby,F-G,NYK,67.0,33.192114,2.164179,0.716418,3.970149,2.731343,2.343284,2.4,6.41791
2,Mikal Bridges,G-F,NYK,82.0,32.828476,3.707317,0.756098,2.841463,0.987805,1.902439,2.5,5.926829
3,Karl-Anthony Towns,C-F,NYK,75.0,30.957089,3.013333,0.533333,8.746667,4.76,1.506667,2.9,10.133333
4,Josh Hart,G,NYK,66.0,30.205682,4.80303,0.257576,5.954545,1.363636,1.515152,2.3,5.454545
5,Miles McBride,G,NYK,41.0,26.342317,2.585366,0.219512,1.853659,0.902439,2.731707,1.8,1.512195
6,Tyler Nickel,F-G,NYK,47.798954,23.060858,5.295606,1.026274,4.68195,2.855291,1.536689,2.127913,6.346894
7,Landry Shamet,G,NYK,51.0,22.961863,1.411765,0.176471,1.352941,1.058824,2.019608,1.5,1.803922
8,Andre Drummond,C,NYK,63.0,19.535688,1.269841,0.777778,5.269841,0.84127,0.507937,0.8,4.031746

NYK 9 man rotation

Guards
Jalen Brunson              35.0 min  (G)
Mikal Bridges              32.8 min  (G-F)
Josh Hart                  30.2 min  (G)
Miles McBride              26.3 min  (G)
Landry Shamet              23.0 min  (G)
Guard total: 147.3 minutes

Forwards
OG Anunoby                 33.2 min  (F-G)
Tyler Nickel               23.1 min  (F-G)
Forward total: 56.3 minutes

Centers
Karl-Anthony Towns         31.0 min  (C-F)
Andre Drummond             19.5 min  (C)
Center total: 50.5 minutes
Total rotation minutes: 254.1
Position total:         254.1
Unassigned minutes:     0.0
OKC Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
497,Shai Gilgeous-Alexander,G,OKC,72.000000,33.219804,6.588235,0.764706,3.735294,7.941176,1.691176,4.700000,12.382353
87,Chet Holmgren,C-F,OKC,71.000000,28.945918,1.666667,1.898551,7.014493,3.260870,1.275362,3.200000,9.072464
236,Jalen Williams,G-F,OKC,70.000000,28.362525,5.484848,0.272727,3.818182,3.272727,0.696970,3.500000,10.000000
82,Cason Wallace,G,OKC,77.000000,26.572338,2.597403,0.363636,2.272727,0.714286,1.311688,1.700000,3.714286
11,Ajay Mitchell,G,OKC,65.000000,25.838567,3.614035,0.315789,2.631579,2.473684,1.070175,3.000000,7.438596
247,Jared McCain,G,OKC,66.000000,25.000000,1.940213,0.107790,2.457603,1.099454,2.134234,1.588819,3.794194
206,Isaiah Hartenstein,C-F,OKC,65.000000,24.200532,3.531915,0.765957,6.255319,1.361702,0.000000,1.400000,7.531915
259,Jaylin Williams,F,OKC,65.000000,24.000000,2.968588,0.789118,6.125061,1.371563,1.841276,1.343380,1.578237
14,Alex Caruso,G,OKC,65.000000,22.000000,2.371743,0.366542,2.738285,0.884013,1.142749,2.052636,2.932337
618,Aday Mara,C,OKC,65.000000,17.747492,1.747362,0.757319,2.737031,0.815315,0.243056,0.716071,2.731695
427,Nikola Topić,G,OKC,10.000000,16.008333,4.400000,0.000000,1.200000,0.200000,0.600000,0.500000,3.200000
324,Kenrich Williams,G-F,OKC,65.000000,15.270774,1.410714,0.089286,2.285714,0.589286,0.892857,1.500000,2.642857
641,Otega Oweh,G-F,OKC,7.367136,13.516317,0.708485,0.176423,0.761812,0.581976,0.419773,0.832162,1.798366
614,Josh Dix,G,OKC,0.762935,11.789050,1.050459,0.019533,0.884061,0.701760,0.711842,0.485696,1.599658
593,Thomas Sorber,C-F,OKC,0.482243,10.857376,0.676188,0.325107,1.891765,0.474893,0.039283,0.198295,1.867114
646,Bennett Stirtz,G,OKC,5.657040,9.068387,3.105727,0.080700,0.917621,0.956447,0.817749,0.677917,1.457793
62,Brooks Barnhizer,G,OKC,40.000000,8.697042,0.550000,0.125000,1.475000,0.175000,0.175000,0.400000,0.850000
613,Cristoph Tilly,NaN,OKC,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 17

OKC 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Shai Gilgeous-Alexander,G,OKC,72.0,33.219804,6.588235,0.764706,3.735294,7.941176,1.691176,4.700000,12.382353
1,Chet Holmgren,C-F,OKC,71.0,28.945918,1.666667,1.898551,7.014493,3.260870,1.275362,3.200000,9.072464
2,Jalen Williams,G-F,OKC,70.0,28.362525,5.484848,0.272727,3.818182,3.272727,0.696970,3.500000,10.000000
3,Cason Wallace,G,OKC,77.0,26.572338,2.597403,0.363636,2.272727,0.714286,1.311688,1.700000,3.714286
4,Ajay Mitchell,G,OKC,65.0,25.838567,3.614035,0.315789,2.631579,2.473684,1.070175,3.000000,7.438596
5,Jared McCain,G,OKC,66.0,25.000000,1.940213,0.107790,2.457603,1.099454,2.134234,1.588819,3.794194
6,Isaiah Hartenstein,C-F,OKC,65.0,24.200532,3.531915,0.765957,6.255319,1.361702,0.000000,1.400000,7.531915
7,Jaylin Williams,F,OKC,65.0,24.000000,2.968588,0.789118,6.125061,1.371563,1.841276,1.343380,1.578237
8,Alex Caruso,G,OKC,65.0,22.000000,2.371743,0.366542,2.738285,0.884013,1.142749,2.052636,2.932337

OKC 9 man rotation

Guards
Shai Gilgeous-Alexander    33.2 min  (G)
Jalen Williams             28.4 min  (G-F)
Cason Wallace              26.6 min  (G)
Ajay Mitchell              25.8 min  (G)
Jared McCain               25.0 min  (G)
Alex Caruso                22.0 min  (G)
Guard total: 161.0 minutes

Forwards
Jaylin Williams            24.0 min  (F)
Forward total: 24.0 minutes

Centers
Chet Holmgren              28.9 min  (C-F)
Isaiah Hartenstein         24.2 min  (C-F)
Center total: 53.1 minutes
Total rotation minutes: 238.1
Position total:         238.1
Unassigned minutes:     0.0
ORL Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
450,Paolo Banchero,F,ORL,72.000000,34.745625,5.180556,0.555556,7.208333,6.347222,1.166667,3.500000,10.444444
144,Desmond Bane,G,ORL,82.000000,33.610305,4.121951,0.451220,2.926829,3.829268,2.036585,3.000000,8.365854
176,Franz Wagner,F,ORL,65.000000,29.970686,3.323529,0.323529,3.941176,4.794118,1.411765,3.500000,10.647059
29,Anthony Black,G,ORL,64.000000,29.844531,3.687500,0.703125,3.078125,2.640625,1.562500,3.000000,7.093750
559,Wendell Carter Jr.,C-F,ORL,78.000000,29.337842,1.974359,0.628205,5.320513,2.538462,0.923077,1.400000,5.769231
428,Nikola Vučević,C,ORL,65.000000,28.408099,3.328125,0.640625,6.437500,1.203125,1.562500,1.900000,8.187500
235,Jalen Suggs,G,ORL,69.000000,27.606491,5.473684,0.701754,3.228070,1.754386,2.140351,2.500000,4.421053
540,Tristan da Silva,F,ORL,77.000000,24.668268,1.610390,0.324675,2.935065,1.090909,1.558442,1.500000,3.662338
270,Jevon Carter,G,ORL,53.000000,16.366824,1.641509,0.188679,1.415094,0.283019,1.471698,0.900000,0.716981
185,Goga Bitadze,C-F,ORL,65.000000,15.187604,1.312500,0.953125,2.859375,1.078125,0.031250,1.100000,4.687500
432,Noah Penda,G-F,ORL,59.000000,12.835169,1.186441,0.305085,2.033898,0.559322,0.508475,0.600000,1.661017
238,Jamal Cain,F,ORL,40.000000,12.149208,0.725000,0.100000,1.250000,0.975000,0.700000,1.400000,2.000000
668,Izaiyah Nelson,C-F,ORL,-1.416979,11.879996,0.926165,0.468848,2.076024,0.647268,0.127444,0.721308,2.652855
250,Jase Richardson,G,ORL,54.000000,10.865710,1.074074,0.037037,0.777778,0.611111,0.518519,1.100000,2.037037
284,Jonathan Isaac,F,ORL,52.000000,10.017179,0.423077,0.596154,1.711538,0.673077,0.134615,0.400000,1.423077
375,Malaki Branham,F,ORL,28.000000,9.838512,0.821429,0.107143,1.142857,1.000000,0.500000,0.900000,1.857143
213,JD Davison,G,ORL,28.000000,7.800595,1.250000,0.214286,1.107143,0.464286,0.285714,0.600000,1.071429
15,Alex Morales,G,ORL,4.000000,5.895833,1.000000,0.000000,0.500000,0.500000,0.000000,0.000000,1.000000
102,Colin Castleton,C,ORL,4.000000,5.345833,0.250000,0.000000,1.500000,0.250000,0.000000,0.000000,1.000000

Available players: 18

ORL 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Paolo Banchero,F,ORL,72.0,34.745625,5.180556,0.555556,7.208333,6.347222,1.166667,3.5,10.444444
1,Desmond Bane,G,ORL,82.0,33.610305,4.121951,0.451220,2.926829,3.829268,2.036585,3.0,8.365854
2,Franz Wagner,F,ORL,65.0,29.970686,3.323529,0.323529,3.941176,4.794118,1.411765,3.5,10.647059
3,Anthony Black,G,ORL,64.0,29.844531,3.687500,0.703125,3.078125,2.640625,1.562500,3.0,7.093750
4,Wendell Carter Jr.,C-F,ORL,78.0,29.337842,1.974359,0.628205,5.320513,2.538462,0.923077,1.4,5.769231
5,Nikola Vučević,C,ORL,65.0,28.408099,3.328125,0.640625,6.437500,1.203125,1.562500,1.9,8.187500
6,Jalen Suggs,G,ORL,69.0,27.606491,5.473684,0.701754,3.228070,1.754386,2.140351,2.5,4.421053
7,Tristan da Silva,F,ORL,77.0,24.668268,1.610390,0.324675,2.935065,1.090909,1.558442,1.5,3.662338
8,Jevon Carter,G,ORL,53.0,16.366824,1.641509,0.188679,1.415094,0.283019,1.471698,0.9,0.716981

ORL 9 man rotation

Guards
Desmond Bane               33.6 min  (G)
Anthony Black              29.8 min  (G)
Jalen Suggs                27.6 min  (G)
Jevon Carter               16.4 min  (G)
Guard total: 107.4 minutes

Forwards
Paolo Banchero             34.7 min  (F)
Franz Wagner               30.0 min  (F)
Tristan da Silva           24.7 min  (F)
Forward total: 89.4 minutes

Centers
Wendell Carter Jr.         29.3 min  (C-F)
Nikola Vučević             28.4 min  (C)
Center total: 57.7 minutes
Total rotation minutes: 254.6
Position total:         254.6
Unassigned minutes:     0.0
PHI Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
549,Tyrese Maxey,G,PHI,70.0,38.015976,6.585714,0.785714,3.800000,5.314286,3.142857,5.4,11.257143
553,VJ Edgecombe,G,PHI,75.0,34.977400,4.200000,0.520000,4.013333,1.973333,1.986667,2.6,6.293333
256,Jaylen Brown,G-F,PHI,71.0,34.406174,5.126761,0.380282,5.788732,6.000000,1.971831,3.9,12.535211
360,LeBron James,F,PHI,60.0,33.150917,7.200000,0.583333,5.350000,3.883333,1.283333,4.6,11.066667
275,Joel Embiid,C-F,PHI,65.0,31.595746,3.947368,1.210526,5.736842,7.526316,1.394737,2.6,9.947368
28,Anfernee Simons,G,PHI,60.0,24.944242,2.436364,0.145455,1.890909,1.254545,2.654545,1.7,3.600000
150,Dominick Barlow,F,PHI,71.0,23.781948,1.225352,0.746479,2.915493,1.323944,0.295775,1.5,5.380282
135,Dean Wade,F-C,PHI,59.0,22.333616,1.491525,0.389831,3.288136,0.457627,1.203390,0.7,1.627119
325,Kentavious Caldwell-Pope,G,PHI,51.0,21.324673,2.725490,0.156863,2.058824,1.431373,1.078431,1.1,2.274510
72,Caleb Love,G,PHI,49.0,20.665476,2.510204,0.081633,1.816327,0.734694,1.897959,1.7,3.224490
9,Adem Bona,F,PHI,71.0,17.382559,0.450704,1.154930,2.521127,1.126761,0.028169,0.9,3.633803
548,Tyrese Martin,F,PHI,46.0,16.882826,1.695652,0.130435,1.782609,0.413043,1.152174,1.2,2.173913
470,Rayan Rupert,G-F,PHI,64.0,16.758516,1.062500,0.140625,2.187500,0.656250,0.687500,1.1,2.281250
308,Justin Edwards,F,PHI,64.0,15.265911,1.250000,0.171875,1.062500,0.515625,1.046875,1.3,2.156250
378,MarJon Beauchamp,F,PHI,14.0,14.007976,1.071429,0.285714,1.785714,0.928571,1.142857,1.6,2.142857
216,Jabari Walker,F,PHI,64.0,11.901068,0.531250,0.203125,1.875000,0.781250,0.500000,0.8,2.000000
33,Ariel Hukporti,C,PHI,54.0,9.221512,0.537037,0.481481,1.907407,0.481481,0.018519,0.2,1.629630
351,Kyle Lowry,G,PHI,14.0,8.431429,0.785714,0.142857,0.642857,0.357143,0.285714,0.0,0.000000
149,Dillon Jones,F,PHI,7.0,5.626905,0.571429,0.000000,0.714286,0.571429,0.142857,0.3,0.285714
574,Labaron Philon,NaN,PHI,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,Tacko Fall,NaN,PHI,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,Saint Thomas,NaN,PHI,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
638,Duke Miles,NaN,PHI,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
671,Jameer Nelson Jr.,NaN,PHI,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 19

PHI 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Tyrese Maxey,G,PHI,70.0,38.015976,6.585714,0.785714,3.800000,5.314286,3.142857,5.4,11.257143
1,VJ Edgecombe,G,PHI,75.0,34.977400,4.200000,0.520000,4.013333,1.973333,1.986667,2.6,6.293333
2,Jaylen Brown,G-F,PHI,71.0,34.406174,5.126761,0.380282,5.788732,6.000000,1.971831,3.9,12.535211
3,LeBron James,F,PHI,60.0,33.150917,7.200000,0.583333,5.350000,3.883333,1.283333,4.6,11.066667
4,Joel Embiid,C-F,PHI,65.0,31.595746,3.947368,1.210526,5.736842,7.526316,1.394737,2.6,9.947368
5,Anfernee Simons,G,PHI,60.0,24.944242,2.436364,0.145455,1.890909,1.254545,2.654545,1.7,3.600000
6,Dominick Barlow,F,PHI,71.0,23.781948,1.225352,0.746479,2.915493,1.323944,0.295775,1.5,5.380282
7,Dean Wade,F-C,PHI,59.0,22.333616,1.491525,0.389831,3.288136,0.457627,1.203390,0.7,1.627119
8,Kentavious Caldwell-Pope,G,PHI,51.0,21.324673,2.725490,0.156863,2.058824,1.431373,1.078431,1.1,2.274510

PHI 9 man rotation

Guards
Tyrese Maxey               38.0 min  (G)
VJ Edgecombe               35.0 min  (G)
Jaylen Brown               34.4 min  (G-F)
Anfernee Simons            24.9 min  (G)
Kentavious Caldwell-Pope   21.3 min  (G)
Guard total: 153.7 minutes

Forwards
LeBron James               33.2 min  (F)
Dominick Barlow            23.8 min  (F)
Dean Wade                  22.3 min  (F-C)
Forward total: 79.3 minutes

Centers
Joel Embiid                31.6 min  (C-F)
Center total: 31.6 minutes
Total rotation minutes: 264.5
Position total:         264.5
Unassigned minutes:     0.0
PHX Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
145,Devin Booker,G,PHX,75.000000,33.537969,6.031250,0.281250,3.125000,7.093750,1.906250,4.400000,8.593750
398,Miles Bridges,F,PHX,77.000000,31.003009,3.194805,0.441558,4.870130,2.701299,1.922078,2.300000,8.233766
148,Dillon Brooks,G-F,PHX,65.000000,30.385417,1.767857,0.160714,2.857143,3.035714,2.267857,3.100000,7.000000
103,Collin Gillespie,G,PHX,80.000000,28.522521,4.637500,0.200000,2.975000,0.950000,2.900000,2.100000,2.050000
336,Khaman Maluach,C,PHX,65.000000,28.000000,0.408734,2.248038,5.722280,1.498692,0.340612,1.253452,6.812238
382,Mark Williams,C,PHX,65.000000,28.000000,1.146852,1.087532,5.773807,2.669397,0.019773,3.084637,10.875322
230,Jalen Green,G,PHX,65.000000,25.885156,2.843750,0.250000,3.125000,2.031250,2.218750,2.600000,6.500000
288,Jordan Goodwin,G,PHX,70.000000,22.453952,2.157143,0.200000,2.900000,0.557143,1.600000,1.800000,3.028571
445,Oso Ighodaro,F,PHX,82.000000,22.053293,2.256098,0.695122,3.414634,0.646341,0.000000,0.800000,5.682927
370,Luke Kennard,G,PHX,78.000000,21.544573,2.230769,0.102564,1.923077,0.807692,1.500000,1.600000,2.205128
482,Ryan Dunn,F,PHX,70.000000,19.360643,1.457143,0.414286,2.828571,0.328571,0.800000,1.200000,3.057143
453,Pat Spencer,G,PHX,66.000000,18.620101,3.515152,0.075758,1.621212,0.666667,0.909091,1.100000,3.151515
241,Jamaree Bouyea,G,PHX,46.000000,14.001268,1.782609,0.347826,1.391304,0.521739,0.500000,1.500000,3.173913
195,Haywood Highsmith,F,PHX,7.000000,12.970000,1.000000,0.000000,1.000000,0.857143,1.142857,1.400000,1.142857
617,Koa Peat,F,PHX,4.140121,12.798117,0.827546,0.119540,1.455756,0.672932,0.218887,0.660083,3.047993
468,Rasheer Fleming,F,PHX,55.000000,12.243667,0.290909,0.381818,1.218182,0.345455,0.818182,0.900000,1.454545
22,Amir Coffey,G-F,PHX,46.000000,10.663080,0.586957,0.108696,0.826087,0.478261,0.369565,0.700000,1.260870
68,CJ Huntley,F,PHX,4.000000,10.100000,0.500000,0.000000,0.750000,0.000000,0.000000,0.000000,2.500000
209,Isaiah Livers,F,PHX,36.000000,9.648889,0.583333,0.222222,1.166667,0.250000,0.333333,0.300000,0.500000
343,Koby Brea,G,PHX,12.000000,6.988889,0.833333,0.000000,0.583333,0.166667,1.083333,0.800000,0.333333

Available players: 20

PHX 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Devin Booker,G,PHX,75.0,33.537969,6.031250,0.281250,3.125000,7.093750,1.906250,4.400000,8.593750
1,Miles Bridges,F,PHX,77.0,31.003009,3.194805,0.441558,4.870130,2.701299,1.922078,2.300000,8.233766
2,Dillon Brooks,G-F,PHX,65.0,30.385417,1.767857,0.160714,2.857143,3.035714,2.267857,3.100000,7.000000
3,Collin Gillespie,G,PHX,80.0,28.522521,4.637500,0.200000,2.975000,0.950000,2.900000,2.100000,2.050000
4,Khaman Maluach,C,PHX,65.0,28.000000,0.408734,2.248038,5.722280,1.498692,0.340612,1.253452,6.812238
5,Mark Williams,C,PHX,65.0,28.000000,1.146852,1.087532,5.773807,2.669397,0.019773,3.084637,10.875322
6,Jalen Green,G,PHX,65.0,25.885156,2.843750,0.250000,3.125000,2.031250,2.218750,2.600000,6.500000
7,Jordan Goodwin,G,PHX,70.0,22.453952,2.157143,0.200000,2.900000,0.557143,1.600000,1.800000,3.028571
8,Oso Ighodaro,F,PHX,82.0,22.053293,2.256098,0.695122,3.414634,0.646341,0.000000,0.800000,5.682927

PHX 9 man rotation

Guards
Devin Booker               33.5 min  (G)
Dillon Brooks              30.4 min  (G-F)
Collin Gillespie           28.5 min  (G)
Jalen Green                25.9 min  (G)
Jordan Goodwin             22.5 min  (G)
Guard total: 140.8 minutes

Forwards
Miles Bridges              31.0 min  (F)
Oso Ighodaro               22.1 min  (F)
Forward total: 53.1 minutes

Centers
Khaman Maluach             28.0 min  (C)
Mark Williams              28.0 min  (C)
Center total: 56.0 minutes
Total rotation minutes: 249.8
Position total:         249.8
Unassigned minutes:     0.0
POR Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
679,Damian Lillard,G,POR,40.0,30.000000,5.877097,0.143344,3.483255,5.189047,2.823873,1.579649,4.816353
138,Deni Avdija,F,POR,40.0,30.000000,6.028958,0.559247,5.183267,6.670046,1.705022,3.150881,9.411722
301,Jrue Holiday,G,POR,53.0,29.441541,6.075472,0.113208,3.283019,1.660377,2.584906,2.600000,6.000000
151,Donovan Clingan,C,POR,77.0,27.190087,2.103896,1.688312,7.077922,1.792208,1.090909,2.000000,6.935065
526,Toumani Camara,F,POR,60.0,27.000000,1.987012,0.345997,2.886604,0.958906,2.164953,1.702306,3.222716
496,Shaedon Sharpe,G,POR,50.0,26.000000,2.332628,0.106029,2.933457,2.739071,1.820157,3.357571,8.411599
683,Ja Morant,G,POR,30.0,25.000000,5.990350,0.197484,2.814148,4.328192,1.448216,3.044546,3.192659
557,Vít Krejčí,G,POR,65.0,21.416923,1.538462,0.276923,1.800000,0.584615,1.969231,1.500000,1.753846
394,Micah Potter,C,POR,47.0,19.325887,1.468085,0.319149,3.723404,1.808511,1.510638,1.100000,3.234043
499,Sidy Cissoko,G,POR,75.0,19.134067,1.466667,0.333333,1.386667,0.773333,0.786667,0.900000,1.920000
474,Robert Williams III,C-F,POR,59.0,17.088362,1.016949,1.474576,4.644068,0.576271,0.152542,1.000000,5.491525
491,Scoot Henderson,G,POR,60.0,17.000000,2.546033,0.204592,1.409411,1.909525,1.295749,1.773130,2.955217
564,Yang Hansen,C,POR,43.0,14.000000,1.027032,0.466833,2.147430,1.307131,0.233416,0.602214,2.334163
47,Blake Wesley,G,POR,31.0,11.639301,2.000000,0.161290,1.000000,0.838710,0.322581,0.800000,2.774194
53,Branden Carlson,C,POR,42.0,11.623889,0.690476,0.642857,2.261905,0.357143,0.738095,0.700000,3.190476
267,Jeremy Sochan,F,POR,44.0,10.648902,0.909091,0.159091,1.590909,0.431818,0.250000,0.800000,2.409091
279,John Tonje,G,POR,6.0,6.983056,0.333333,0.000000,1.000000,0.666667,0.500000,0.800000,0.333333
92,Chris Youngblood,G,POR,34.0,5.443873,0.352941,0.088235,0.617647,0.264706,0.529412,0.400000,0.176471
261,Jayson Kent,F,POR,5.0,4.493333,0.000000,0.200000,1.000000,0.200000,0.200000,1.000000,1.200000

Available players: 19

POR 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Damian Lillard,G,POR,40.0,30.000000,5.877097,0.143344,3.483255,5.189047,2.823873,1.579649,4.816353
1,Deni Avdija,F,POR,40.0,30.000000,6.028958,0.559247,5.183267,6.670046,1.705022,3.150881,9.411722
2,Jrue Holiday,G,POR,53.0,29.441541,6.075472,0.113208,3.283019,1.660377,2.584906,2.600000,6.000000
3,Donovan Clingan,C,POR,77.0,27.190087,2.103896,1.688312,7.077922,1.792208,1.090909,2.000000,6.935065
4,Toumani Camara,F,POR,60.0,27.000000,1.987012,0.345997,2.886604,0.958906,2.164953,1.702306,3.222716
5,Shaedon Sharpe,G,POR,50.0,26.000000,2.332628,0.106029,2.933457,2.739071,1.820157,3.357571,8.411599
6,Ja Morant,G,POR,30.0,25.000000,5.990350,0.197484,2.814148,4.328192,1.448216,3.044546,3.192659
7,Vít Krejčí,G,POR,65.0,21.416923,1.538462,0.276923,1.800000,0.584615,1.969231,1.500000,1.753846
8,Micah Potter,C,POR,47.0,19.325887,1.468085,0.319149,3.723404,1.808511,1.510638,1.100000,3.234043

POR 9 man rotation

Guards
Damian Lillard             30.0 min  (G)
Jrue Holiday               29.4 min  (G)
Shaedon Sharpe             26.0 min  (G)
Ja Morant                  25.0 min  (G)
Vít Krejčí                 21.4 min  (G)
Guard total: 131.9 minutes

Forwards
Deni Avdija                30.0 min  (F)
Toumani Camara             27.0 min  (F)
Forward total: 57.0 minutes

Centers
Donovan Clingan            27.2 min  (C)
Micah Potter               19.3 min  (C)
Center total: 46.5 minutes
Total rotation minutes: 235.4
Position total:         235.4
Unassigned minutes:     0.0
SAC Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
318,Keegan Murray,F,SAC,30.000000,28.000000,1.341577,1.270967,3.495160,1.341577,1.094444,2.111218,5.295697
606,Darius Acuff Jr.,G,SAC,50.000000,28.000000,8.292160,0.232854,1.913874,1.950107,2.459994,2.008983,3.716395
680,Domantas Sabonis,F-C,SAC,30.000000,28.000000,4.876328,0.299727,8.127214,2.513096,0.749318,2.259481,2.513096
695,Zach LaVine,G,SAC,30.000000,28.000000,3.335280,0.129108,3.152378,2.528358,2.571393,2.706956,2.646706
392,Maxime Raynaud,C,SAC,74.000000,26.538919,1.351351,0.527027,5.594595,1.783784,0.324324,1.600000,9.108108
114,Daeqwon Plowden,G-F,SAC,32.000000,26.386510,1.281250,0.218750,2.000000,1.312500,1.937500,1.500000,3.500000
130,De'Andre Hunter,F-G,SAC,45.000000,26.121926,2.000000,0.133333,3.444444,2.755556,1.666667,2.100000,4.355556
429,Nique Clifford,G,SAC,75.000000,25.092333,2.386667,0.320000,2.893333,0.933333,1.026667,1.600000,3.706667
463,Precious Achiuwa,F,SAC,73.000000,23.906644,1.383562,0.684932,4.315068,1.054795,0.369863,1.800000,7.698630
377,Malik Monk,G,SAC,62.000000,21.994247,2.983871,0.387097,1.645161,1.516129,2.000000,2.100000,4.064516
577,Ben Simmons,NaN,SAC,51.000000,21.954771,5.588235,0.450980,3.803922,0.470588,0.000000,NaN,0.000000
165,Dylan Cardwell,C,SAC,44.000000,20.603144,1.409091,1.522727,4.204545,0.590909,0.045455,0.700000,4.500000
596,Emanuel Sharp,G,SAC,1.710429,15.119179,0.771946,0.047654,0.735053,0.778687,0.894821,1.464593,1.514144
660,Alex Karaban,F,SAC,5.341297,11.474184,0.938845,0.079476,1.013112,0.443195,1.426872,0.609979,1.262901
286,Jonathan Mogbo,F,SAC,40.000000,6.222417,0.625000,0.200000,1.225000,0.225000,0.000000,0.200000,1.250000
656,Adam Flagler,NaN,SAC,37.000000,5.485541,0.324324,0.081081,0.540541,0.027027,0.378378,NaN,0.000000

Available players: 16

SAC 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Keegan Murray,F,SAC,30.0,28.000000,1.341577,1.270967,3.495160,1.341577,1.094444,2.111218,5.295697
1,Darius Acuff Jr.,G,SAC,50.0,28.000000,8.292160,0.232854,1.913874,1.950107,2.459994,2.008983,3.716395
2,Domantas Sabonis,F-C,SAC,30.0,28.000000,4.876328,0.299727,8.127214,2.513096,0.749318,2.259481,2.513096
3,Zach LaVine,G,SAC,30.0,28.000000,3.335280,0.129108,3.152378,2.528358,2.571393,2.706956,2.646706
4,Maxime Raynaud,C,SAC,74.0,26.538919,1.351351,0.527027,5.594595,1.783784,0.324324,1.600000,9.108108
5,Daeqwon Plowden,G-F,SAC,32.0,26.386510,1.281250,0.218750,2.000000,1.312500,1.937500,1.500000,3.500000
6,De'Andre Hunter,F-G,SAC,45.0,26.121926,2.000000,0.133333,3.444444,2.755556,1.666667,2.100000,4.355556
7,Nique Clifford,G,SAC,75.0,25.092333,2.386667,0.320000,2.893333,0.933333,1.026667,1.600000,3.706667
8,Precious Achiuwa,F,SAC,73.0,23.906644,1.383562,0.684932,4.315068,1.054795,0.369863,1.800000,7.698630

SAC 9 man rotation

Guards
Darius Acuff Jr.           28.0 min  (G)
Zach LaVine                28.0 min  (G)
Daeqwon Plowden            26.4 min  (G-F)
Nique Clifford             25.1 min  (G)
Guard total: 107.5 minutes

Forwards
Keegan Murray              28.0 min  (F)
Domantas Sabonis           28.0 min  (F-C)
De'Andre Hunter            26.1 min  (F-G)
Precious Achiuwa           23.9 min  (F)
Forward total: 106.0 minutes

Centers
Maxime Raynaud             26.5 min  (C)
Center total: 26.5 minutes
Total rotation minutes: 240.0
Position total:         240.0
Unassigned minutes:     0.0
SAS Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
554,Victor Wembanyama,F-C,SAS,65.000000,32.000000,3.413291,3.378986,10.394242,6.380624,2.092570,3.402999,12.178072
129,De'Aaron Fox,G,SAS,72.000000,30.987014,6.180556,0.263889,3.166667,2.597222,1.819444,2.200000,8.777778
147,Devin Vassell,G-F,SAS,67.000000,30.510920,2.492537,0.373134,3.432836,1.582090,2.477612,2.000000,2.537313
506,Stephon Castle,G,SAS,68.000000,29.966814,7.382353,0.279412,3.882353,4.147059,1.191176,2.800000,8.029412
166,Dylan Harper,G,SAS,65.000000,28.000000,4.780621,0.431334,3.235007,1.617503,1.096308,2.480172,8.662629
521,Tobias Harris,F,SAS,63.000000,27.705556,2.492063,0.412698,4.253968,2.158730,1.301587,2.200000,5.174603
302,Julian Champagnie,F,SAS,82.000000,27.633699,1.548780,0.463415,4.865854,1.390244,2.378049,1.600000,2.463415
192,Harrison Barnes,F,SAS,77.000000,25.798377,1.922078,0.155844,1.961039,1.324675,1.805195,1.200000,2.987013
320,Keldon Johnson,F-G,SAS,82.000000,23.310569,1.353659,0.134146,3.695122,1.878049,1.207317,2.200000,7.512195
371,Luke Kornet,C-F,SAS,68.000000,21.030588,1.852941,0.955882,3.426471,1.382353,0.000000,0.500000,5.088235
619,Maliq Brown,F-C,SAS,24.029148,15.117529,1.514402,0.494811,1.535947,0.606910,0.307817,0.647864,1.698698
592,Tarris Reed Jr.,C,SAS,6.987162,13.399226,0.960335,0.511299,3.240061,0.651857,-0.074971,0.545753,3.953843
510,Taelon Peter,G,SAS,38.000000,12.953421,1.052632,0.105263,1.289474,0.263158,1.078947,0.700000,0.894737
81,Carter Bryant,F,SAS,71.000000,11.519225,0.661972,0.323944,1.971831,0.422535,0.732394,0.600000,1.521127
657,Jayden Quaintance,C-F,SAS,1.155995,10.126057,0.920976,0.544615,1.845900,0.594000,0.053651,0.699230,2.591577
290,Jordan McLaughlin,G,SAS,44.000000,6.400379,0.863636,0.045455,0.568182,0.136364,0.386364,0.700000,0.681818
125,David Jones Garcia,G,SAS,11.000000,6.179545,1.636364,0.090909,0.818182,0.272727,0.272727,0.400000,1.818182
634,Ja'Kobi Gillespie,NaN,SAS,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 17
  -> Adding real player Luke Kornet (C-F, 21.03 min) to fill C
     Removing Keldon Johnson to make room.

SAS 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Victor Wembanyama,F-C,SAS,65.0,32.000000,3.413291,3.378986,10.394242,6.380624,2.09257,3.402999,12.178072
1,De'Aaron Fox,G,SAS,72.0,30.987014,6.180556,0.263889,3.166667,2.597222,1.819444,2.2,8.777778
2,Devin Vassell,G-F,SAS,67.0,30.510920,2.492537,0.373134,3.432836,1.58209,2.477612,2.0,2.537313
3,Stephon Castle,G,SAS,68.0,29.966814,7.382353,0.279412,3.882353,4.147059,1.191176,2.8,8.029412
4,Dylan Harper,G,SAS,65.0,28.000000,4.780621,0.431334,3.235007,1.617503,1.096308,2.480172,8.662629
5,Tobias Harris,F,SAS,63.0,27.705556,2.492063,0.412698,4.253968,2.15873,1.301587,2.2,5.174603
6,Julian Champagnie,F,SAS,82.0,27.633699,1.54878,0.463415,4.865854,1.390244,2.378049,1.6,2.463415
7,Harrison Barnes,F,SAS,77.0,25.798377,1.922078,0.155844,1.961039,1.324675,1.805195,1.2,2.987013
8,Luke Kornet,C-F,SAS,68.0,21.030588,1.852941,0.955882,3.426471,1.382353,0.0,0.5,5.088235

SAS 9 man rotation

Guards
De'Aaron Fox               31.0 min  (G)
Devin Vassell              30.5 min  (G-F)
Stephon Castle             30.0 min  (G)
Dylan Harper               28.0 min  (G)
Guard total: 119.5 minutes

Forwards
Victor Wembanyama          32.0 min  (F-C)
Tobias Harris              27.7 min  (F)
Julian Champagnie          27.6 min  (F)
Harrison Barnes            25.8 min  (F)
Forward total: 113.1 minutes

Centers
Luke Kornet                21.0 min  (C-F)
Center total: 21.0 minutes
Total rotation minutes: 253.6
Position total:         253.6
Unassigned minutes:     0.0
TOR Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
492,Scottie Barnes,F-G,TOR,80.000000,33.509708,5.925000,1.450000,5.637500,3.025000,0.850000,2.900000,10.350000
316,Kawhi Leonard,F,TOR,72.000000,32.072744,3.600000,0.415385,5.261538,5.707692,2.646154,5.100000,10.553846
201,Immanuel Quickley,G,TOR,70.000000,31.875833,5.928571,0.071429,3.485714,2.428571,2.542857,2.300000,5.371429
467,RJ Barrett,F-G,TOR,66.000000,30.276491,3.315789,0.333333,4.298246,3.508772,1.684211,3.400000,10.421053
104,Collin Murray-Boyles,F,TOR,75.000000,28.000000,2.382787,1.191394,3.416827,1.596018,0.382145,1.921965,7.912653
227,Jakob Poeltl,C,TOR,70.000000,24.979565,2.021739,0.695652,4.543478,1.282609,0.000000,1.700000,8.956522
374,Malachi Smith,G,TOR,15.000000,23.921333,3.266667,0.266667,2.600000,0.533333,1.333333,1.500000,3.333333
240,Jamal Shead,G,TOR,82.000000,22.588272,5.414634,0.182927,1.426829,1.109756,1.024390,1.600000,2.341463
214,Ja'Kobe Walter,G,TOR,72.000000,20.466319,1.194444,0.194444,1.791667,0.986111,1.527778,1.800000,1.861111
348,Kyle Anderson,F-G,TOR,43.000000,19.842713,2.930233,0.604651,2.511628,1.116279,0.093023,0.800000,4.511628
648,Allen Graves,F-C,TOR,55.000000,17.000000,1.473352,0.061883,1.510961,0.885312,1.147760,1.034176,2.682940
662,Jaden Bradley,G,TOR,4.170644,12.520981,1.863310,0.134439,0.699719,0.729907,0.378386,0.349103,1.206977
0,A.J. Lawson,G,TOR,24.000000,9.421458,0.291667,0.166667,1.416667,0.583333,0.791667,1.000000,1.250000
527,Trayce Jackson-Davis,F,TOR,53.000000,9.359182,0.735849,0.452830,1.490566,0.716981,0.018868,0.600000,2.641509
25,Andre Jackson Jr.,G,TOR,48.000000,8.502257,0.895833,0.083333,0.979167,0.416667,0.312500,0.500000,1.000000
245,Jamison Battle,F,TOR,61.000000,8.471776,0.393443,0.049180,1.131148,0.147541,0.573770,0.400000,1.147541
95,Chucky Hepburn,G,TOR,2.000000,6.616667,1.000000,0.000000,0.500000,0.000000,0.000000,0.000000,0.000000
17,Alijah Martin,G,TOR,23.000000,6.331087,0.521739,0.173913,0.521739,0.652174,0.173913,0.200000,1.043478
536,Trey Jemison III,C,TOR,13.000000,6.276026,0.384615,0.153846,0.769231,0.076923,0.000000,0.200000,0.769231
659,Nate Bittle,NaN,TOR,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Available players: 19
  -> Adding real player Allen Graves (F-C, 17.00 min) to fill C
     Removing Ja'Kobe Walter to make room.

TOR 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Scottie Barnes,F-G,TOR,80.0,33.509708,5.925,1.45,5.6375,3.025,0.85,2.9,10.35
1,Kawhi Leonard,F,TOR,72.0,32.072744,3.6,0.415385,5.261538,5.707692,2.646154,5.1,10.553846
2,Immanuel Quickley,G,TOR,70.0,31.875833,5.928571,0.071429,3.485714,2.428571,2.542857,2.3,5.371429
3,RJ Barrett,F-G,TOR,66.0,30.276491,3.315789,0.333333,4.298246,3.508772,1.684211,3.4,10.421053
4,Collin Murray-Boyles,F,TOR,75.0,28.000000,2.382787,1.191394,3.416827,1.596018,0.382145,1.921965,7.912653
5,Jakob Poeltl,C,TOR,70.0,24.979565,2.021739,0.695652,4.543478,1.282609,0.0,1.7,8.956522
6,Malachi Smith,G,TOR,15.0,23.921333,3.266667,0.266667,2.6,0.533333,1.333333,1.5,3.333333
7,Jamal Shead,G,TOR,82.0,22.588272,5.414634,0.182927,1.426829,1.109756,1.02439,1.6,2.341463
8,Allen Graves,F-C,TOR,55.0,17.000000,1.473352,0.061883,1.510961,0.885312,1.14776,1.034176,2.68294

TOR 9 man rotation

Guards
Immanuel Quickley          31.9 min  (G)
Malachi Smith              23.9 min  (G)
Jamal Shead                22.6 min  (G)
Guard total: 78.4 minutes

Forwards
Scottie Barnes             33.5 min  (F-G)
Kawhi Leonard              32.1 min  (F)
RJ Barrett                 30.3 min  (F-G)
Collin Murray-Boyles       28.0 min  (F)
Allen Graves               17.0 min  (F-C)
Forward total: 140.9 minutes

Centers
Jakob Poeltl               25.0 min  (C)
Center total: 25.0 minutes
Total rotation minutes: 244.2
Position total:         244.2
Unassigned minutes:     0.0
UTA Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
358,Lauri Markkanen,F-C,UTA,65.000000,34.347540,2.119048,0.500000,4.880952,5.714286,2.738095,3.900000,11.761905
335,Keyonte George,G,UTA,65.000000,33.076080,6.148148,0.259259,3.259259,6.240741,2.481481,3.500000,7.703704
685,Jaren Jackson Jr.,F-C,UTA,74.000000,31.000000,2.078886,1.587257,4.579167,4.368469,2.050793,2.702551,6.573773
594,Darryn Peterson,G,UTA,65.000000,28.000000,2.581628,0.226109,2.502333,2.275046,1.807083,2.447364,5.569960
7,Ace Bailey,F,UTA,72.000000,27.606157,1.819444,0.680556,2.750000,0.916667,1.902778,1.800000,5.166667
309,Jusuf Nurkić,C,UTA,41.000000,26.416301,4.780488,0.536585,7.780488,1.512195,0.609756,1.000000,7.365854
204,Isaiah Collier,G,UTA,59.000000,25.710508,7.169492,0.338983,2.186441,2.559322,0.457627,2.500000,7.389831
300,Josh Okogie,G,UTA,78.000000,25.000000,1.274180,0.295462,2.197499,0.757122,1.144916,1.296340,2.142100
194,Hayden Gray,G,UTA,40.000000,24.750000,1.000000,1.000000,0.000000,2.000000,0.000000,0.000000,2.000000
59,Brice Sensabaugh,F,UTA,75.000000,23.491556,1.906667,0.160000,2.333333,2.213333,2.160000,2.200000,5.200000
349,Kyle Filipowski,C,UTA,77.000000,23.388874,2.571429,0.506494,5.298701,2.064935,0.961039,1.800000,6.311688
508,Svi Mykhailiuk,G-F,UTA,50.000000,23.112233,1.860000,0.060000,1.760000,0.500000,1.960000,1.400000,2.720000
46,Blake Hinson,F,UTA,14.000000,20.388095,1.142857,0.142857,1.571429,0.857143,2.642857,2.300000,2.714286
402,Mo Bamba,C,UTA,50.000000,20.000000,0.456621,1.369863,5.479452,0.000000,0.000000,0.000000,3.652968
254,Jaxson Hayes,C-F,UTA,66.000000,18.281490,0.893939,0.787879,2.606061,1.484848,0.045455,1.100000,5.909091
331,Kevin Love,F-C,UTA,37.000000,16.562162,1.810811,0.243243,4.324324,1.000000,1.432432,1.200000,1.189189
296,Josh Green,G,UTA,58.000000,15.653937,0.810345,0.103448,0.982759,0.431034,1.000000,0.700000,0.827586
535,Trey Alexander,G,UTA,9.000000,12.293704,1.000000,0.222222,1.111111,0.333333,0.666667,0.700000,1.777778
627,Tamar Bates,G-F,UTA,1.949338,8.613749,0.376910,0.020490,1.002475,0.301125,0.614877,0.559539,1.155284
193,Harrison Ingram,F,UTA,7.000000,3.730952,0.142857,0.000000,0.000000,0.000000,0.142857,0.700000,1.142857

Available players: 20

UTA 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Lauri Markkanen,F-C,UTA,65.0,34.347540,2.119048,0.500000,4.880952,5.714286,2.738095,3.900000,11.761905
1,Keyonte George,G,UTA,65.0,33.076080,6.148148,0.259259,3.259259,6.240741,2.481481,3.500000,7.703704
2,Jaren Jackson Jr.,F-C,UTA,74.0,31.000000,2.078886,1.587257,4.579167,4.368469,2.050793,2.702551,6.573773
3,Darryn Peterson,G,UTA,65.0,28.000000,2.581628,0.226109,2.502333,2.275046,1.807083,2.447364,5.569960
4,Ace Bailey,F,UTA,72.0,27.606157,1.819444,0.680556,2.750000,0.916667,1.902778,1.800000,5.166667
5,Jusuf Nurkić,C,UTA,41.0,26.416301,4.780488,0.536585,7.780488,1.512195,0.609756,1.000000,7.365854
6,Isaiah Collier,G,UTA,59.0,25.710508,7.169492,0.338983,2.186441,2.559322,0.457627,2.500000,7.389831
7,Josh Okogie,G,UTA,78.0,25.000000,1.274180,0.295462,2.197499,0.757122,1.144916,1.296340,2.142100
8,Hayden Gray,G,UTA,40.0,24.750000,1.000000,1.000000,0.000000,2.000000,0.000000,0.000000,2.000000

UTA 9 man rotation

Guards
Keyonte George             33.1 min  (G)
Darryn Peterson            28.0 min  (G)
Isaiah Collier             25.7 min  (G)
Josh Okogie                25.0 min  (G)
Hayden Gray                24.8 min  (G)
Guard total: 136.5 minutes

Forwards
Lauri Markkanen            34.3 min  (F-C)
Jaren Jackson Jr.          31.0 min  (F-C)
Ace Bailey                 27.6 min  (F)
Forward total: 93.0 minutes

Centers
Jusuf Nurkić               26.4 min  (C)
Center total: 26.4 minutes
Total rotation minutes: 255.9
Position total:         255.9
Unassigned minutes:     0.0
WAS Roster

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
352,Kyshawn George,F,WAS,48.000000,28.978403,4.458333,0.895833,4.208333,2.187500,2.062500,1.600000,4.750000
688,Trae Young,G,WAS,45.000000,28.000000,8.995787,0.122670,2.044497,5.019240,2.228502,2.952254,0.838244
677,Anthony Davis,F-C,WAS,45.000000,28.000000,2.971583,1.805934,7.486419,4.695429,0.574615,2.930539,4.301407
65,Bub Carrington,G,WAS,50.000000,27.690854,4.646341,0.207317,2.963415,0.987805,2.060976,1.500000,1.609756
136,Deandre Ayton,C,WAS,72.000000,27.199792,0.819444,0.972222,5.416667,1.263889,0.000000,2.100000,10.777778
16,Alex Sarr,C,WAS,48.000000,27.180451,2.708333,1.979167,5.208333,2.104167,1.041667,2.000000,10.125000
44,Bilal Coulibaly,G,WAS,56.000000,26.207232,2.589286,0.964286,3.482143,2.357143,1.160714,2.100000,5.428571
652,AJ Dybantsa,F,WAS,50.000000,24.540266,2.256040,0.208463,3.197713,2.078903,0.774349,2.043655,6.217963
528,Tre Johnson,G,WAS,60.000000,24.046944,2.033333,0.300000,2.350000,1.266667,1.916667,1.700000,3.366667
337,Khris Middleton,F,WAS,63.000000,22.842646,2.793651,0.142857,2.857143,1.888889,1.063492,1.000000,2.349206
562,Will Riley,F,WAS,74.000000,22.060428,1.972973,0.121622,2.108108,1.945946,1.054054,1.700000,4.675676
244,Jamir Watkins,F,WAS,50.000000,20.643533,1.340000,0.500000,2.900000,1.140000,0.940000,1.100000,3.320000
307,Justin Champagnie,G-F,WAS,69.000000,19.963092,1.217391,0.623188,3.463768,1.159420,0.768116,1.600000,5.159420
31,Anthony Gill,F,WAS,55.000000,17.289939,1.254545,0.381818,1.818182,0.618182,0.309091,0.600000,4.109091
498,Sharife Cooper,G,WAS,41.000000,17.073130,3.024390,0.121951,1.658537,1.219512,0.707317,1.700000,3.902439
539,Tristan Vukcevic,F,WAS,49.000000,13.693469,1.122449,0.673469,2.346939,1.775510,1.020408,1.100000,3.591837
530,Tre Mann,G,WAS,53.000000,12.612421,1.622642,0.094340,1.358491,0.433962,0.943396,0.600000,1.811321
644,Felix Okpara,C,WAS,10.910557,10.098313,0.966686,0.463268,0.942973,0.807838,0.066435,0.645492,2.081808

Available players: 18

WAS 9-man rotation

,PlayerName,Pos,TeamAbbv,GP,Min,Ast,BLK,DReb,FTM,3PM,PTSOFFTO,Pts_Paint
0,Kyshawn George,F,WAS,48.0,28.978403,4.458333,0.895833,4.208333,2.187500,2.062500,1.600000,4.750000
1,Trae Young,G,WAS,45.0,28.000000,8.995787,0.122670,2.044497,5.019240,2.228502,2.952254,0.838244
2,Anthony Davis,F-C,WAS,45.0,28.000000,2.971583,1.805934,7.486419,4.695429,0.574615,2.930539,4.301407
3,Bub Carrington,G,WAS,50.0,27.690854,4.646341,0.207317,2.963415,0.987805,2.060976,1.500000,1.609756
4,Deandre Ayton,C,WAS,72.0,27.199792,0.819444,0.972222,5.416667,1.263889,0.000000,2.100000,10.777778
5,Alex Sarr,C,WAS,48.0,27.180451,2.708333,1.979167,5.208333,2.104167,1.041667,2.000000,10.125000
6,Bilal Coulibaly,G,WAS,56.0,26.207232,2.589286,0.964286,3.482143,2.357143,1.160714,2.100000,5.428571
7,AJ Dybantsa,F,WAS,50.0,24.540266,2.256040,0.208463,3.197713,2.078903,0.774349,2.043655,6.217963
8,Tre Johnson,G,WAS,60.0,24.046944,2.033333,0.300000,2.350000,1.266667,1.916667,1.700000,3.366667

WAS 9 man rotation

Guards
Trae Young                 28.0 min  (G)
Bub Carrington             27.7 min  (G)
Bilal Coulibaly            26.2 min  (G)
Tre Johnson                24.0 min  (G)
Guard total: 105.9 minutes

Forwards
Kyshawn George             29.0 min  (F)
Anthony Davis              28.0 min  (F-C)
AJ Dybantsa                24.5 min  (F)
Forward total: 81.5 minutes

Centers
Deandre Ayton              27.2 min  (C)
Alex Sarr                  27.2 min  (C)
Center total: 54.4 minutes
Total rotation minutes: 241.8
Position total:         241.8
Unassigned minutes:     0.0

# Step 11: Create Conferences/Standings

In [51]:
# Helper function that updates W/L records and winning percentage for a completed game.
def update_standings(standings, winner, loser):

    def find_conference(team):
        if team in standings["East"]:
            return "East"
        elif team in standings["West"]:
            return "West"
        else:
            raise ValueError(f"Unknown team abbreviation: {team}")

    winner_conf = find_conference(winner)
    loser_conf = find_conference(loser)

    # Update records
    standings[winner_conf][winner]["W"] += 1
    standings[loser_conf][loser]["L"] += 1

    # Recalculate winning percentages for any conference(s) touched
    for conf in {winner_conf, loser_conf}:
        for team, record in standings[conf].items():
            games = record["W"] + record["L"]
            record["W_Pct"] = record["W"] / games if games > 0 else 0.0

    return standings

In [52]:
# Helper function that creates initial NBA standings using TeamAbbv.
# Returns:
#     standings = {
#         "East": {...},
#         "West": {...}
#     }

# Each team starts with:
#     W = 0
#     L = 0
#     W_Pct = 0
def create_standings():

    eastern_teams = [
        "ATL",  # Atlanta Hawks
        "BOS",  # Boston Celtics
        "BKN",  # Brooklyn Nets
        "CHA",  # Charlotte Hornets
        "CHI",  # Chicago Bulls
        "CLE",  # Cleveland Cavaliers
        "DET",  # Detroit Pistons
        "IND",  # Indiana Pacers
        "MIA",  # Miami Heat
        "MIL",  # Milwaukee Bucks
        "NYK",  # New York Knicks
        "ORL",  # Orlando Magic
        "PHI",  # Philadelphia 76ers
        "TOR",  # Toronto Raptors
        "WAS",  # Washington Wizards
    ]

    western_teams = [
        "DAL",  # Dallas Mavericks
        "DEN",  # Denver Nuggets
        "GSW",  # Golden State Warriors
        "HOU",  # Houston Rockets
        "LAC",  # LA Clippers
        "LAL",  # Los Angeles Lakers
        "MEM",  # Memphis Grizzlies
        "MIN",  # Minnesota Timberwolves
        "NOP",  # New Orleans Pelicans
        "OKC",  # Oklahoma City Thunder
        "PHX",  # Phoenix Suns
        "POR",  # Portland Trail Blazers
        "SAC",  # Sacramento Kings
        "SAS",  # San Antonio Spurs
        "UTA",  # Utah Jazz
    ]

    standings = {
        "East": {},
        "West": {}
    }

    for team in eastern_teams:
        standings["East"][team] = {
            "W": 0,
            "L": 0,
            "W_Pct": 0.0
        }

    for team in western_teams:
        standings["West"][team] = {
            "W": 0,
            "L": 0,
            "W_Pct": 0.0
        }

    return standings

In [53]:
# Helper function that prints current NBA standings for both conferences.
def print_standings(standings):

    print("Eastern Conference")

    east_sorted = sorted(
        standings["East"].items(),
        key=lambda x: x[1]["W_Pct"],
        reverse=True
    )

    print(
        f"{'Team':<6}"
        f"{'W':>5}"
        f"{'L':>5}"
        f"{'W_Pct':>10}"
    )

    for team, record in east_sorted:
        print(
            f"{team:<6}"
            f"{record['W']:>5}"
            f"{record['L']:>5}"
            f"{record['W_Pct']:>10.3f}"
        )

    print("Western Conference")

    west_sorted = sorted(
        standings["West"].items(),
        key=lambda x: x[1]["W_Pct"],
        reverse=True
    )

    print(
        f"{'Team':<6}"
        f"{'W':>5}"
        f"{'L':>5}"
        f"{'W_Pct':>10}"
    )

    for team, record in west_sorted:
        print(
            f"{team:<6}"
            f"{record['W']:>5}"
            f"{record['L']:>5}"
            f"{record['W_Pct']:>10.3f}"
        )

In [54]:
# Helper function that compares the standing that the model obtained with the actual standings.
def compare_standings(model_standings, actual_standings):

    comparison = {
        "East": {},
        "West": {}
    }

    for conference in ["East", "West"]:

        for team, model_record in model_standings[conference].items():

            actual_record = actual_standings[conference][team]

            model_w = model_record["W"]
            model_l = model_record["L"]

            actual_w = actual_record["W"]
            actual_l = actual_record["L"]

            model_pct = model_record["W_Pct"]

            actual_games = actual_w + actual_l
            actual_pct = (
                actual_w / actual_games
                if actual_games > 0
                else 0.0
            )

            comparison[conference][team] = {
                "Model_W": model_w,
                "Actual_W": actual_w,
                "W_Diff": model_w - actual_w,

                "Model_L": model_l,
                "Actual_L": actual_l,
                "L_Diff": model_l - actual_l,

                "Model_W_Pct": model_pct,
                "Actual_W_Pct": actual_pct,

                "W_Pct_Diff": model_pct - actual_pct
            }

    return comparison

In [55]:
# Helper function that takes into account home-court advantage.
#     The boost is a logit-space shift; 0.20 corresponds to roughly a 50/50 game
#     becoming ~55/45 in the home team's favor (the NBA's long-run home edge).
def apply_home_advantage(home_prob, away_prob, boost=0.20):
    def logit(p):
        p = np.clip(p, 1e-6, 1 - 1e-6)
        return np.log(p / (1 - p))

    def sigmoid(x):
        return 1 / (1 + np.exp(-x))

    home_prob_adj = sigmoid(logit(home_prob) + boost)
    away_prob_adj = sigmoid(logit(away_prob) - boost)

    return home_prob_adj, away_prob_adj

Debugging

# Step 12: Get schedule

In [56]:
# Picking the season
SEASONS = [
    # "21_22",
    # "22_23",
    # "23_24",
    # "24_25",
    # "25_26",
    "26_27",
]

Load Model

In [57]:
model = xgb.Booster()
model.load_model("/Users/ronanhwang/Downloads/Github/nba_2020s/best_model_Altogether.json")

Run model of schedule

In [58]:
# Helper function that applies a penalty to a team that is playing a back to back
def apply_back_to_back_penalty(home_prediction, away_prediction, home_is_b2b, away_is_b2b, penalty=0.03):
    if home_is_b2b and not away_is_b2b:
        home_prediction -= penalty
        away_prediction += penalty
    elif away_is_b2b and not home_is_b2b:
        away_prediction -= penalty
        home_prediction += penalty
    # if both teams are on a b2b, no relative adjustment
    return home_prediction, away_prediction

In [59]:
SEASON_TIPOFF = {
    "21_22": "2021-10-19",
    "22_23": "2022-10-18",
    "23_24": "2023-10-24",
    "24_25": "2024-10-22",
    "25_26": "2025-10-21",
    "26_27": "2026-10-20",
}

def process_all_seasons(data, team_rosters, seasons):

    results = {}

    for season in seasons:

        print(f"\nProcessing season: {season}")

        schedule = data[season]["ScheduleLeagueV2"].copy()

        schedule["gameDateTimeEst"] = pd.to_datetime(
            schedule["gameDateTimeEst"],
            utc=True
        )

        tipoff = pd.Timestamp(
            SEASON_TIPOFF[season],
            tz="UTC"
        )

        season_rosters = {
            team: df.copy()
            for team, df in team_rosters[season].items()
        }

        standings = create_standings()

        schedule = (
            schedule
            .sort_values("gameDateTimeEst")
            .reset_index(drop=True)
        )

        correct_predictions = 0
        incorrect_predictions = 0
        flipped_by_home_boost = 0
        flipped_by_b2b = 0

        processed_games = 0
        skipped_non_regular = 0
        skipped_not_final = 0

        team_games_played = {
            team: 0
            for team in season_rosters
        }

        # Store predictions for future seasons
        season_predictions = []

        # Last game date per team
        last_game_date = {
            team: None
            for team in season_rosters
        }

        for _, game in schedule.iterrows():

            # Game Type
            label = (
                str(game["gameLabel"]).strip()
                if pd.notna(game["gameLabel"])
                else ""
            )

            series = (
                str(game["seriesText"]).strip()
                if pd.notna(game["seriesText"])
                else ""
            )

            # Skip non regular season games
            # Game Type
            label = (
                str(game["gameLabel"]).strip()
                if pd.notna(game["gameLabel"])
                else ""
            )

            series = (
                str(game["seriesText"]).strip()
                if pd.notna(game["seriesText"])
                else ""
            )

            # Skip ONLY:
            # 1. Preseason
            # 2. Emirates NBA Cup games at Neutral Site
            is_non_regular = (
                label == "Preseason"
                or (
                    label == "Emirates NBA Cup"
                    and pd.isna(game["homeTeam_teamTricode"])
                    and pd.isna(game["awayTeam_teamTricode"])
                )
            )
            if is_non_regular:
                skipped_non_regular += 1
                continue

            # Process scheduled games 
            status = (
                str(game["gameStatusText"]).strip()
                if pd.notna(game["gameStatusText"])
                else ""
            )

            is_final = status.lower().startswith("final")

            if season != "26_27" and not is_final:
                skipped_not_final += 1
                continue

            # Teams
            home_team = game["homeTeam_teamTricode"]
            away_team = game["awayTeam_teamTricode"]

            if (
                home_team not in season_rosters
                or away_team not in season_rosters
            ):
                print(
                    f"Skipping game with unknown team(s): "
                    f"{away_team} @ {home_team}"
                )
                continue

            processed_games += 1

            # Eastern Calendar Date for B2B games
            game_date = (
                game["gameDateTimeEst"]
                .tz_convert("America/New_York")
                .normalize()
            )

            home_is_b2b = (
                last_game_date[home_team] is not None
                and (
                    game_date - last_game_date[home_team]
                ).days == 1
            )

            away_is_b2b = (
                last_game_date[away_team] is not None
                and (
                    game_date - last_game_date[away_team]
                ).days == 1
            )

            # Current Rosters
            home_roster = season_rosters[home_team]
            away_roster = season_rosters[away_team]

            # 9-MAN Rotations
            home_rotation = get_9_man_rotation(home_roster)
            away_rotation = get_9_man_rotation(away_roster)

            home_rotation = normalize_rotation(home_rotation)
            away_rotation = normalize_rotation(away_rotation)

            # Aggregate team stats
            homeTeam = home_rotation.agg({
                "Ast": "sum",
                "BLK": "sum",
                "DReb": "sum",
                "FTM": "sum",
                "3PM": "sum",
                "PTSOFFTO": "sum",
                "Pts_Paint": "sum"
            })

            awayTeam = away_rotation.agg({
                "Ast": "sum",
                "BLK": "sum",
                "DReb": "sum",
                "FTM": "sum",
                "3PM": "sum",
                "PTSOFFTO": "sum",
                "Pts_Paint": "sum"
            })

            # Feature Differences
            diff_homeTeam = pd.Series({
                "diff_Ast":
                    homeTeam["Ast"] - awayTeam["Ast"],

                "diff_OppPointsInPaint":
                    homeTeam["Pts_Paint"] - awayTeam["Pts_Paint"],

                "diff_PointsOffTO":
                    homeTeam["PTSOFFTO"] - awayTeam["PTSOFFTO"],

                "diff_Blk":
                    homeTeam["BLK"] - awayTeam["BLK"],

                "diff_DReb":
                    homeTeam["DReb"] - awayTeam["DReb"],

                "diff_FTM":
                    homeTeam["FTM"] - awayTeam["FTM"],

                "diff_3PM":
                    homeTeam["3PM"] - awayTeam["3PM"]
            })

            diff_awayTeam = pd.Series({
                "diff_Ast":
                    awayTeam["Ast"] - homeTeam["Ast"],

                "diff_OppPointsInPaint":
                    awayTeam["Pts_Paint"] - homeTeam["Pts_Paint"],

                "diff_PointsOffTO":
                    awayTeam["PTSOFFTO"] - homeTeam["PTSOFFTO"],

                "diff_Blk":
                    awayTeam["BLK"] - homeTeam["BLK"],

                "diff_DReb":
                    awayTeam["DReb"] - homeTeam["DReb"],

                "diff_FTM":
                    awayTeam["FTM"] - homeTeam["FTM"],

                "diff_3PM":
                    awayTeam["3PM"] - homeTeam["3PM"]
            })

            features = [
                "diff_Ast",
                "diff_OppPointsInPaint",
                "diff_PointsOffTO",
                "diff_Blk",
                "diff_DReb",
                "diff_FTM",
                "diff_3PM"
            ]

            home_team_stats = (
                diff_homeTeam
                .to_frame()
                .T[features]
            )

            away_team_stats = (
                diff_awayTeam
                .to_frame()
                .T[features]
            )

            # XGBoost Prediction
            home_dmatrix = xgb.DMatrix(
                home_team_stats,
                feature_names=features
            )

            away_dmatrix = xgb.DMatrix(
                away_team_stats,
                feature_names=features
            )

            home_prediction = model.predict(
                home_dmatrix
            )[0]

            away_prediction = model.predict(
                away_dmatrix
            )[0]

            # Pre boost prediction
            pre_boost_home_win = home_prediction >= 0.5

            # Home court Advantage
            home_prediction, away_prediction = (
                apply_home_advantage(
                    home_prediction,
                    away_prediction
                )
            )

            post_home_boost_win = home_prediction >= 0.5

            if post_home_boost_win != pre_boost_home_win:
                flipped_by_home_boost += 1

            # Back to Back Penalty
            home_prediction, away_prediction = (
                apply_back_to_back_penalty(
                    home_prediction,
                    away_prediction,
                    home_is_b2b,
                    away_is_b2b
                )
            )

            home_win = home_prediction >= 0.5
            away_win = away_prediction >= 0.5

            if home_win != post_home_boost_win:
                flipped_by_b2b += 1

            # Determine Model Winner
            if home_win == away_win:

                if home_prediction > away_prediction:
                    model_winner = home_team
                    model_loser = away_team

                elif away_prediction > home_prediction:
                    model_winner = away_team
                    model_loser = home_team

                else:
                    model_winner = home_team
                    model_loser = away_team

            else:

                if home_win:
                    model_winner = home_team
                    model_loser = away_team

                else:
                    model_winner = away_team
                    model_loser = home_team

            # Save 26_27 Prediction
            if season == "26_27":

                season_predictions.append({
                    "gameId": game["gameId"],
                    "gameDate": game["gameDate"],
                    "gameDateTimeEst": game["gameDateTimeEst"],
                    "away_team": away_team,
                    "home_team": home_team,
                    "predicted_winner": model_winner,
                    "predicted_loser": model_loser,
                    "away_prediction": away_prediction,
                    "home_prediction": home_prediction,
                    "away_is_b2b": away_is_b2b,
                    "home_is_b2b": home_is_b2b,
                })

            # Update Standings
            # Update Standings
            update_standings(
                standings,
                model_winner,
                model_loser
            )

            # Track actual games processed for each team
            team_games_played[home_team] += 1
            team_games_played[away_team] += 1
            # Update Rotations
            subtract_games_Played(
                home_roster,
                home_rotation
            )

            subtract_games_Played(
                away_roster,
                away_rotation
            )

            # Update last game date
            last_game_date[home_team] = game_date
            last_game_date[away_team] = game_date

        # Save Results
        results[season] = {
            "team_rosters": season_rosters,
            "standings": standings,
            "correct_predictions": correct_predictions,
            "incorrect_predictions": incorrect_predictions,
            "flipped_by_home_boost": flipped_by_home_boost,
            "flipped_by_b2b": flipped_by_b2b,
            "predictions": season_predictions
        }
        
        # Output
        print(
            f"\nFinished {season} — "
        )

        print("\nSCHEDULE DIAGNOSTICS")
        print(f"Total schedule rows:       {len(schedule)}")
        print(f"Skipped non-regular:       {skipped_non_regular}")
        print(f"Skipped not final:         {skipped_not_final}")
        print(f"Processed games:           {processed_games}")

        if season == "26_27":
            print(
                f"26_27 predictions stored:  "
                f"{len(season_predictions)}"
            )
        print(
            f"Games flipped by home-court boost: "
            f"{flipped_by_home_boost}"
        )
    return results

In [60]:
results = process_all_seasons(
    data,
    team_rosters,
    SEASONS
)

Processing season: 26_27
Available players: 20
Available players: 18
Available players: 15
  -> Adding real player Andre Drummond (C, 19.54 min) to fill C
     Removing Jose Alvarado to make room.
Available players: 19
Available players: 17
  -> Adding real player Luke Kornet (C-F, 21.03 min) to fill C
     Removing Keldon Johnson to make room.
Available players: 17
Available players: 18
Available players: 18
Available players: 18
Available players: 22
Available players: 18
Available players: 23
Available players: 19
  -> Adding real player Allen Graves (F-C, 17.00 min) to fill C
     Removing Ja'Kobe Walter to make room.
Available players: 16
Available players: 19
  -> Adding real player Nick Richards (C, 14.60 min) to fill C
     Removing Nikola Jović to make room.
Available players: 16
  -> Adding real player Rocco Zikarsky (C, 12.00 min) to fill C
     Removing Bones Hyland to make room.
Available players: 20
  -> Adding real player Yves Missi (C, 19.65 min) to fill C
     Removing Jordan Poole to make room.
Available players: 18
  -> Adding real player Jay Huff (C, 20.97 min) to fill C
     Removing Keion Brooks Jr. to make room.
Available players: 21
Available players: 20
Available players: 21
Available players: 16
Available players: 19
Available players: 18
Available players: 19
Available players: 20
Available players: 24
  -> Adding real player Jamarion Sharp (C, 16.33 min) to fill C
     Removing Jordan Miller to make room.
Available players: 16
Available players: 19
Available players: 15
Available players: 17
Available players: 20
  -> Adding real player Zeke Nnaji (F-C, 12.04 min) to fill C
     Removing Lonnie Walker IV to make room.
Available players: 18
Available players: 19
  -> Adding real player Allen Graves (F-C, 17.00 min) to fill C
     Removing Ja'Kobe Walter to make room.
Available players: 18
Available players: 16
  -> Adding real player Rocco Zikarsky (C, 12.00 min) to fill C
     Removing Bones Hyland to make room.
Available players: 18
  -> Adding real player Jay Huff (C, 20.97 min) to fill C
     Removing Keion Brooks Jr. to make room.
Available players: 16
Available players: 18
Available players: 15
  -> Adding real player Andre Drummond (C, 19.54 min) to fill C
     Removing Jose Alvarado to make room.
Available players: 23
Available players: 22
Available players: 19
  -> Adding real player Nick Richards (C, 14.60 min) to fill C
     Removing Nikola Jović to make room.
Available players: 20
Available players: 18
Available players: 16
Available players: 17
  -> Adding real player Luke Kornet (C-F, 21.03 min) to fill C
     Removing Keldon Johnson to make room.
Available players: 21
Available players: 20
Available players: 20
  -> Adding real player Yves Missi (C, 19.65 min) to fill C
     Removing Jordan Poole to make room.
Available players: 16
Available players: 19
Available players: 18
Available players: 21
Available players: 19
Available players: 24
  -> Adding real player Jamarion Sharp (C, 16.33 min) to fill C
     Removing Jordan Miller to make room.
Available players: 23
Available players: 19
  -> Adding real player Nick Richards (C, 14.60 min) to fill C
     Removing Nikola Jović to make room.
Available players: 19
Available players: 18
Available players: 15
Available players: 18
Available players: 22
Available players: 21
Available players: 16
Available players: 18
Available players: 16
Available players: 17
  -> Adding real player Luke Kornet (C-F, 21.03 min) to fill C
     Removing Keldon Johnson to make room.
Available players: 20
  -> Adding real player Zeke Nnaji (F-C, 12.04 min) to fill C
     Removing Lonnie Walker IV to make room.
Available players: 20
  -> Adding real player Yves Missi (C, 19.65 min) to fill C
     Removing Jordan Poole to make room.
Available players: 20
Available players: 18
Available players: 19
Available players: 19
Available players: 18
Available players: 18
  -> Adding real player Jay Huff (C, 20.97 min) to fill C
     Removing Keion Brooks Jr. to make room.
Available players: 16
  -> Adding real player Rocco Zikarsky (C, 12.00 min) to fill C
     Removing Bones Hyland to make room.
Available players: 19
  -> Adding real player Allen Graves (F-C, 17.00 min) to fill C
     Removing Ja'Kobe Walter to make room.
Available players: 17
Available players: 23
  -> Adding real player Jamarion Sharp (C, 16.33 min) to fill C
     Removing Jordan Miller to make room.
Available players: 15
  -> Adding real player Andre Drummond (C, 19.54 min) to fill C
     Removing Jose Alvarado to make room.
Available players: 18
Available players: 19
Available players: 20
Available players: 15
Available players: 21
Available players: 23
Available players: 18
Available players: 15
Available players: 16
  -> Adding real player Rocco Zikarsky (C, 12.00 min) to fill C
     Removing Bones Hyland to make room.
Available players: 18
Available players: 16
Available players: 19
  -> Adding real player Nick Richards (C, 14.60 min) to fill C
     Removing Nikola Jović to make room.
Available players: 16
Available players: 17
Available players: 20
Available players: 18
Available players: 18
  -> Adding real player Jay Huff (C, 20.97 min) to fill C
     Removing Keion Brooks Jr. to make room.
Available players: 21
Available players: 22
Available players: 19
Available players: 21
Available players: 20
  -> Adding real player Zeke Nnaji (F-C, 12.04 min) to fill C
     Removing Lonnie Walker IV to make room.
Available players: 18
Available players: 18
Available players: 18
Available players: 15
  -> Adding real player Andre Drummond (C, 19.54 min) to fill C
     Removing Jose Alvarado to make room.
Available players: 20
Available players: 17
  -> Adding real player Luke Kornet (C-F, 21.03 min) to fill C
     Removing Keldon Johnson to make room.
Available players: 15
Available players: 19
Available players: 19
Available players: 20
Available players: 23
Available players: 18
  -> Adding real player Jay Huff (C, 20.97 min) to fill C
     Removing Keion Brooks Jr. to make room.
Available players: 19
Available players: 22
Available players: 19
  -> Adding real player Nick Richards (C, 14.60 min) to fill C
     Removing Nikola Jović to make room.
Available players: 14
Available players: 18
Available players: 19
  -> Adding real player Allen Graves (F-C, 17.00 min) to fill C
     Removing Ja'Kobe Walter to make room.
Available players: 18
Available players: 15
Available players: 15
  -> Adding real player Andre Drummond (C, 19.54 min) to fill C
     Removing Jose Alvarado to make room.
Available players: 18
Available players: 21
Available players: 16
  -> Adding real player Rocco Zikarsky (C, 12.00 min) to fill C
     Removing Bones Hyland to make room.
Available players: 18
Available players: 20
  -> Adding real player Yves Missi (C, 19.65 min) to fill C
     Removing Jordan Poole to make room.
Available players: 20
  -> Adding real player Zeke Nnaji (F-C, 12.04 min) to fill C
     Removing Lonnie Walker IV to make room.
Available players: 19
Available players: 17
  -> Adding real player Luke Kornet (C-F, 21.03 min) to fill C
     Removing Keldon Johnson to make room.
Available players: 16
Available players: 17
Available players: 22
  -> Adding real player Jamarion Sharp (C, 16.33 min) to fill C
     Removing Jordan Miller to make room.
Available players: 19
Available players: 22
Available players: 14
Available players: 20
  -> Adding real player Yves Missi (C, 19.65 min) to fill C
     Removing Jordan Poole to make room.
Available players: 15
Available players: 19
Available players: 21
Available players: 18
Available players: 23
Available players: 18
Available players: 15
Available players: 18
Available players: 20
Available players: 19
Available players: 15
  -> Adding real player Andre Drummond (C, 19.54 min) to fill C
     Removing Jose Alvarado to make room.
Available players: 19
  -> Adding real player Allen Graves (F-C, 17.00 min) to fill C
     Removing Ja'Kobe Walter to make room.
Available players: 18
Available players: 19
  -> Adding real player Nick Richards (C, 14.60 min) to fill C
     Removing Nikola Jović to make room.
Available players: 18
  -> Adding real player Jay Huff (C, 20.97 min) to fill C
     Removing Keion Brooks Jr. to make room.
Available players: 16
Available players: 21
Available players: 15
  -> Adding real player Rocco Zikarsky (C, 12.00 min) to fill C
     Removing Jaylen Clark to make room.
Available players: 22
  -> Adding real player Jamarion Sharp (C, 16.33 min) to fill C
     Removing Jordan Miller to make room.
Available players: 20
Available players: 20
  -> Adding real player Zeke Nnaji (F-C, 12.04 min) to fill C
     Removing Lonnie Walker IV to make room.
Available players: 18
Available players: 19
Available players: 19
Available players: 19
Available players: 23
Available players: 19
Available players: 20
  -> Adding real player Yves Missi (C, 19.65 min) to fill C
     Removing Jordan Poole to make room.
Available players: 22
Available players: 21
Available players: 15
Available players: 18
Available players: 14
Available players: 17
  -> Adding real player Luke Kornet (C-F, 21.03 min) to fill C
     Removing Keldon Johnson to make room.
Available players: 15
  -> Adding real player Rocco Zikarsky (C, 12.00 min) to fill C
     Removing Jaylen Clark to make room.
Available players: 21
Available players: 17
Available players: 18
Available players: 18
Available players: 18
  -> Adding real player Jay Huff (C, 20.97 min) to fill C
     Removing Keion Brooks Jr. to make room.
Available players: 18
Available players: 18
Available players: 22
  -> Adding real player Jamarion Sharp (C, 16.33 min) to fill C
     Removing Jordan Miller to make room.
Available players: 19
Available players: 18
  -> Adding real player Allen Graves (F-C, 17.00 min) to fill C
     Removing Ja'Kobe Walter to make room.
Available players: 14
Available players: 17
Available players: 23
Available players: 20
Available players: 18
  -> Adding real player Jay Huff (C, 20.97 min) to fill C
     Removing Keion Brooks Jr. to make room.
Available players: 22
Available players: 15
  -> Adding real player Andre Drummond (C, 19.54 min) to fill C
     Removing Jose Alvarado to make room.
Available players: 18
Available players: 18
Available players: 18
Available players: 19
Available players: 14
Available players: 21
Available players: 20
  -> Adding real player Yves Missi (C, 19.65 min) to fill C
     Removing Jordan Poole to make room.
Available players: 15
  -> Adding real player Rocco Zikarsky (C, 12.00 min) to fill C
     Removing Jaylen Clark to make room.
Available players: 18
Available players: 16
Available players: 14
Available players: 21
Available players: 18
Available players: 17
  -> Adding real player Luke Kornet (C-F, 21.03 min) to fill C
     Removing Keldon Johnson to make room.
Available players: 19
Available players: 20
  -> Adding real player Zeke Nnaji (F-C, 12.04 min) to fill C
     Removing Lonnie Walker IV to make room.
Available players: 19
Available players: 18
Available players: 20
Available players: 22
  -> Adding real player Jamarion Sharp (C, 16.33 min) to fill C
     Removing Jordan Miller to make room.
Available players: 18
  -> Adding real player Allen Graves (F-C, 17.00 min) to fill C
     Removing Ja'Kobe Walter to make room.
Available players: 19
Available players: 19
  -> Adding real player Nick Richards (C, 14.60 min) to fill C
     Removing Nikola Jović to make room.
Available players: 18
Available players: 22
Available players: 20
Available players: 19
Available players: 18
Available players: 23
Available players: 15
  -> Adding real player Andre Drummond (C, 19.54 min) to fill C
     Removing Jose Alvarado to make room.
Available players: 14
Available players: 18
Available players: 18
Available players: 21
Available players: 18
  -> Adding real player Jay Huff (C, 20.97 min) to fill C
     Removing Keion Brooks Jr. to make room.
Available players: 20
  -> Adding real player Yves Missi (C, 19.65 min) to fill C
     Removing Jordan Poole to make room.
Available players: 19
Available players: 17
Available players: 14
Available players: 21
Available players: 15
  -> Adding real player Rocco Zikarsky (C, 12.00 min) to fill C
     Removing Jaylen Clark to make room.
Available players: 20
  -> Adding real player Zeke Nnaji (F-C, 12.04 min) to fill C
     Removing Lonnie Walker IV to make room.
Available players: 18
  -> Adding real player Allen Graves (F-C, 17.00 min) to fill C
     Removing Ja'Kobe Walter to make room.
Available players: 20
Available players: 19
Available players: 17
  -> Adding real player Luke Kornet (C-F, 21.03 min) to fill C
     Removing Keldon Johnson to make room.
Available players: 16
Available players: 14
Available players: 19
Available players: 22
  -> Adding real player Jamarion Sharp (C, 16.33 min) to fill C
     Removing Jordan Miller to make room.
Available players: 19
  -> Adding real player Nick Richards (C, 14.60 min) to fill C
     Removing Nikola Jović to make room.
Available players: 20
Available players: 18
Available players: 18
Available players: 19
  -> Adding real player Nick Richards (C, 14.60 min) to fill C
     Removing Nikola Jović to make room.
Available players: 22
Available players: 18
Available players: 23
Available players: 18
Available players: 14
Available players: 19
Available players: 18
Available players: 18
  -> Adding real player Allen Graves (F-C, 17.00 min) to fill C
     Removing Ja'Kobe Walter to make room.
Available players: 20
  -> Adding real player Yves Missi (C, 19.65 min) to fill C
     Removing Jordan Poole to make room.
Available players: 15
  -> Adding real player Rocco Zikarsky (C, 12.00 min) to fill C
     Removing Jaylen Clark to make room.
Available players: 16
Available players: 19
Available players: 20
Available players: 17
Available players: 14
Available players: 17
  -> Adding real player Luke Kornet (C-F, 21.03 min) to fill C
     Removing Keldon Johnson to make room.
Available players: 19
Available players: 19
Available players: 18
  -> Adding real player Jay Huff (C, 20.97 min) to fill C
     Removing Keion Brooks Jr. to make room.
Available players: 20
  -> Adding real player Zeke Nnaji (F-C, 12.04 min) to fill C
     Removing Lonnie Walker IV to make room.
Available players: 22
Available players: 18
Available players: 14
Available players: 15
  -> Adding real player Andre Drummond (C, 19.54 min) to fill C
     Removing Jose Alvarado to make room.
Available players: 17
Available players: 18
Available players: 18
Available players: 18
Available players: 20
Available players: 21
Available players: 19
Available players: 17
  -> Adding real player Luke Kornet (C-F, 21.03 min) to fill C
     Removing Keldon Johnson to make room.
Available players: 14
Available players: 19
Available players: 20
Available players: 19
Available players: 15
  -> Adding real player Rocco Zikarsky (C, 12.00 min) to fill C
     Removing Jaylen Clark to make room.
Available players: 19
Available players: 16
Available players: 18
Available players: 18
Available players: 18
Available players: 21
  -> Adding real player Jamarion Sharp (C, 16.33 min) to fill C
     Removing Jordan Miller to make room.
Available players: 20
  -> Adding real player Yves Missi (C, 19.65 min) to fill C
     Removing Jordan Poole to make room.
Available players: 14
Available players: 19
  -> Adding real player Nick Richards (C, 14.60 min) to fill C
     Removing Nikola Jović to make room.
Available players: 22
Available players: 19
Available players: 23
Available players: 14
Available players: 20
Available players: 18
Available players: 18
  -> Adding real player Allen Graves (F-C, 17.00 min) to fill C
     Removing Ja'Kobe Walter to make room.
Available players: 20
Available players: 16
Available players: 18
  -> Adding real player Jay Huff (C, 20.97 min) to fill C
     Removing Keion Brooks Jr. to make room.
Available players: 21
Available players: 20
  -> Adding real player Zeke Nnaji (F-C, 12.04 min) to fill C
     Removing Lonnie Walker IV to make room.
Available players: 20
Available players: 17
  -> Adding real player Luke Kornet (C-F, 21.03 min) to fill C
     Removing Keldon Johnson to make room.
Available players: 18
Available players: 20
  -> Adding real player Yves Missi (C, 19.65 min) to fill C
     Removing Jordan Poole to make room.
Available players: 15
  -> Adding real player Andre Drummond (C, 19.54 min) to fill C
     Removing Jose Alvarado to make room.
Available players: 18
Available players: 19
Available players: 18
Available players: 20
Available players: 21
  -> Adding real player Jamarion Sharp (C, 16.33 min) to fill C
     Removing Jordan Miller to make room.
Available players: 19
Available players: 19
  -> Adding real player Nick Richards (C, 14.60 min) to fill C
     Removing Nikola Jović to make room.
Available players: 14
Available players: 18
Available players: 19
Available players: 17
Available players: 18
  -> Adding real player Allen Graves (F-C, 17.00 min) to fill C
     Removing Ja'Kobe Walter to make room.
Available players: 18
Available players: 18
  -> Adding real player Jay Huff (C, 20.97 min) to fill C
     Removing Keion Brooks Jr. to make room.
Available players: 17
Available players: 15
  -> Adding real player Andre Drummond (C, 19.54 min) to fill C
     Removing Jose Alvarado to make room.
Available players: 14
Available players: 14
Available players: 17
  -> Adding real player Luke Kornet (C-F, 21.03 min) to fill C
     Removing Keldon Johnson to make room.
Available players: 20
Available players: 20
  -> Adding real player Zeke Nnaji (F-C, 12.04 min) to fill C
     Removing Lonnie Walker IV to make room.
Available players: 17
Available players: 19
Available players: 20
  -> Adding real player Yves Missi (C, 19.65 min) to fill C
     Removing Jordan Poole to make room.
Available players: 18
Available players: 19
Available players: 18
Available players: 21
Available players: 18
Available players: 19
Available players: 17
Available players: 17
Available players: 20
Available players: 19
Available players: 18
  -> Adding real player Allen Graves (F-C, 17.00 min) to fill C
     Removing Ja'Kobe Walter to make room.
Available players: 15
  -> Adding real player Rocco Zikarsky (C, 12.00 min) to fill C
     Removing Jaylen Clark to make room.
Available players: 16
Available players: 20
Available players: 23
Available players: 18
  -> Adding real player Jay Huff (C, 20.97 min) to fill C
     Removing Keion Brooks Jr. to make room.
Available players: 15
  -> Adding real player Andre Drummond (C, 19.54 min) to fill C
     Removing Jose Alvarado to make room.
Available players: 18
Available players: 17
Available players: 19
  -> Adding real player Nick Richards (C, 14.60 min) to fill C
     Removing Nikola Jović to make room.
Available players: 14
Available players: 14
Available players: 22
Available players: 20
  -> Adding real player Yves Missi (C, 19.65 min) to fill C
     Removing Jordan Poole to make room.
Available players: 20
Available players: 21
Available players: 19
Available players: 17
  -> Adding real player Luke Kornet (C-F, 21.03 min) to fill C
     Removing Keldon Johnson to make room.
Available players: 18
Available players: 14
Available players: 19
Available players: 21
  -> Adding real player Jamarion Sharp (C, 16.33 min) to fill C
     Removing Jordan Miller to make room.
Available players: 17
Available players: 20
  -> Adding real player Yves Missi (C, 19.65 min) to fill C
     Removing Jordan Poole to make room.
Available players: 20
  -> Adding real player Zeke Nnaji (F-C, 12.04 min) to fill C
     Removing Lonnie Walker IV to make room.
Available players: 13
Available players: 16
Available players: 19
  -> Adding real player Nick Richards (C, 14.60 min) to fill C
     Removing Nikola Jović to make room.
Available players: 20
Available players: 20
Available players: 18
Available players: 15
  -> Adding real player Rocco Zikarsky (C, 12.00 min) to fill C

# Step 13: Check

In [61]:
# NBA standings from previous years
nba_standings = {
    "21_22": {
        "west": [
            {"teamAbbv": "PHX", "W": 64, "L": 18, "W_Pct": 0.780},
            {"teamAbbv": "MEM", "W": 56, "L": 26, "W_Pct": 0.683},
            {"teamAbbv": "GSW", "W": 53, "L": 29, "W_Pct": 0.646},
            {"teamAbbv": "DAL", "W": 52, "L": 30, "W_Pct": 0.634},
            {"teamAbbv": "UTA", "W": 49, "L": 33, "W_Pct": 0.598},
            {"teamAbbv": "DEN", "W": 48, "L": 34, "W_Pct": 0.585},
            {"teamAbbv": "MIN", "W": 46, "L": 36, "W_Pct": 0.561},
            {"teamAbbv": "LAC", "W": 42, "L": 40, "W_Pct": 0.512},
            {"teamAbbv": "NOP", "W": 36, "L": 46, "W_Pct": 0.439},
            {"teamAbbv": "SAS", "W": 34, "L": 48, "W_Pct": 0.415},
            {"teamAbbv": "LAL", "W": 33, "L": 49, "W_Pct": 0.402},
            {"teamAbbv": "SAC", "W": 30, "L": 52, "W_Pct": 0.366},
            {"teamAbbv": "POR", "W": 27, "L": 55, "W_Pct": 0.329},
            {"teamAbbv": "OKC", "W": 24, "L": 58, "W_Pct": 0.293},
            {"teamAbbv": "HOU", "W": 20, "L": 62, "W_Pct": 0.244},
        ],
        "east": [
            {"teamAbbv": "MIA", "W": 53, "L": 29, "W_Pct": 0.646},
            {"teamAbbv": "BOS", "W": 51, "L": 31, "W_Pct": 0.622},
            {"teamAbbv": "MIL", "W": 51, "L": 31, "W_Pct": 0.622},
            {"teamAbbv": "PHI", "W": 51, "L": 31, "W_Pct": 0.622},
            {"teamAbbv": "TOR", "W": 48, "L": 34, "W_Pct": 0.585},
            {"teamAbbv": "CHI", "W": 46, "L": 36, "W_Pct": 0.561},
            {"teamAbbv": "BKN", "W": 44, "L": 38, "W_Pct": 0.537},
            {"teamAbbv": "CLE", "W": 44, "L": 38, "W_Pct": 0.537},
            {"teamAbbv": "ATL", "W": 43, "L": 39, "W_Pct": 0.524},
            {"teamAbbv": "CHA", "W": 43, "L": 39, "W_Pct": 0.524},
            {"teamAbbv": "NYK", "W": 37, "L": 45, "W_Pct": 0.451},
            {"teamAbbv": "WAS", "W": 35, "L": 47, "W_Pct": 0.427},
            {"teamAbbv": "IND", "W": 25, "L": 57, "W_Pct": 0.305},
            {"teamAbbv": "DET", "W": 23, "L": 59, "W_Pct": 0.280},
            {"teamAbbv": "ORL", "W": 22, "L": 60, "W_Pct": 0.268},
        ],
    },

    "22_23": {
        "east": [
            {"teamAbbv": "MIL", "W": 58, "L": 24, "W_Pct": 0.707},
            {"teamAbbv": "BOS", "W": 57, "L": 25, "W_Pct": 0.695},
            {"teamAbbv": "PHI", "W": 54, "L": 28, "W_Pct": 0.659},
            {"teamAbbv": "CLE", "W": 51, "L": 31, "W_Pct": 0.622},
            {"teamAbbv": "NYK", "W": 47, "L": 35, "W_Pct": 0.573},
            {"teamAbbv": "BKN", "W": 45, "L": 37, "W_Pct": 0.549},
            {"teamAbbv": "MIA", "W": 44, "L": 38, "W_Pct": 0.537},
            {"teamAbbv": "ATL", "W": 41, "L": 41, "W_Pct": 0.500},
            {"teamAbbv": "TOR", "W": 41, "L": 41, "W_Pct": 0.500},
            {"teamAbbv": "CHI", "W": 40, "L": 42, "W_Pct": 0.488},
            {"teamAbbv": "IND", "W": 35, "L": 47, "W_Pct": 0.427},
            {"teamAbbv": "WAS", "W": 35, "L": 47, "W_Pct": 0.427},
            {"teamAbbv": "ORL", "W": 34, "L": 48, "W_Pct": 0.415},
            {"teamAbbv": "CHA", "W": 27, "L": 55, "W_Pct": 0.329},
            {"teamAbbv": "DET", "W": 17, "L": 65, "W_Pct": 0.207},
        ],
        "west": [
            {"teamAbbv": "DEN", "W": 53, "L": 29, "W_Pct": 0.646},
            {"teamAbbv": "MEM", "W": 51, "L": 31, "W_Pct": 0.622},
            {"teamAbbv": "SAC", "W": 48, "L": 34, "W_Pct": 0.585},
            {"teamAbbv": "PHX", "W": 45, "L": 37, "W_Pct": 0.549},
            {"teamAbbv": "LAC", "W": 44, "L": 38, "W_Pct": 0.537},
            {"teamAbbv": "GSW", "W": 44, "L": 38, "W_Pct": 0.537},
            {"teamAbbv": "LAL", "W": 43, "L": 39, "W_Pct": 0.524},
            {"teamAbbv": "MIN", "W": 42, "L": 40, "W_Pct": 0.512},
            {"teamAbbv": "NOP", "W": 42, "L": 40, "W_Pct": 0.512},
            {"teamAbbv": "OKC", "W": 40, "L": 42, "W_Pct": 0.488},
            {"teamAbbv": "DAL", "W": 38, "L": 44, "W_Pct": 0.463},
            {"teamAbbv": "UTA", "W": 37, "L": 45, "W_Pct": 0.451},
            {"teamAbbv": "POR", "W": 33, "L": 49, "W_Pct": 0.402},
            {"teamAbbv": "HOU", "W": 22, "L": 60, "W_Pct": 0.268},
            {"teamAbbv": "SAS", "W": 22, "L": 60, "W_Pct": 0.268},
        ],
    },

    "23_24": {
        "east": [
            {"teamAbbv": "BOS", "W": 64, "L": 18, "W_Pct": 0.780},
            {"teamAbbv": "NYK", "W": 50, "L": 32, "W_Pct": 0.610},
            {"teamAbbv": "MIL", "W": 49, "L": 33, "W_Pct": 0.598},
            {"teamAbbv": "CLE", "W": 48, "L": 34, "W_Pct": 0.585},
            {"teamAbbv": "ORL", "W": 47, "L": 35, "W_Pct": 0.573},
            {"teamAbbv": "IND", "W": 47, "L": 35, "W_Pct": 0.573},
            {"teamAbbv": "PHI", "W": 47, "L": 35, "W_Pct": 0.573},
            {"teamAbbv": "MIA", "W": 46, "L": 36, "W_Pct": 0.561},
            {"teamAbbv": "CHI", "W": 39, "L": 43, "W_Pct": 0.476},
            {"teamAbbv": "ATL", "W": 36, "L": 46, "W_Pct": 0.439},
            {"teamAbbv": "BKN", "W": 32, "L": 50, "W_Pct": 0.390},
            {"teamAbbv": "TOR", "W": 25, "L": 57, "W_Pct": 0.305},
            {"teamAbbv": "CHA", "W": 21, "L": 61, "W_Pct": 0.256},
            {"teamAbbv": "WAS", "W": 15, "L": 67, "W_Pct": 0.183},
            {"teamAbbv": "DET", "W": 14, "L": 68, "W_Pct": 0.171},
        ],
        "west": [
            {"teamAbbv": "OKC", "W": 57, "L": 25, "W_Pct": 0.695},
            {"teamAbbv": "DEN", "W": 57, "L": 25, "W_Pct": 0.695},
            {"teamAbbv": "MIN", "W": 56, "L": 26, "W_Pct": 0.683},
            {"teamAbbv": "LAC", "W": 51, "L": 31, "W_Pct": 0.622},
            {"teamAbbv": "DAL", "W": 50, "L": 32, "W_Pct": 0.610},
            {"teamAbbv": "PHX", "W": 49, "L": 33, "W_Pct": 0.598},
            {"teamAbbv": "NOP", "W": 49, "L": 33, "W_Pct": 0.598},
            {"teamAbbv": "LAL", "W": 47, "L": 35, "W_Pct": 0.573},
            {"teamAbbv": "SAC", "W": 46, "L": 36, "W_Pct": 0.561},
            {"teamAbbv": "GSW", "W": 46, "L": 36, "W_Pct": 0.561},
            {"teamAbbv": "HOU", "W": 41, "L": 41, "W_Pct": 0.500},
            {"teamAbbv": "UTA", "W": 31, "L": 51, "W_Pct": 0.378},
            {"teamAbbv": "MEM", "W": 27, "L": 55, "W_Pct": 0.329},
            {"teamAbbv": "SAS", "W": 22, "L": 60, "W_Pct": 0.268},
            {"teamAbbv": "POR", "W": 21, "L": 61, "W_Pct": 0.256},
        ],
    },

    "24_25": {
        "east": [
            {"teamAbbv": "CLE", "W": 64, "L": 18, "W_Pct": 0.780},
            {"teamAbbv": "BOS", "W": 61, "L": 21, "W_Pct": 0.744},
            {"teamAbbv": "NYK", "W": 51, "L": 31, "W_Pct": 0.622},
            {"teamAbbv": "IND", "W": 50, "L": 32, "W_Pct": 0.610},
            {"teamAbbv": "MIL", "W": 48, "L": 34, "W_Pct": 0.585},
            {"teamAbbv": "DET", "W": 44, "L": 38, "W_Pct": 0.537},
            {"teamAbbv": "ORL", "W": 41, "L": 41, "W_Pct": 0.500},
            {"teamAbbv": "ATL", "W": 40, "L": 42, "W_Pct": 0.488},
            {"teamAbbv": "CHI", "W": 39, "L": 43, "W_Pct": 0.476},
            {"teamAbbv": "MIA", "W": 37, "L": 45, "W_Pct": 0.451},
            {"teamAbbv": "TOR", "W": 30, "L": 52, "W_Pct": 0.366},
            {"teamAbbv": "BKN", "W": 26, "L": 56, "W_Pct": 0.317},
            {"teamAbbv": "PHI", "W": 24, "L": 58, "W_Pct": 0.293},
            {"teamAbbv": "CHA", "W": 19, "L": 63, "W_Pct": 0.232},
            {"teamAbbv": "WAS", "W": 18, "L": 64, "W_Pct": 0.220},
        ],
        "west": [
            {"teamAbbv": "OKC", "W": 68, "L": 14, "W_Pct": 0.829},
            {"teamAbbv": "HOU", "W": 52, "L": 30, "W_Pct": 0.634},
            {"teamAbbv": "LAL", "W": 50, "L": 32, "W_Pct": 0.610},
            {"teamAbbv": "DEN", "W": 50, "L": 32, "W_Pct": 0.610},
            {"teamAbbv": "LAC", "W": 50, "L": 32, "W_Pct": 0.610},
            {"teamAbbv": "MIN", "W": 49, "L": 33, "W_Pct": 0.598},
            {"teamAbbv": "GSW", "W": 48, "L": 34, "W_Pct": 0.585},
            {"teamAbbv": "MEM", "W": 48, "L": 34, "W_Pct": 0.585},
            {"teamAbbv": "SAC", "W": 40, "L": 42, "W_Pct": 0.488},
            {"teamAbbv": "DAL", "W": 39, "L": 43, "W_Pct": 0.476},
            {"teamAbbv": "PHX", "W": 36, "L": 46, "W_Pct": 0.439},
            {"teamAbbv": "POR", "W": 36, "L": 46, "W_Pct": 0.439},
            {"teamAbbv": "SAS", "W": 34, "L": 48, "W_Pct": 0.415},
            {"teamAbbv": "NOP", "W": 21, "L": 61, "W_Pct": 0.256},
            {"teamAbbv": "UTA", "W": 17, "L": 65, "W_Pct": 0.207},
        ],
    },

    "25_26": {
        "east": [
            {"teamAbbv": "DET", "W": 60, "L": 22, "W_Pct": 0.732},
            {"teamAbbv": "BOS", "W": 56, "L": 26, "W_Pct": 0.683},
            {"teamAbbv": "NYK", "W": 53, "L": 29, "W_Pct": 0.646},
            {"teamAbbv": "CLE", "W": 52, "L": 30, "W_Pct": 0.634},
            {"teamAbbv": "TOR", "W": 46, "L": 36, "W_Pct": 0.561},
            {"teamAbbv": "ATL", "W": 46, "L": 36, "W_Pct": 0.561},
            {"teamAbbv": "PHI", "W": 45, "L": 37, "W_Pct": 0.549},
            {"teamAbbv": "ORL", "W": 45, "L": 37, "W_Pct": 0.549},
            {"teamAbbv": "CHA", "W": 44, "L": 38, "W_Pct": 0.537},
            {"teamAbbv": "MIA", "W": 43, "L": 39, "W_Pct": 0.524},
            {"teamAbbv": "MIL", "W": 32, "L": 50, "W_Pct": 0.390},
            {"teamAbbv": "CHI", "W": 31, "L": 51, "W_Pct": 0.378},
            {"teamAbbv": "BKN", "W": 20, "L": 62, "W_Pct": 0.244},
            {"teamAbbv": "IND", "W": 19, "L": 63, "W_Pct": 0.232},
            {"teamAbbv": "WAS", "W": 17, "L": 65, "W_Pct": 0.207},
        ],
        "west": [
            {"teamAbbv": "OKC", "W": 64, "L": 18, "W_Pct": 0.780},
            {"teamAbbv": "SAS", "W": 62, "L": 20, "W_Pct": 0.756},
            {"teamAbbv": "DEN", "W": 54, "L": 28, "W_Pct": 0.659},
            {"teamAbbv": "LAL", "W": 53, "L": 29, "W_Pct": 0.646},
            {"teamAbbv": "HOU", "W": 52, "L": 30, "W_Pct": 0.634},
            {"teamAbbv": "MIN", "W": 49, "L": 33, "W_Pct": 0.598},
            {"teamAbbv": "PHX", "W": 45, "L": 37, "W_Pct": 0.549},
            {"teamAbbv": "POR", "W": 42, "L": 40, "W_Pct": 0.512},
            {"teamAbbv": "LAC", "W": 42, "L": 40, "W_Pct": 0.512},
            {"teamAbbv": "GSW", "W": 37, "L": 45, "W_Pct": 0.451},
            {"teamAbbv": "NOP", "W": 26, "L": 56, "W_Pct": 0.317},
            {"teamAbbv": "DAL", "W": 26, "L": 56, "W_Pct": 0.317},
            {"teamAbbv": "MEM", "W": 25, "L": 57, "W_Pct": 0.305},
            {"teamAbbv": "SAC", "W": 22, "L": 60, "W_Pct": 0.268},
            {"teamAbbv": "UTA", "W": 22, "L": 60, "W_Pct": 0.268},
        ],
    },
    "26_27": {
        "east": [
            {"teamAbbv": "DET", "W": 60, "L": 22, "W_Pct": 0.732},
            {"teamAbbv": "BOS", "W": 56, "L": 26, "W_Pct": 0.683},
            {"teamAbbv": "NYK", "W": 53, "L": 29, "W_Pct": 0.646},
            {"teamAbbv": "CLE", "W": 52, "L": 30, "W_Pct": 0.634},
            {"teamAbbv": "TOR", "W": 46, "L": 36, "W_Pct": 0.561},
            {"teamAbbv": "ATL", "W": 46, "L": 36, "W_Pct": 0.561},
            {"teamAbbv": "PHI", "W": 45, "L": 37, "W_Pct": 0.549},
            {"teamAbbv": "ORL", "W": 45, "L": 37, "W_Pct": 0.549},
            {"teamAbbv": "CHA", "W": 44, "L": 38, "W_Pct": 0.537},
            {"teamAbbv": "MIA", "W": 43, "L": 39, "W_Pct": 0.524},
            {"teamAbbv": "MIL", "W": 32, "L": 50, "W_Pct": 0.390},
            {"teamAbbv": "CHI", "W": 31, "L": 51, "W_Pct": 0.378},
            {"teamAbbv": "BKN", "W": 20, "L": 62, "W_Pct": 0.244},
            {"teamAbbv": "IND", "W": 19, "L": 63, "W_Pct": 0.232},
            {"teamAbbv": "WAS", "W": 17, "L": 65, "W_Pct": 0.207},
        ],
        "west": [
            {"teamAbbv": "OKC", "W": 64, "L": 18, "W_Pct": 0.780},
            {"teamAbbv": "SAS", "W": 62, "L": 20, "W_Pct": 0.756},
            {"teamAbbv": "DEN", "W": 54, "L": 28, "W_Pct": 0.659},
            {"teamAbbv": "LAL", "W": 53, "L": 29, "W_Pct": 0.646},
            {"teamAbbv": "HOU", "W": 52, "L": 30, "W_Pct": 0.634},
            {"teamAbbv": "MIN", "W": 49, "L": 33, "W_Pct": 0.598},
            {"teamAbbv": "PHX", "W": 45, "L": 37, "W_Pct": 0.549},
            {"teamAbbv": "POR", "W": 42, "L": 40, "W_Pct": 0.512},
            {"teamAbbv": "LAC", "W": 42, "L": 40, "W_Pct": 0.512},
            {"teamAbbv": "GSW", "W": 37, "L": 45, "W_Pct": 0.451},
            {"teamAbbv": "NOP", "W": 26, "L": 56, "W_Pct": 0.317},
            {"teamAbbv": "DAL", "W": 26, "L": 56, "W_Pct": 0.317},
            {"teamAbbv": "MEM", "W": 25, "L": 57, "W_Pct": 0.305},
            {"teamAbbv": "SAC", "W": 22, "L": 60, "W_Pct": 0.268},
            {"teamAbbv": "UTA", "W": 22, "L": 60, "W_Pct": 0.268},
        ],
    },
}

In [62]:
# Preseason vegas odds for each season
vegas_odds = {
    "21_22": {
        "BKN": {"odds": 240, "wl_ou": 56.5},
        "LAL": {"odds": 400, "wl_ou": 52.5},
        "MIL": {"odds": 900, "wl_ou": 54.5},
        "GSW": {"odds": 900, "wl_ou": 48.5},
        "PHX": {"odds": 1500, "wl_ou": 51.5},
        "UTA": {"odds": 1600, "wl_ou": 52.5},
        "PHI": {"odds": 1600, "wl_ou": 50.5},
        "LAC": {"odds": 1600, "wl_ou": 45.5},
        "DEN": {"odds": 2200, "wl_ou": 47.5},
        "MIA": {"odds": 2500, "wl_ou": 48.5},
        "DAL": {"odds": 3000, "wl_ou": 48.5},
        "ATL": {"odds": 3500, "wl_ou": 47.5},
        "BOS": {"odds": 4000, "wl_ou": 45.5},
        "POR": {"odds": 5000, "wl_ou": 44.5},
        "CHI": {"odds": 6600, "wl_ou": 42.5},
        "NYK": {"odds": 8000, "wl_ou": 41.5},
        "MEM": {"odds": 10000, "wl_ou": 41.5},
        "IND": {"odds": 10000, "wl_ou": 42.5},
        "NOP": {"odds": 10000, "wl_ou": 39.5},
        "CHA": {"odds": 10000, "wl_ou": 38.5},
        "WAS": {"odds": 15000, "wl_ou": 33.5},
        "TOR": {"odds": 15000, "wl_ou": 35.5},
        "SAC": {"odds": 25000, "wl_ou": 36.5},
        "MIN": {"odds": 25000, "wl_ou": 35.5},
        "SAS": {"odds": 30000, "wl_ou": 28.5},
        "CLE": {"odds": 50000, "wl_ou": 26.5},
        "ORL": {"odds": 50000, "wl_ou": 22.5},
        "OKC": {"odds": 50000, "wl_ou": 23.5},
        "DET": {"odds": 50000, "wl_ou": 24.5},
        "HOU": {"odds": 50000, "wl_ou": 24.5},
    },

    "22_23": {
        "BOS": {"odds": 500, "wl_ou": 54.5},
        "GSW": {"odds": 600, "wl_ou": 52.5},
        "MIL": {"odds": 650, "wl_ou": 53.5},
        "BKN": {"odds": 700, "wl_ou": 50.5},
        "LAC": {"odds": 700, "wl_ou": 52.5},
        "PHX": {"odds": 1000, "wl_ou": 52.5},
        "PHI": {"odds": 1400, "wl_ou": 50.5},
        "MIA": {"odds": 1600, "wl_ou": 49.5},
        "DEN": {"odds": 1800, "wl_ou": 51.5},
        "LAL": {"odds": 1800, "wl_ou": 44.5},
        "MEM": {"odds": 2000, "wl_ou": 49.5},
        "DAL": {"odds": 2500, "wl_ou": 48.5},
        "MIN": {"odds": 2800, "wl_ou": 49.5},
        "CLE": {"odds": 3000, "wl_ou": 46.5},
        "TOR": {"odds": 4000, "wl_ou": 46.5},
        "CHI": {"odds": 4000, "wl_ou": 41.5},
        "NOP": {"odds": 4000, "wl_ou": 45.5},
        "ATL": {"odds": 5000, "wl_ou": 46.5},
        "NYK": {"odds": 6600, "wl_ou": 38.5},
        "POR": {"odds": 8000, "wl_ou": 39.5},
        "CHA": {"odds": 15000, "wl_ou": 34.5},
        "WAS": {"odds": 25000, "wl_ou": 35.5},
        "DET": {"odds": 50000, "wl_ou": 29.5},
        "OKC": {"odds": 50000, "wl_ou": 23.5},
        "ORL": {"odds": 50000, "wl_ou": 26.5},
        "IND": {"odds": 50000, "wl_ou": 24.5},
        "SAC": {"odds": 50000, "wl_ou": 34.5},
        "SAS": {"odds": 50000, "wl_ou": 22.5},
        "HOU": {"odds": 50000, "wl_ou": 23.5},
        "UTA": {"odds": 50000, "wl_ou": 23.5},
    },

    "23_24": {
        "BOS": {"odds": 450, "wl_ou": 54.5},
        "DEN": {"odds": 450, "wl_ou": 52.5},
        "PHX": {"odds": 600, "wl_ou": 51.5},
        "MIL": {"odds": 600, "wl_ou": 54.5},
        "GSW": {"odds": 1200, "wl_ou": 48.5},
        "LAL": {"odds": 1500, "wl_ou": 47.5},
        "MIA": {"odds": 1600, "wl_ou": 45.5},
        "PHI": {"odds": 1800, "wl_ou": 48.5},
        "LAC": {"odds": 2200, "wl_ou": 46.5},
        "MEM": {"odds": 2200, "wl_ou": 45.5},
        "DAL": {"odds": 2500, "wl_ou": 45.5},
        "CLE": {"odds": 2500, "wl_ou": 50.5},
        "SAC": {"odds": 3500, "wl_ou": 44.5},
        "NOP": {"odds": 4000, "wl_ou": 44.5},
        "NYK": {"odds": 5000, "wl_ou": 45.5},
        "MIN": {"odds": 6600, "wl_ou": 44.5},
        "ATL": {"odds": 8000, "wl_ou": 42.5},
        "TOR": {"odds": 8000, "wl_ou": 36.5},
        "OKC": {"odds": 10000, "wl_ou": 44.5},
        "CHI": {"odds": 12500, "wl_ou": 37.5},
        "BKN": {"odds": 12500, "wl_ou": 37.5},
        "POR": {"odds": 12500, "wl_ou": 28.5},
        "SAS": {"odds": 15000, "wl_ou": 28.5},
        "UTA": {"odds": 25000, "wl_ou": 35.5},
        "ORL": {"odds": 25000, "wl_ou": 37.5},
        "IND": {"odds": 25000, "wl_ou": 38.5},
        "HOU": {"odds": 25000, "wl_ou": 31.5},
        "WAS": {"odds": 50000, "wl_ou": 24.5},
        "CHA": {"odds": 50000, "wl_ou": 31.5},
        "DET": {"odds": 50000, "wl_ou": 28.5},
    },

    "24_25": {
        "BOS": {"odds": 325, "wl_ou": 58.5},
        "OKC": {"odds": 675, "wl_ou": 57.5},
        "NYK": {"odds": 700, "wl_ou": 53.5},
        "PHI": {"odds": 1000, "wl_ou": 50.5},
        "DAL": {"odds": 1100, "wl_ou": 49.5},
        "DEN": {"odds": 1100, "wl_ou": 51.5},
        "MIN": {"odds": 1100, "wl_ou": 51.5},
        "MIL": {"odds": 1400, "wl_ou": 49.5},
        "PHX": {"odds": 1500, "wl_ou": 48.5},
        "CLE": {"odds": 3500, "wl_ou": 48.5},
        "MEM": {"odds": 3500, "wl_ou": 47.5},
        "ORL": {"odds": 4000, "wl_ou": 47.5},
        "GSW": {"odds": 4000, "wl_ou": 43.5},
        "LAL": {"odds": 4000, "wl_ou": 43.5},
        "MIA": {"odds": 5000, "wl_ou": 44.5},
        "NOP": {"odds": 5000, "wl_ou": 46.5},
        "IND": {"odds": 6600, "wl_ou": 46.5},
        "SAC": {"odds": 6600, "wl_ou": 46.5},
        "HOU": {"odds": 8000, "wl_ou": 43.5},
        "LAC": {"odds": 12500, "wl_ou": 35.5},
        "SAS": {"odds": 15000, "wl_ou": 35.5},
        "ATL": {"odds": 50000, "wl_ou": 36.5},
        "UTA": {"odds": 50000, "wl_ou": 28.5},
        "DET": {"odds": 100000, "wl_ou": 25.5},
        "CHA": {"odds": 100000, "wl_ou": 30.5},
        "CHI": {"odds": 100000, "wl_ou": 28.5},
        "BKN": {"odds": 100000, "wl_ou": 19.5},
        "POR": {"odds": 100000, "wl_ou": 21.5},
        "TOR": {"odds": 100000, "wl_ou": 29.5},
        "WAS": {"odds": 100000, "wl_ou": 20.5},
    },

    "25_26": {
        "OKC": {"odds": 240, "wl_ou": 62.5},
        "DEN": {"odds": 550, "wl_ou": 53.5},
        "CLE": {"odds": 750, "wl_ou": 56.5},
        "NYK": {"odds": 900, "wl_ou": 53.5},
        "MIN": {"odds": 1300, "wl_ou": 49.5},
        "HOU": {"odds": 1400, "wl_ou": 52.5},
        "LAL": {"odds": 1600, "wl_ou": 46.5},
        "LAC": {"odds": 1800, "wl_ou": 49.5},
        "ORL": {"odds": 1800, "wl_ou": 51.5},
        "GSW": {"odds": 2500, "wl_ou": 47.5},
        "DET": {"odds": 3300, "wl_ou": 46.5},
        "DAL": {"odds": 3500, "wl_ou": 41.5},
        "PHI": {"odds": 4000, "wl_ou": 43.5},
        "ATL": {"odds": 4000, "wl_ou": 46.5},
        "MIL": {"odds": 5500, "wl_ou": 43.5},
        "BOS": {"odds": 6000, "wl_ou": 41.5},
        "SAS": {"odds": 6600, "wl_ou": 44.5},
        "IND": {"odds": 10000, "wl_ou": 37.5},
        "TOR": {"odds": 10000, "wl_ou": 39.5},
        "MEM": {"odds": 12500, "wl_ou": 39.5},
        "MIA": {"odds": 20000, "wl_ou": 37.5},
        "NOP": {"odds": 30000, "wl_ou": 30.5},
        "PHX": {"odds": 50000, "wl_ou": 30.5},
        "POR": {"odds": 50000, "wl_ou": 35.5},
        "SAC": {"odds": 50000, "wl_ou": 35.5},
        "CHI": {"odds": 50000, "wl_ou": 33.5},
        "CHA": {"odds": 100000, "wl_ou": 27.5},
        "BKN": {"odds": 100000, "wl_ou": 19.5},
        "UTA": {"odds": 100000, "wl_ou": 18.5},
        "WAS": {"odds": 100000, "wl_ou": 20.5},
    },

    "26_27": {
        "ATL": {"odds": -105, "wl_ou": 43.5},
        "BOS": {"odds": -115, "wl_ou": 51.5},
        "BKN": {"odds": 100, "wl_ou": 24.5},
        "CHA": {"odds": -120, "wl_ou": 37.5},
        "CHI": {"odds": -135, "wl_ou": 27.5},
        "CLE": {"odds": -115, "wl_ou": 47.5},
        "DAL": {"odds": -110, "wl_ou": 34.5},
        "DEN": {"odds": 105, "wl_ou": 49.5},
        "DET": {"odds": -105, "wl_ou": 49.5},
        "GSW": {"odds": 100, "wl_ou": 40.5},
        "HOU": {"odds": -110, "wl_ou": 47.5},
        "IND": {"odds": -125, "wl_ou": 44.5},
        "LAC": {"odds": 100, "wl_ou": 30.5},
        "LAL": {"odds": -105, "wl_ou": 46.5},
        "MEM": {"odds": -120, "wl_ou": 28.5},
        "MIA": {"odds": 105, "wl_ou": 46.5},
        "MIL": {"odds": -115, "wl_ou": 25.5},
        "MIN": {"odds": -110, "wl_ou": 48.5},
        "NOP": {"odds": -115, "wl_ou": 27.5},
        "NYK": {"odds": 100, "wl_ou": 52.5},
        "OKC": {"odds": -105, "wl_ou": 62.5},
        "ORL": {"odds": -130, "wl_ou": 43.5},
        "PHI": {"odds": 100, "wl_ou": 50.5},
        "PHX": {"odds": -120, "wl_ou": 38.5},
        "POR": {"odds": 100, "wl_ou": 42.5},
        "SAS": {"odds": -115, "wl_ou": 59.5},
        "SAC": {"odds": -105, "wl_ou": 21.5},
        "TOR": {"odds": -125, "wl_ou": 45.5},
        "UTA": {"odds": -145, "wl_ou": 35.5},
        "WAS": {"odds": -105, "wl_ou": 34.5},
    },
}

In [63]:
# Create dataframe to compare standings

season = "26_27"

# WEST


# Model standings
model_west = (
    pd.DataFrame(results[season]["standings"]["West"])
    .T
    .reset_index()
    .rename(columns={
        "index": "Team",
        "W_Pct": "W%"
    })
)

# Keep only the relevant columns
model_west = model_west[["Team", "W"]].rename(
    columns={"W": "Model Wins"}
)

# Adjust model wins:
# Winning record -> 2 additional losses
# Losing record -> 2 additional wins
model_west.loc[model_west["Model Wins"] > 41, "Model Wins"] -= 2
model_west.loc[model_west["Model Wins"] < 41, "Model Wins"] += 2



# Actual standings
actual_west = (
    pd.DataFrame(nba_standings[season]["west"])
    .rename(columns={
        "teamAbbv": "Team",
        "W_Pct": "W%"
    })
)

actual_west = actual_west[["Team", "W"]].rename(
    columns={"W": "Actual Wins"}
)

# Vegas
vegas_west = (
    pd.DataFrame.from_dict(
        vegas_odds[season],
        orient="index"
    )
    .reset_index()
    .rename(columns={
        "index": "Team",
        "wl_ou": "W-L O/U"
    })
)

vegas_west = vegas_west[["Team", "W-L O/U"]]

# Merge
west_final = (
    model_west
    .merge(vegas_west, on="Team", how="left")
    .merge(actual_west, on="Team", how="left")
)

# Differences
west_final["Model - Vegas"] = (
    west_final["Model Wins"] - west_final["W-L O/U"]
)

west_final["Actual - Vegas"] = (
    west_final["Actual Wins"] - west_final["W-L O/U"]
)


# Final Column Order
west_final = west_final[
    [
        "Team",
        "Model Wins",
        "W-L O/U",
        "Model - Vegas",
        "Actual - Vegas",
        "Actual Wins"
    ]
]

# Sort by actual standings
west_final = (
    west_final
    .sort_values("Model Wins", ascending=False)
    .reset_index(drop=True)
)
# Clean numeric formatting
west_final["Model Wins"] = west_final["Model Wins"].astype(int)
west_final["Actual Wins"] = west_final["Actual Wins"].astype(int)
west_final["W-L O/U"] = west_final["W-L O/U"].astype(float)

west_final["Model - Vegas"] = west_final["Model - Vegas"].round(1)
west_final["Actual - Vegas"] = west_final["Actual - Vegas"].round(1)

# EAST

# Model standings
model_east = (
    pd.DataFrame(results[season]["standings"]["East"])
    .T
    .reset_index()
    .rename(columns={
        "index": "Team",
        "W_Pct": "W%"
    })
)

model_east = model_east[["Team", "W"]].rename(
    columns={"W": "Model Wins"}
)

# Adjust model wins:
# Winning record -> 2 additional losses
# Losing record -> 2 additional wins
model_east.loc[model_east["Model Wins"] > 41, "Model Wins"] -= 2
model_east.loc[model_east["Model Wins"] < 41, "Model Wins"] += 2


# Actual standings
actual_east = (
    pd.DataFrame(nba_standings[season]["east"])
    .rename(columns={
        "teamAbbv": "Team",
        "W_Pct": "W%"
    })
)

actual_east = actual_east[["Team", "W"]].rename(
    columns={"W": "Actual Wins"}
)


# Vegas
vegas_east = (
    pd.DataFrame.from_dict(
        vegas_odds[season],
        orient="index"
    )
    .reset_index()
    .rename(columns={
        "index": "Team",
        "wl_ou": "W-L O/U"
    })
)

vegas_east = vegas_east[["Team", "W-L O/U"]]

# Merge
east_final = (
    model_east
    .merge(vegas_east, on="Team", how="left")
    .merge(actual_east, on="Team", how="left")
)

# Differences
east_final["Model - Vegas"] = (
    east_final["Model Wins"] - east_final["W-L O/U"]
)

east_final["Actual - Vegas"] = (
    east_final["Actual Wins"] - east_final["W-L O/U"]
)

# Final Column Order
east_final = east_final[
    [
        "Team",
        "Model Wins",
        "W-L O/U",
        "Model - Vegas",
        "Actual - Vegas",
        "Actual Wins"
    ]
]

# Sort by actual standings
east_final = (
    east_final
    .sort_values("Model Wins", ascending=False)
    .reset_index(drop=True)
)

# Formatting
east_final["Model Wins"] = east_final["Model Wins"].astype(int)
east_final["Actual Wins"] = east_final["Actual Wins"].astype(int)
east_final["W-L O/U"] = east_final["W-L O/U"].astype(float)

east_final["Model - Vegas"] = east_final["Model - Vegas"].round(1)
east_final["Actual - Vegas"] = east_final["Actual - Vegas"].round(1)

In [64]:
# Compare model vs vegas accuracies West
west_error = west_final.copy()

# Absolute error from actual win total
west_error["Model Abs Error"] = (
    west_error["Model Wins"] - west_error["Actual Wins"]
).abs()

west_error["Vegas Abs Error"] = (
    west_error["W-L O/U"] - west_error["Actual Wins"]
).abs()


# Summary statistics
west_stats = pd.DataFrame({
    "Mean": [
        west_error["Model Abs Error"].mean(),
        west_error["Vegas Abs Error"].mean()
    ],
    "Median": [
        west_error["Model Abs Error"].median(),
        west_error["Vegas Abs Error"].median()
    ],
    "Std Dev": [
        west_error["Model Abs Error"].std(),
        west_error["Vegas Abs Error"].std()
    ],
    "Min": [
        west_error["Model Abs Error"].min(),
        west_error["Vegas Abs Error"].min()
    ],
    "Max": [
        west_error["Model Abs Error"].max(),
        west_error["Vegas Abs Error"].max()
    ]
}, index=["Model", "Vegas"]).round(2)

display(west_final)
display(west_stats)

   Team  Model Wins  W-L O/U  Model - Vegas  Actual - Vegas  Actual Wins
0   SAS          63     59.5            3.5             2.5           62
1   OKC          59     62.5           -3.5             1.5           64
2   POR          57     42.5           14.5            -0.5           42
3   LAL          55     46.5            8.5             6.5           53
4   GSW          46     40.5            5.5            -3.5           37
5   DEN          41     49.5           -8.5             4.5           54
6   MIN          41     48.5           -7.5             0.5           49
7   MEM          34     28.5            5.5            -3.5           25
8   NOP          31     27.5            3.5            -1.5           26
9   PHX          30     38.5           -8.5             6.5           45
10  HOU          27     47.5          -20.5             4.5           52
11  SAC          26     21.5            4.5             0.5           22
12  UTA          25     35.5          -10.5           -13.5           22
13  DAL          16     34.5          -18.5            -8.5           26
14  LAC          11     30.5          -19.5            11.5           42

        Mean  Median  Std Dev  Min   Max
Model  10.33     9.0     8.49  1.0  31.0
Vegas   4.63     3.5     4.02  0.5  13.5

In [65]:
# Compare model vs vegas accuracies East

east_error = east_final.copy()

# Absolute error from actual win total
east_error["Model Abs Error"] = (
    east_error["Model Wins"] - east_error["Actual Wins"]
).abs()

east_error["Vegas Abs Error"] = (
    east_error["W-L O/U"] - east_error["Actual Wins"]
).abs()


# Summary statistics
east_stats = pd.DataFrame({
    "Mean": [
        east_error["Model Abs Error"].mean(),
        east_error["Vegas Abs Error"].mean()
    ],
    "Median": [
        east_error["Model Abs Error"].median(),
        east_error["Vegas Abs Error"].median()
    ],
    "Std Dev": [
        east_error["Model Abs Error"].std(),
        east_error["Vegas Abs Error"].std()
    ],
    "Min": [
        east_error["Model Abs Error"].min(),
        east_error["Vegas Abs Error"].min()
    ],
    "Max": [
        east_error["Model Abs Error"].max(),
        east_error["Vegas Abs Error"].max()
    ]
}, index=["Model", "Vegas"]).round(2)

display(east_final)
display(east_stats)

   Team  Model Wins  W-L O/U  Model - Vegas  Actual - Vegas  Actual Wins
0   NYK          61     52.5            8.5             0.5           53
1   MIA          57     46.5           10.5            -3.5           43
2   PHI          57     50.5            6.5            -5.5           45
3   BOS          55     51.5            3.5             4.5           56
4   CLE          49     47.5            1.5             4.5           52
5   ORL          46     43.5            2.5             1.5           45
6   IND          45     44.5            0.5           -25.5           19
7   ATL          42     43.5           -1.5             2.5           46
8   WAS          42     34.5            7.5           -17.5           17
9   CHA          41     37.5            3.5             6.5           44
10  DET          38     49.5          -11.5            10.5           60
11  TOR          34     45.5          -11.5             0.5           46
12  MIL          27     25.5            1.5             6.5           32
13  CHI          26     27.5           -1.5             3.5           31
14  BKN          18     24.5           -6.5            -4.5           20

       Mean  Median  Std Dev  Min   Max
Model  9.53     5.0     8.70  1.0  26.0
Vegas  6.50     4.5     6.77  0.5  25.5